### ISSUE TITLE
Active subscription but no payment type defined, is not consistent

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#101]
Build: MASTER 30.05.2016
Version: BES V16.0 Fix 4+
Authentication mode: internal
Test category: creative Test

[Steps to reproduce]
1. Login as administrator on blue portal;
2. Login as supplier, create customer, do not define a default payment type for customer(using Manage payment types), and no organization address.
3. Click on "Update configuration settings", then set "HIDE_PAYMENT_INFORMATION" to true;
4. Login marketplace as customer and subscribe to non-free service
5. Login as administrator on blue portal;
6. Click on "Update configuration settings", then set "HIDE_PAYMENT_INFORMATION" to false;
7. Login marketplace as customer;
8. Click on "ACCOUNT->Subscriptions", select the subscription which created in step 4, then click on "Payment" button.

[Expected result]
Subscription is suspended after step 6.

[Observed result] 
The subscription in step 8 is active, but no billing type is defined.
In step 8, the billing address and payment type was displayed, the billing address was displayed as a newly created default billing address (in my case empty), and the payment type was displayed as "Currently no payment type is enabled for you. Please contact your supplier or reseller."

[Details]
Normally, if no payment type is defined for a subscription, the subscription is suspended. In this case manage payment types called by supplier does not show "Invoice" as a payment type for this customer, but the subscription is active. This is inconsistent behavior.
It is OK in my opinion if INVOICE is defined for the customer by the supplier, that INVOICE is used as a default payment type for the subscription.

**Comment by SylviaDehn** [comment]
Please be careful when you fix this, that the billing run will still work while hide payment info is set to true.

**Comment by GoebelL** [comment]
As agreed, the setting HIDE_PAYMENT_INFORMATION will be changed to read-only. This will also avoid the given case of reactivation with possible effects on billing.

**Comment by GoebelL** [comment]
Documentation needs to be adapted accordingly.

**Comment by SuessI** [comment]
Documentation adapted, reviewed, and checked into master.

**Comment by SylviaDehn** [comment]
verified 16.0 fix6 06.07.2016
