### ISSUE TITLE
VMware controller - the operations "Restart" and "Restore" does not work properly

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#106]
The sample technical service contains the operations "start", "stop", "restart", "snapshot" and "restore".
The operations "restart" and "restore" end with error, because starting the VM will be tried twice.

**Comment by StavrevaS** [comment]
The error cannot be reproduced always, sometimes the operations work. I have tested with default APP timeout 15 sec and than with 30 sec. 
If the timeout is increased (more time to wait between the provisioning or operation steps), everything works fine.
Nevertheless some improvement is made in the state machines for restart operation and delete VM.
See commit [ec7953f6c3b4ff49cb90d72dfb2128733006fe58](https://github.com/servicecatalog/development/commit/ec7953f6c3b4ff49cb90d72dfb2128733006fe58).

**Comment by SylviaDehn** [comment]
[Build] 2016/08/01 verified
I cannot reproduce this problem even with default timeout
