### ISSUE TITLE
HIDE_PAYMENT_INFORMATION value can be changed

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#109]
Version: 16.0.4+ 
Date: 2016/06/02 
[Test category] creative

[Steps to reproduce]
1. for installation, in configsetttings.properties set HIDE_PAYMENT_INFORMATION = true
.... customer works as always ...
2. run update database script with configsetttings.properties
HIDE_PAYMENT_INFORMATION = false

[Expected result]
should not be possible, because set HIDE_PAYMENT_INFORMATION field already exists in DB

[Observed result]
I can change the parameter back and forth even though this should not be possible

[Details]
See documentation for this restriction.

**Comment by SylviaDehn** [comment]
I can still change it as platform operator too. I am wondering if I have a build that is too old (UNIT build this morning, BES_MASTER_UNIT-1512 2016/06/02)

**Comment by kowalczyka** [comment]
It is not in the MASTER branch yet - currently Jenkins webtests job are running to verify that everything is ok. 

Could you please use: BES_GitHub_BUGFIX_Unit - 64 (2016-06-02 09:52:22)

**Comment by kowalczyka** [comment]
[Details of fix]
Config property made read-only.

**Comment by GoebelL** [comment]
It was created from retesting the fix #100. But testing was done on master before the fix has been available there. 
This issue is invalid. As checked, #100 has been fixed correctly.
