### ISSUE TITLE
Empty HIDDEN_UI_ELEMENTS in configsettings.properties

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#113]
[Version]
16.0.4+

[How to reproduce]
1. Upgrade OSCM to 16.0.5 as described in the documentation
2. As platform operator administrator login to the OSCM administration portal.
3. On Update Configuration Settings page, check the setting of HIDDEN_UI_ELEMENTS

[Observed result]
HIDDEN_UI_ELEMENTS contains billing adapter UI pages

[Expected result]
HIDDEN_UI_ELEMENTS doesn't contain billing adapter UI pages

[Detail]
The billing Adapter is released since 16.0.3, therefore the the UI should be visible by default.

**Comment by GoebelL** [comment]
I guess also documentation needs to be updated. Please check.

**Comment by SuessI** [comment]
In the OSCM delivery, the line
 # HIDDEN_UI_ELEMENTS=operator.manageBillingAdapters,techService.viewBillingAdapters
appears just as an example - it has a comment sign.
The original reporter said that we should leave the example.
The documentation has already been updated for 16.0 Fix 3.
So nothing needs to be done here -> closing.
