### ISSUE TITLE
The page information displayed incorrectly when search subscription

### ISSUE THREAD

**Issue by wangyingfnst** [servicecatalog/development#114]
Date: 2016/06/02
[Test category]: creative Test
Severity：Minor

[Steps to reproduce]
1. Login in marketplace as customer;
2. Subscribe to service for more than 10 times and assign the customer to these subscriptions;
3. Click on "ACCOUNT->Subscriptions";
4. Input a space into the search box, then click on the search button;
5. Click on "MY SUBSCRIPTIONS";
6. Input a space into the search box, then click on the search button.

[Expected result]
In step 4 and step 6, no subscriptions should be displayed in the screen, and the information of pages should not be displayed.

[Observed result]
In step 4 and step 6, no subscriptions was displayed in the screen, but the information of pages was displayed.

![the page information displayed incorrectly when search subscription](https://cloud.githubusercontent.com/assets/14818896/15816141/009ffa48-2c04-11e6-8297-ab20c598850f.png)

**Comment by badziakp** [comment]
This issue will be not reproducable after resolving issue #127. (Search by 'space' will show all the subscriptions). I checked described case with non-existent text, and it also works as it should.

**Comment by badziakp** [comment]
Issue #127 is closed so I'm closing this one too.

**Comment by jiangweiyi** [comment]
Verified by FNST
[verified-version] V16.0 fix6
[verified-details]The issue cannot be reproduced, so verified.
