### ISSUE TITLE
The page jumped incorrectly when input numbers with letters

### ISSUE THREAD

**Issue by wangyingfnst** [servicecatalog/development#115]
Date: 2016/06/02
[Test category]: creative Test
Severity：Minor

[Steps to reproduce]
1. Login in marketplace as customer;
2. Subscribe to service for more than 10 times and assign customer to these subscripitons;
3. Click on "ACCOUNT->Subscriptions", click page 1;
4. Input “abc” into the input box of page, then click on “Go” button;
5. Input “2abc” into the input box of page, then click on "Go" button;
6. Click on "MY SUBSCRIPTIONS", click page 1;
7. Input “abc” into the input box of page, then click on “Go” button;
8. Input “2abc” into the input box of page, then click on "Go" button.

[Expected result]
In step 4, step 5, step 7 and step 8, the system should not make any response, and the page should be stay in the current page 1.

[Observed result]
In step 4 and step 7, the system made no  response, and the page stayed in the current page 1.
But in step 5 and step 8, the page jumped to page 2.

**Comment by DawidCh** [comment]
Hi.
In my environment when I filter out all the subscription and I do not have any rows in my table the paginator is hidden so I do not see situation when I am on page 2. Could you please send some screenshot?
Regards, Dawid
![Uploading Untitled.png…]()

**Comment by DawidCh** [comment]
CLosed by mistake.

**Comment by DawidCh** [comment]
[Details of fix]
Now the paginator field is accepting nothing but numbers.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/09 verified
