### ISSUE TITLE
Service search behaves differently from subscription search

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#117]
Reported on behalf of @SylviaDehn.
 
Version: 16.0.3+
Date: 2016/04/20
[Test category] creative

[Steps to reproduce]
1. log in at marketplace as customer
a subscription exists with name "bunny on egg"
a service exists with name "bunny on egg"

2. go to account->subscriptions
3. search for subscription with name "unny"
4. search for service with name "unny" at service level

[Expected result]
search for "unny" will result in "bunny on egg" service/subscription

[Observed result]
This works for subscriptions ("Bunny on egg" is found), but not for service search

[Details]
It would be nice if this worked at the service level too. Sometimes a partial 
word search works (e.g. exampl instead of example).
If this cannot be done, it should be documented

**Comment by GoebelL** [comment]
>Sometimes a partial word search works (e.g. exampl instead of example).
That's not a bug, but a feature.

I have taken a look into the old service search implementation and found the reason. The service search is using keyword stemming analyzer in compare to subscription search. In our Product domain class I can find Analyzer definitions using classes SnowballPorterFilterFactory and GermanStemFilterFactory. 

It makes much sense to use stemming in subscription search as well. 

@DawidCh 
Please check if same stemming can be added to subscription search. If the effort is reasonable, please fix this for 16.0.5.

**Comment by badziakp** [comment]
I checked the latest version and partial word search doesn't work on subscriptions either. Should we implement partial word search in both options?

**Comment by GoebelL** [comment]
Sorry the report is misleading. The service search is fine and should not be changed. 
My comment referred only to:
>Sometimes a partial word search works (e.g. exampl instead of example).

This is the difference:

[Steps to reproduce]
1. log in at marketplace as customer
a subscription exists with name "example service"
a service exists with name "example service"

[Expected result]
Search with similar words "exampl", "Examples" will will find "example service" for service/subscription

[Observed result]
Search with similar words "exampl", "Examples" will will find "example service" for service, but NOT for subscription

=> Missing stemming for subscription search.

**Comment by MiethanerR** [comment]
added english stemming to the subscription search. fix was merged into master.

**Comment by MiethanerR** [comment]
fix was merged with master

**Comment by SylviaDehn** [comment]
[Build] 2016/08/09 verified  (works as search for service)
stemming works for endings such as "e", "s" etc.
e.g. search for "boat", "boating" will find "boats"

**Comment by SuessI** [comment]
The fix of this issue required an update of the search index structures. In an update installation, we must delete more than one index directory now in the index base of master indexer domain and bes domain. The Installation Guide was adapted to reflect this.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/17 verified installation guide
