### ISSUE TITLE
The string "Search subscriptions" in the search field is not shown with IE9.

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#118]
Date: 2016/06/02
[Test category]: creative Test

Severity: minor

[Steps to reproduce]:
1. Login as customer to the marketplace page.
2. Go to Account--Subscription page.
3. Check the subscription search field.

[Expected result]
There show "search subscriptions"

[Observed result]
No string "search subscriptions" in the search field with IE9.
![q -20160607094838](https://cloud.githubusercontent.com/assets/15228666/15843549/8a7ecf82-2c95-11e6-85b3-03c8053e4d50.png)

**Comment by GoebelL** [comment]
Please check.

**Comment by wangyingfnst** [comment]
The string "Search services" was also not displayed in the search field with IE9.

**Comment by grubskim** [comment]
There is no "placeholder" attribute support in IE9 and lower. I have added three methods in javascript to simulate this behavior. These methods will be invoked only if the browser does not support placeholders.

**Comment by SylviaDehn** [comment]
[Build] 2015/08/09 verified
