### ISSUE TITLE
The page cannot be returned when click on "Previous" button with the subscription name as null

### ISSUE THREAD

**Issue by wangyingfnst** [servicecatalog/development#120]
Date: 2016/06/02
[Test category]: creative Test
Severity：Minor

[Steps to reproduce]
1. Login in marketplace as customer;
2. Select a service, then click on "Show Details->Get it now";
3. Empty the subscription name, then click on "Previous" button.

[Expected result]
The page should be returned successfully.

[Observed result]
The page cannot be returned with the error message "Please correct the information in the highlighted fields.".
![the page cannot be returned when click on previous button with the subscription name as null](https://cloud.githubusercontent.com/assets/14818896/15847299/59ac82ce-2cb7-11e6-835b-80bb6e4d3d1e.png)

**Comment by GoebelL** [comment]
The mandatory Subscription name is filled by default. So, this use case is a bit uncommon.
Please fix the previous button navigation. 

For fixing: I guess the control in the JSF include or faclet should miss out the validation phase, with using immediate="true".

**Comment by badziakp** [comment]
[Fix details]
User can click [Previous] button without given subscription id.

**Comment by wangyingfnst** [comment]
Verified by FNST
[Verified-build] V16.1 GA1
[Verified-details] Now click "Previous" button when Subscription name is empty will return page correctly , so verified.
