### ISSUE TITLE
After changding the payment information by supplier, the subscription is suspended when the HIDE_PAYMENT_INFORMATION is true

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#121]
Date: 2016/06/02
[Test category]: creative Test

Severity: minor

[Steps to reproduce]
1. Set the HIDE_PAYMENT_INFORMATION as true in configsetting.properties file.
2. Install CTMG.
3. Login as customer, subscribe a service.
4. Login as supplier, click on "manage payment types", check all the checkbox, click on "save" button.
5. Login as customer to check the subscription status.
6. Login as supplier, click on "manage payment types", uncheck all the checkbox, click on "save" button.
7. Login as customer to check the subscription status.

[Expected result]
Since the payment types are not used on this platform,
After step5, the status should be active.
After step7, the status should be active.

[Observed result]
After step5, the status is active.
After step7, the status is suspended.

**Comment by GoebelL** [comment]
The subscriptions are suspended, when the service manager disables the used payment types. The described [Observed result] is the correct behavior.
