### ISSUE TITLE
Inconsistent payment types with HIDE_PAYMENT_INFORMATION

### ISSUE THREAD

**Issue by mdehn** [servicecatalog/development#122]
Version: 16.0.5
Date: 2016/06/08
[Test category]: creative Test

[Steps to reproduce]
1. Set HIDE_PAYMENT_INFORMATION to "true" when upgrading to 16.0.5
2. As supplier remove payment types from the customer
3. Subscriptions of the customer become "suspended" 
4. Customer has to update the payment type  

[Expected result]
Customer can update the payment type

[Observed result]
Customer cannot update the payment type

The purpose of HIDE_PAYMENT_INFORMATION set to "true" is to not ask customers for information, which is not required. Therefore this issue is not solved by letting the customer update the payment type. Rather hide the "Manage payment types" page for suppliers, in order to avoid the situation described above.

**Comment by GoebelL** [comment]
Please make the "manage payment types" page hidden in admin portal. Take care that it will also not be accessible with deep links, like #119.

**Comment by redmond2683** [comment]
Fixed in 272c858

**Comment by redmond2683** [comment]
Please adapt the online documentations to this change of behaviour.

**Comment by SuessI** [comment]
Red, I just completed the documentation in English and German for this. 
Please adapt the Japanese.

**Comment by redmond2683** [comment]
Adapted the Japanese documentation

**Comment by SylviaDehn** [comment]
verified 30.06.2016
