### ISSUE TITLE
Network image cannot be uploaded when using Microsoft edge

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#125]
[version]
V16.0.5

[Client]
Microsoft Edge 25.10586.0.0
Microsoft EdgeHtml 13.10586

[Frequency]
Always

[How to reproduce]
1. Login windows 10 client using RDP (Select local driver to be able to access from RDP)
2. Login as technical provider or supplier using Microsoft Edge
3. Go to Account > Edit profile
4. Click Upload image and select image in network drive which was selected 1st step(e.g. \\tsclient\D\tmp\testimg.png)

[Expected result]
The image is shown in Profile image and can be uploaded

[Observed result]
The image is not shown in Profile image and cannot be uploaded

[Note]
I think the cause of this issue is Microsoft Edge bugs.(<https://connect.microsoft.com/IE/feedback/details/1897265/edge-file-
upload-fails-when-a-network-file-is-selected>)
This issue also occurred in "Import service definition", "Define service" and "Update service".(Maybe all of upload function cannot be used with driver mapped by Remote Desktop.)
Please check whether are there workaround or not.

**Comment by GoebelL** [comment]
Please check.

**Comment by badziakp** [comment]
I installed image on my virtualbox with Windows 10 and Microsoft Edge in version from the description and all uploads work correct. I am not able to reproduce this issue.

**Comment by GoebelL** [comment]
Same result. Installed Microsoft Edge 20.10240.16384.0.

No problems detected.
