### ISSUE TITLE
The status of subscriptions were wrong when select Modify subscription as process trigger

### ISSUE THREAD

**Issue by wangyingfnst** [servicecatalog/development#126]
Date: 2016/06/02
[Test category]: creative Test
Severity：Major

[Steps to reproduce]
1. Login in marketplace as customer;
2. Click on "ACCOUNT->Processes->Add Process Trigger";
3. Fill the following fields "Display as", Type="Modify subscription" Target type="Web Service", Target URL="http://mockproductServer:port/oscm-integrationtests-mockproduct/NotificationService?wsdl",
check the "Suspends the execution of the process", then click on "Save" button;
4. Click on "HOME->Show Details->Get it now" to make a subscription, and assign customer to this subscription;
5. Click on "ACCOUNT->Subscriptions" to see the status of the subscription created in step 4;
6. Select the subscription created in step 4, click on "Configuration", modify the subscription name, then click on "Save" button;
7. Click on "ACCOUNT->Subscriptions" to see the status of the subscription created in step 4;
8. Click on "MY SUBSCRIPTIONS", select the subscription created in step 4, then click on "Use service" button.

[Expected result]
In step 5, the status should be "ready";
In step 6, some message "This action is subject to process control by your organization. Before it is finally executed, it must be approved in this process control system. Please wait for this approval." should be displayed;
In step 7, the status should be "suspended";
In step 8, the status should be "suspended", and no "Use service" button should be displayed.

[Observed result]
In step 5, the status was "ready";
In step 6, some message was displayed;
But in step 7, the status was "ready";
And in step 8, the subscription can be used successfully.

![the status of subscriptions were wrong when select modify subscription as process trigger](https://cloud.githubusercontent.com/assets/14818896/15995991/38028ce8-3155-11e6-8261-ba1f16ec18b3.png)

**Comment by GoebelL** [comment]
Please check.

**Comment by badziakp** [comment]
Hi,
I think that the described behavior is correct. The checkbox "Suspends the execution of the proces" means, in this case, that modification process should be suspended not a subscription. Changes are waiting for approval but user still can use subscription without that changes.

**Comment by mdehn** [comment]
The behavior described in [Observed result] is correct by design. Don't change this behavior.
