### ISSUE TITLE
The search results were not the same when enter a space into search box of "services" and "subscriptions"

### ISSUE THREAD

**Issue by wangyingfnst** [servicecatalog/development#127]
Date: 2016/06/02
[Test category]: creative Test
Severity：Minor

[Steps to reproduce]
1. Login in marketplace as customer;
2. Click on "ACCOUNT->Subscriptions";
3. Enter a space into the "Search subscriptions", then click on search button;
4. Enter a space into the "Search services", then click on search button.

[Expected result]
In step 3, no subscription should be list;
In step 4, no services should be list.

[Observed result]
In step 3, no subscription was list;
In step 4, no service was list, but the message "Please specify a search term" was displayed in the screen.

**Comment by GoebelL** [comment]
The search must behave uniquely. But in any case no error message should be displayed.

If no or a blank search term is given, I suggest for 
- services, to return the "browse all services" list, by forwarding to this page "Home > All services".
- subscriptions, to display all available subscriptions (same as now, when searching with empty string as search term)

@mdehn, do you agree?

[2016-05-19 10:19:30] Reply from @mdehn:
fine for me.

**Comment by jiangweiyi** [comment]
Verified by FNST
[verified-version] V16.0 fix6
[verified-details]Search blank in service and subscription pages will return all of the results. so verified.
