### ISSUE TITLE
The blank space key was regard as character only sometimes

### ISSUE THREAD

**Issue by wangyingfnst** [servicecatalog/development#129]
Date: 2016/06/02
[Test category]: creative Test
Severity：Minor

[Steps to reproduce]
1. Login in marketplace as customer;
2. Select a service which has been subscribed at least one times;
3. Click on "Write a review" button;
4. Rate the service, input the title, then input some content plus some space, such as "good                    ";
5. Click on "Save" button, then click on "Manage reviews".

[Expected result]
In step 4, the message "You have entered ... characters; the maximum is 2000." should be displayed;
In step 5, the message displayed should be the same as step 4.

[Observed result]
In step 4, the message "You have entered 60  characters; the maximum is 2000." was displayed, that meas space was think as characters.
But in step 5, the message "You have entered 4 characters; the maximum is 2000." was displayed, that means space was not think as characters.

**Comment by GoebelL** [comment]
The report is not clear. Anyway, I don't see a problem here. The message on step 4 is just a feedback to the user how many characters may be entered maximum. It might be, that the message is trimmed. If it's just about leading or trailing white space I don't consider this issue for fixing.
