### ISSUE TITLE
default sorting for "manage access" for marketplace not like other pages

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/development#131]
Date: 2016/06/16
 [Test category]: creative Test

[Steps to reproduce]
 1. login as marketplace owner
 2. goto marketplace-> manage access and define a closed marketplace.
 2. click some Organisation for access.
 3. click save
 4. leave page and go back
[Expected result]
 Default sorting of custumer with assecc are first.
see cb:Sortable list with paging with check box (with tooltip)#7319
 [Observed result]
default sorting is not clear

**Comment by kowalczyka** [comment]
Default sorting has been added to the table.

[Resolving commit]
660b7412d80a73d2a768212ed8ef500adb59b794
