### ISSUE TITLE
Service marked as not in catalog is visible as edition

### ISSUE THREAD

**Issue by skulle** [servicecatalog/development#132]
Hi,

I have one marketable service (Edition Test) which is active but not 'In catalog'. You cannot see the service on my marketplace but when you click on another service it can be seen on the left side in the 'Availabe editions' box. You can even click on it. Is that correct behavior?

Best regards,
Sven

![snip1](https://cloud.githubusercontent.com/assets/15829792/16114889/02cf90cc-33c4-11e6-8fb8-6b891fd3cbd1.png)
![snip2](https://cloud.githubusercontent.com/assets/15829792/16114891/02d0a44e-33c4-11e6-95ce-60a640088000.png)
![snip3](https://cloud.githubusercontent.com/assets/15829792/16114890/02d022a8-33c4-11e6-9f5d-0c1b456dd9fd.png)
![snip4](https://cloud.githubusercontent.com/assets/15829792/16114892/02f4847c-33c4-11e6-91c0-e2369d86761b.png)

**Comment by GoebelL** [comment]
From online help:
"Decide whether an activated service is to be displayed in the service catalog on the marketplace.

If you activate multiple marketable services which are based on the same technical service, you can decide to display only a subset of them in the service catalog. At least one service of such a set of services must be displayed in the catalog. **A service that is not displayed is offered to customers as soon as they request details of a related service. Requesting details displays all editions of a service, i.e. a complete list of the marketable services that are based on the same technical service.**"

**Comment by GoebelL** [comment]
This flag controls the visibility in the catalog list. Related editions of a particular service are always available on the details page of this service (your first two screen shots).

**Comment by skulle** [comment]
Thx for the quick response.
