### ISSUE TITLE
"...document\Development\... does not exist." while running packageDeploy

### ISSUE THREAD

**Issue by angarg12** [servicecatalog/development#135]
Following the set up instructions, when I run the script /oscm-devruntime/javares/devscripts/build-dev-PackageDeploy.xml I get the following error message:

`C:\Users\garcia\Documents\GitHub\development\oscm-build\build.xml:146: C:\Users\garcia\Documents\GitHub\**document**\Development\oscm-app-aws\doc does not exist.`

I made sure that I cloned the docs repo in my local also. Then I noticed that the path for the repo is:

`...\GitHub\**documentation**\Development`

Its a minor thing but I think that names should be in sync so that it isn't necessary to rename your local repo to make the code work.

**Comment by GoebelL** [comment]
Thank you for your note. The same issue is already handled in #84 .
