### ISSUE TITLE
Expected displaying of custom attributes in subscription UI

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#136]
This question comes from @wangyingfnst 

Could you tell us the expected result for displaying custom attributes in subscription UI? 

For example:

1. Create supplier, customer, marketable service and "Define custom attributes for customers" with     default value "customer" and name super_attribute
2. Log in as customer and subscribe with filling value "cus_change" for super_attribute to subscribe      this service.
3. When the customer subscribe this service again, what should be display for the super_attribute in the UI?
4. When the supplier change the default value to be "cus_def", what should be display during the customer subscription?

**Comment by mdehn** [comment]
For customer-specific attributes, which are customer options (seen and editable by the customer) the default value provided by the supplier is displayed only as long as the customer has not set any value. This is the case 
- when subscribing any service of the respective supplier for the first time or
- when the supplier adds a custom attribute and the customer creates or changes a subscription for the first time after the custom attribute has been added.
As soon as the customer has set a value for the customer-specific attribute 
- by subscribing to a service of the respective supplier or 
- by updating the subscription of a service provided by the supplier
the value set by the customer is displayed.

Having said this the values displayed for super_attribute are 
(3) "cus_change""
(4) still "cus_change"

**Comment by jiangweiyi** [comment]
Thanks.
I still have another question, what is the same situation with "Define custom attributes for subscriptions"?

1. Create supplier, customer, marketable service and "Define custom attributes for subscriptions" with default value "default_s" and name super_attribute
2. Log in as customer and subscribe with filling value "s_change" for super_attribute to subscribe this service.
3. When the customer subscribe this service again, what should be display for the super_attribute in the UI?
4. When the supplier change the default value to be "default_s_change", what should be display during the customer subscription?

**Comment by mdehn** [comment]
While the scope of a customer-specific attribute is the customer, a subscription-specific attribute set by the customer is in the scope of the subscription. Therefore when crating a new subscription always display the default value set by the supplier. 
Having said this the values displayed for super_attribute are 
(3) "default_s"
(4) "default_s_change" for new subscriptions
This is the current behavior, which should not be changed.
