### ISSUE TITLE
REST API v1 Authentication in SAML_SP mode

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#137]
Found by FBT:
The OSCM can run in INTERNAL and SAML_SP authentication mode. The REST API v1 supports only basich authentication over https.
The REST API authentication does not work if OSCM runs in SAML_SP mode.

**Comment by StavrevaS** [comment]
For 16.1 only basic authentication for REST API is supported, even if OSCM runs in SAML_SP mode.
Authentication with tokens is planned for the next release.

**Comment by MiethanerR** [comment]
Fixed basic authentication for REST API so it now works in both modes.
