### ISSUE TITLE
manage access marketplace: Dialog for remove access is wrong

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/development#141]
Date: 2016/06/23
[Test category]: creative Test

[Steps to reproduce]
1.login as marketplace owner
2.goto marketplace-> manage access and select a closed marketplace.
3.remove granted access for a Organization which has subscription on this marketplace.
4.click save
5. warning will be shown
6. click "no"
[Expected result]
all changes will be canceled
[Observed result]
go back, but changes will not be canceled

**Comment by GoebelL** [comment]
I feel not to agree with the [expected result]. I think [observed result] is correct. 
When answering confirmation questions with "no" it mean that the attempted action will not be performed. Save will not persist the changes. It doesn't mean to rewind the local changes made in the form. 
It would be inconvenient: For example you select 20 organizations to remove the access, but when clicking save you remember that one you didn't want to remove. Therefore you answer with "no". If all selections would be reverted you have again to choose the 19 other. 

Secondly, again our general rule applies: The behavior must be unique and consistent. There are similar cases in the admin portal which all behave as [Observed result]. 
Example: 
1. Given supplier S published a marketable service on base of a technical service T from a 
    technology provider TP
2. As technology manager of TP go to account -> manage supplier
3. Chose technical service T => Organization S appears
4. Check checkbox for S and press "delete" button
5. Answer confirm question with "no" 
=> Nothing gets deleted but also nothing is changed nor reverted 
=> Organization checkbox remains checked

[Expected result]
go back, but changes will not be canceled
