### ISSUE TITLE
Subscription search on organization custom attributes from different vendors now working

### ISSUE THREAD

**Issue by wangyingfnst** [servicecatalog/development#142]
This is the doubt about the reported bug of our fnst when do the verification.
--->Could you tell us the custom attributes were for customers or for subscriptions?

[Description]
Subscription search lists to many results in following scenario
- customer having two suppliers s1, s2
- suppler s1 defining customer uda u1 as customer option
- suppler s2 have no customer udas
- customer c1 subscribing services from s1 and s2, specifying value "test" for u1
=> searching "test" brings both subscriptions

**Comment by GoebelL** [comment]
Customer UDAs are not searchable by definition.
