### ISSUE TITLE
Search for subscription does not support all character defined for subscription name

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#145]
Version: 16.0 fix3
Date: 2016/04/28

[Description]
 
search for subscription does not support all character which will be valid for subscription name

[Steps to reproduce]
subscription name: A service with string par(2) 
search term: par(2)

[Expected result]
subscription found: A service with string par(2)

[Observed result]
nothing will be found

**Comment by badziakp** [comment]
[Details of fix]
Subscription search works with special characters in given phrase.

**Comment by SylviaDehn** [comment]
verified 2016/07/20 checked for subscription name, subscription attributes, string parameters
