### ISSUE TITLE
Trigger target type overridden via REST API

### ISSUE THREAD

**Issue by Weiser-R** [servicecatalog/development#148]
Via REST API created triggers are always of target type REST (basically ok so far). But one can still create triggers of target type SOAP in UI. When updating this trigger via REST API, it will be changed to target type REST.

So either one can also define the target type via REST API or the target type must not be changed on update.

**Comment by MiethanerR** [comment]
@Weiser-R I added the field to the representation (also in docu). It can now be set and changed freely and is shown on get.
