### ISSUE TITLE
 Billing data xml is opened in same window when using Microsoft Edge

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#149]
[version]
V16.0.5+

[Client]
Microsoft Edge 25.10586.0.0
Microsoft EdgeHtml 13.10586

[Frequency]
Always

[How to reproduce]
1. Login as supplier using Microsoft Edge
3. Go to Export billing data
4. Select "Customer billing data", organization and date
5. Click Export

[Expected result]
XML is opened in separate window or popup download dialog

[Observed result]
XML is opened in same window

**Comment by GoebelL** [comment]
[details of cause]
The corrected content disposition header has to be provided with the HTTP Response in order to enforce the file download in the browser. There was a spelling error in the response header parameter value, which led to this issue on MS Edge. Somehow, older browser versions are more fault tolerant, ignoring this typo.
[details of fix]
Fixed the header for file download in 16.0.6.

**Comment by SylviaDehn** [comment]
@GoebelL : I'm not sure this is intended behavior. The xml can be saved, and then it is opened with IE 11.
This seems a bit strange.

**Comment by SylviaDehn** [comment]
OK, now I can open in another tab (setting was incorrect.
[Build] 2016/08/17 verified
