### ISSUE TITLE
VMware-Adapter does not have Fujitsu Branding

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#150]
[Version]
V16.0 Fix 6
[Date]
2016/06/26

[Test category] 
Creative

[Description]
The branding of the VMware Controller interface does not match the Branding of the rest of the adapters like AWS controller

Severity major, because the VMware controller cannot be delivered unless the branding matches.

[Steps to reproduce]
Start VMware controller (https://machine:28881/oscm-app-vmware/)
Start AWS Controller (https://machine:28881/oscm-app-aws/)
compare both screens
[Expected result]
The branding is identical
[Observed result] 
Different look and feel
[Details]
See above; 

[Messages and logs]
attached a screenshot from vmware adapter and aws controller for comparison reasons

**Comment by AndreasTWolf** [comment]
AWS controller pic

![awscontroller](https://cloud.githubusercontent.com/assets/19411047/16414716/94e88ac6-3d39-11e6-92a8-56551417ffeb.PNG)

vmware controller pic
![vmwarecontroller](https://cloud.githubusercontent.com/assets/19411047/16414725/a7e0f79e-3d39-11e6-83a3-a35175932ce4.PNG)

**Comment by SylviaDehn** [comment]
Branding verified 2016/07/22
