### ISSUE TITLE
vmware controller: vSphere user password in clear text

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#152]
[Version]
V16.0 Fix 6
[Date]
2016/06/26

[Test category] 
Creative

[Description]
start vmware controller, look at the vSphere API Settings; Password is written in clear text
[Steps to reproduce]
see above
[Expected result]
Passwords are scrambled 
[Observed result] 
password in clear text
[Details]
See above; 

[Messages and logs]
attached a screen shot

**Comment by AndreasTWolf** [comment]
Btw. the password is also in clear text tine the vmware database: table vcenter column password. Needs to be encrypted here as well

**Comment by kowalczyka** [comment]
This was fixed only in UI (password is scrambled). Password encryption was decided to be resolved with separate feature.

**Comment by SylviaDehn** [comment]
verified scrambled password 2016/07/22 on
http://estsdehn.intern.est.fujitsu.com:8880/oscm-app-vmware/vcenter.jsf
