### ISSUE TITLE
REST API: error messages

### ISSUE THREAD

**Issue by Weiser-R** [servicecatalog/development#153]
Some error messages don't provide an exception id.

A very generic error is returned when using a wrong data type (Invalid JSON format).

Some error messages contain class names like VOTriggerDefinition.

**Comment by MiethanerR** [comment]
@Weiser-R I added additional info for wrong data types, should be more clear now. Since the error messages with class and field names come from the underlying service, I can't do much about that in this version. The exception ids will also be added in the next version.
