### ISSUE TITLE
REST API: optional input

### ISSUE THREAD

**Issue by Weiser-R** [servicecatalog/development#155]
Certain fields of input objects need to be optional as they are returned on GET but not neded on POST or PUT. This should be visible in the API description.

A very special case is PUT on processes/{id}/approve - there one only needs the id (present in the path) but has to provide an empty JSON object ({}), otherwise a 500 is the result.

**Comment by MiethanerR** [comment]
@Weiser-R I adjusted the documentation with comments and required fields. I also removed the json input from the approve resource.
