### ISSUE TITLE
Marketplace/Manage access: organization name are NOK

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#158]
Date:2016/06/29

[Steps to reproduce]
1. As marketplace owner, choose "Marketplace/Manage access", define "Authorized customers only"
2. look at organization names

[Expected result]
organization names are correct

[Observed result]
organization names have "- nnnnn" added to the end (tkey?)

![organizationname](https://cloud.githubusercontent.com/assets/15086024/16445862/046e5eb0-3de5-11e6-98a7-a093d246ae7a.jpg)

**Comment by GoebelL** [comment]
This is not desired and therefore a valid bug which has to be fixed. But it's not major. Please keep to the agreed severity classifications.

**Comment by badziakp** [comment]
The presented organization name is corrected.

**Comment by SylviaDehn** [comment]
30.06.2016 verified
