### ISSUE TITLE
Incorrect login results in wrong error message for marketplace with authorized customers

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#159]
Date:2016/06/29

[Steps to reproduce]
1. As marketplace owner, choose "Marketplace/Manage access", define "Authorized customers only"
2. Go to marketplace and try to login with invalid id. 

[Expected result]
Message: "Login failed. Check whether the specified user ID or password are correct."

[Observed result]
Message: "The organization does not exist"

[Details]
This is a security issue. One should never show that a user or organization does not exist. An attacker should not be able to confirm whether the username is valid.

**Comment by badziakp** [comment]
issue is fixed. Correct message is shown when user enters invalid credentials in login form.

**Comment by SylviaDehn** [comment]
2016/06/30 master branch verified
