### ISSUE TITLE
Marketplace/Manage access check all button has no effect

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#160]
Date:2016/06/29

[Steps to reproduce]
1. As marketplace owner, choose "Marketplace/Manage access", define "Authorized customers only"
2. Press "choose all" button at top (see screenshot)

[Expected result]
all organizations on page are chosen

[Observed result]
pressing check all has no effect

[Details]
see screenshot
![checkall](https://cloud.githubusercontent.com/assets/15086024/16450790/62f2ec16-3dff-11e6-93aa-873454836c0f.jpg)

**Comment by kowalczyka** [comment]
The solution has already been merged to master branch - BES_MASTER_Unit (1534)

**Comment by SylviaDehn** [comment]
30.06.2016 verified in master
