### ISSUE TITLE
The patameter in csv files of VMware adapter

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#161]
When I setup VMware adapter, I could not understand what parameter have to input in these columns:
* vcenter.csv
  * TKey
* datacenter.csv
  * DatacenterId
* ippool.csv
  * IPAddress

About the "TKey" and "DatacenterId", how can I get these parameter? If you have any documentation or detail information, 
please share the information. 
About the "IPAddress", what format can I use to this parameter? Can I input range information?( ex. "192.168.30.100#100")

**Comment by StavrevaS** [comment]
The TKey parameter is a unique identifier of the vcenter in the controller database. It has nothing to do with the target vSphere system.

Datacenterid is the name or identifier of the Datacenter created for a vcenter. Please see the hierarchy in the VMWareIntegration.pdf in Appendix A. Or if you use vSphere client, this is the name you see for the Datacenter (2nd level in hierarchy).

As the documentation describes, the ippool table contains a pool of IP addresses available in the corresponding network in the Datacenter. Each IP address is a separate row in the controller database, no ranges should be specified.

**Comment by misako0927** [comment]
datacenter.csv also have "Datacenter" column. I could not understand what difference are there between "Datacenter" and "DatacenterId". "DatacenterId".

**Comment by StavrevaS** [comment]
Datacenter table:
Datacenter in csv (name column) - the name of the data center in the target vSphere system.
Datacenterid in csv (identifier column) - the controller specific id for the datacenter, has nothing to do with the target system. It is used for automatic generation of instance names, placeholder ${DC} - see Appendix B.
Sorry, I mixed up datacenter and datacenterid in the previous comment.

**Comment by misako0927** [comment]
I understand DatacenterId is used only in controller and user can input any unique character to this param.

**Comment by misako0927** [comment]
Excuse me, could you write these information in documentation? Otherwise user cannot understand what kind of parameter should be written in CSV file.

**Comment by misako0927** [comment]
I'm sorry I didn't see newest documentation. In newest documentation there are these information.
I can close this issue.
