### ISSUE TITLE
vmware controller: The command for importing the .csv files return incorrect errorlevel

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#162]
[Frequency]
Always

[How to reproduce]
1. Input incorrect parameter in csv file
  ex. vcenter.csv
    TKey,Name,Identifier,URL,UserId,Password,
    test,test1,test2,test3,test4,test5
2. Execute this command:
  <ANT_HOME>\bin\ant -f build-db-import.xml importVCenter -Ddb.dir=controller_db

[Expected result]
Importing is failed and %errorlevel% return not 0

[Observed result]
Importing was successful and %errorlevel% retun 0
> #%ANT_HOME%\bin\ant -f build-db-import.xml importVCenter -Ddb.dir=controller_db
> Unable to locate tools.jar. Expected to find it in C:\Java\lib\tools.jar
> Buildfile: C:\vmwareadapter\install\build-db-import.xml
> 
> importVCenter:
>      [java] VCenterImport execute failed to add row:  test test2 test1
>      [java] VCenterImport execute For input string: "test"
> 
> BUILD SUCCESSFUL
> Total time: 0 seconds

"importAll", "importCluster", "importVLAN", "importDomain" and "importIPPool" also same return when importing is failed.

**Comment by DawidCh** [comment]
Hello Misako.
There is one issue in your environment. If you see following text "Unable to locate tools.jar. Expected to find it in C:\Java\lib\tools.jar" it means that java system which you have in your PATH is set to java jre rather than java sdk (which is preffered). You have to modify your PATH variable and set it to java sdk home (here is tutorial: http://www.computerhope.com/issues/ch000549.htm).
Regards, Dawid.

Deatails of fix
Code have been modified to rethrow exceptions outside the main method (to ant) if the failure happened.

**Comment by misako0927** [comment]
Hello Dawid.
Thank you for your comment. I added JAVA_HOME and I could run this command.

**Comment by misako0927** [comment]
Hello. I tried to setup again with GA1 but still same issue occurred.

[Version]
v16.0 GA1
BES_MASTER_DELIVERY-744-20160722124302

[Frequency]
Always

[How to reproduce]
1. Input incorrect parameter in csv file
ex. vcenter.csv
TKey,Name,Identifier,URL,UserId,Password,
testCTMG,BX922S2-02-B05,vCenter1,https://BX922S2-02-B05/sdk,administrator@vsphere.local,hogehoge
2. Execute this command:
\bin\ant -f build-db-import.xml importAll -Ddb.dir=controller_db

[Expected result]
Importing is failed and %errorlevel% return not 0

[Observed result]
Importing was successful and %errorlevel% retun 0

[log of this command]
```
importVCenter:
     [java] VCenterImport execute failed to add row:  testCTMG vCenter1 BX922S2-02-B05
     [java] VCenterImport execute For input string: "testCTMG"

importDatacenter:
     [java] DatacenterImport execute Failed to add row: BX922S2-02-B05 CTMG-Datacenter datacenter1
     [java] DatacenterImport execute Failed to retrieve vcenter BX922S2-02-B05

importCluster:
     [java] ClusterImport execute failed to add row:  BX922S2-02-B05 CTMG-Datacenter CTMG-Cluster
     [java] ClusterImport execute Failed to retrieve datacenter CTMG-Datacenter

importVLAN:
     [java] VLANImport execute failed to add row: BX922S2-02-B05 CTMG-Datacenter CTMG-Cluster vlan1 10.125.67.220 ctmg.local
     [java] VLANImport execute Failed to retrieve tkey for cluster CTMG-Cluster datacenter: CTMG-Datacenter vcenter: BX922S2-02-B05

importIPPool:
     [java] IPPoolImport execute Failed to add row: BX922S2-02-B05 CTMG-Datacenter CTMG-Cluster vlan1 192.168.10.2
     [java] IPPoolImport execute Failed to retrieve tkey for VLAN vlan1 datacenter: CTMG-Datacenter vcenter: BX922S2-02-B05 cluster: CTMG-Cluster

importAll:

BUILD SUCCESSFUL
Total time: 1 second
```

**Comment by kowalczyka** [comment]
The issue has been resolved and merged into master branch.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/01
verified
