### ISSUE TITLE
vmware controller: Cannot update vSphere configuration with CSV file.

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#167]
[Frequency]
Always

[How to reproduce]

1. Input parameter in vcenter.csv with TKey = 123

  ```
  ex. vcenter.csv
    TKey,Name,Identifier,URL,UserId,Password,
    123,test1,test2,http://test3.com,test4,test5
  ```
2. Execute this command:

  ```
  \bin\ant -f build-db-import.xml importVCenter -Ddb.dir=controller_db
  ```
3. Change the parameter of Name in same TKey

  ```
     ex. vcenter.csv
       TKey,Name,Identifier,URL,UserId,Password,
       123,foo,bar,http://foofoo.com,test4,test5
  ```
4. Execute this command:

  ```
  \bin\ant -f build-db-import.xml importVCenter -Ddb.dir=controller_db
  ```

[Expected result]
Overwrite the column of TKey 123.

[Observed result]
Import was failed because the key 123 already exists.

```
# %ANT_HOME%\bin\ant -f build-db-import.xml importVCenter -Ddb.dir=controller_db -Ddb.admin.user=pgctbss
Unable to locate tools.jar. Expected to find it in C:\Java\lib\tools.jar
Buildfile: C:\Fujitsu\FSCTMG\app\setupvmware\install\build-db-import.xml

importVCenter:
     [java] VCenterImport execute failed to add row:  123 vcenter1 test1
     [java] VCenterImport execute ERROR: duplicate key value violates unique con straint "vcenter_pkey"
     [java]  Detail l: Key (tkey)=(123) already exists.

BUILD SUCCESSFUL
Total time: 0 seconds
```

I think build-db-import.xml can only use for adding row.
We need provide the way to change the row and delete the row.

**Comment by StavrevaS** [comment]
The build-db-import.xml provides a basic functionality for importing the vSphere data needed for controller. The provided ant targets are meant to help integrating the VMWare installer in another installation software. 
As it is already documentedin VMWareIntegration.pdf, these settings usually do not change once imported. If such case exists, than the SQL commands can be used.

**Comment by misako0927** [comment]
Are there any reason vSphere settings should not change after importing?

At least deleting operation should be prepared. User often will want to change these settings especially VLAN and IP Pool. And sometimes user make typo in the settings.
SQL are difficult so we need to prepare another way.(Ex. ant or GUI)

**Comment by misako0927** [comment]
Could you let me know how to use update vCenter entry function?

**Comment by kowalczyka** [comment]
Just update the csv with some new values (the entry will be updated using tkey)  and invoke the same import command again. As it is described in [How to reproduce]

For now it is working for VCenter objects.

**Comment by misako0927** [comment]
Thank you.
I think all objects need these function. Could you prepare these options too?
* importAll
* importCluster
* importVLAN
* importDomain
* importIPPool

**Comment by misako0927** [comment]
@kowalczyka 
Excuse me, your commit looks like you added update function only to vCenter. Can I use update function to another table?

**Comment by kowalczyka** [comment]
Yes, for now only vCenter can be updated as the csv file includes its tkey which can identify the row which should be updated. Other tables consist of some data and references to other tables so the update strategy is not clear.

Therefore we provided additional target do delete the content of all tables. For this the following command can be used:

\bin\ant -f build-db-import.xml deleteAll -Ddb.dir=controller_db

**Comment by SylviaDehn** [comment]
not ok with GA1 2016/07/22
1. emptied tables with \bin\ant -f build-db-import.xml deleteAll -Ddb.dir=controller_db
2. tried to import as usual, errors occurred, see below:
![updatevmware](https://cloud.githubusercontent.com/assets/15086024/17095955/5dd896ec-5257-11e6-8423-d449181bc5ca.jpg)

**Comment by SylviaDehn** [comment]
A workaround for this is:
1. stop your bes and app domains
2. delete your vmware db, 
3. ant -f build-db.xml CREATE.dbAndUser -Ddb.dir=controller_db
4. ant -f build-db.xml UPDATE.dbSchema -Ddb.dir=controller_db
5. ant -f build-db-import.xml importAll

**Comment by kowalczyka** [comment]
@SylviaDehn could you please verify it on BES_GitHub_BUGFIX_Unit (128)? I have commited the final changes.

**Comment by kowalczyka** [comment]
The solution can be verified on master branch now.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/01
verified
The following sequence will update the settings:
 ant -f build-db-import.xml deleteAll -Ddb.dir=controller_db
 ant -f build-db-import.xml importAll -Ddb.dir=controller_db
