### ISSUE TITLE
vmware controller: db.properties of controller_db isn't used to set up glassfish for VMware adapter

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#169]
[Frequency]
Always

[How to reproduce]

1. Change db.port in db.properties for controller_db to 5443
2. Setting up DB
3. Setting up the Application Server Resources with this command:

  ```
  <ANT_HOME>/bin/ant -f build-glassfish.xml SETUP
  ```

[Expected result]
Property of PortNumber for BSSAppVMwarePool is set to 5443

[Observed result]
Property of PortNumber for BSSAppVMwarePool is set to 5432

This issue occurred since properties in "resource-extention.xml" are fixed value.

**Comment by StavrevaS** [comment]
The installation is adapted to take the db.properties from controller_db in the installation package.
The file resources-extension.xml will be generated during the installation process, based on resources-extension-template.xml. The template has placeholders for the database settings, which are replaced with the values from the db.properties of controller_db. After the installation, the generated file resources-extension.xml is deleted, but the template not. It is used for repeated installation if necessary. The documentation will be changed accordingly.

The changes are contained in the following [commit](https://github.com/servicecatalog/development/commit/9f5afafc781bcdb969600f96f0505c48bb43a2d9)

**Comment by StavrevaS** [comment]
Reopen for verification

**Comment by SylviaDehn** [comment]
verified for new installation; update installation does not remove file 2016/07/22
