### ISSUE TITLE
Login dialog box does not appear at marketplace with option "Authorized customers only"

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#171]
Date: 2016/07/04

[Steps to reproduce]
prerequisite: lots of organizations are defined.
1. As marketplace owner "SuppTechAdmin7", choose "Marketplace/Manage access", define "Authorized customers only" for marketplace "HelloKitty"
2. Click save
3. Enter url for Hello Kitty marketplace in "Incognito Window" in Chrome (to make sure cookies etc
are gone):
estsdehn.intern.est.fujitsu.com:8180/oscm-portal/marketplace/index.jsf?mId=8da97137

[Expected result]
Login appears

[Observed result]
Endless loop of redirect

[Details]
This problem only occurs with this database and exactly this marketplace. Please ask me for the dump
since it is too big to attach here.

**Comment by badziakp** [comment]
[Datails of fix]
Login to the restricted marketplace without public landing page was fixed.

**Comment by SylviaDehn** [comment]
verified 2016/07/13 (16.0 fix6+)
