### ISSUE TITLE
AWS is switching to longer resource ids in December 2016 

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#172]
2016/07/01 
16.0 fix6
Amazon states:
Resource ID length management
Use this page to manage your opt-in status for longer resource IDs. To opt in to receiving longer IDs, check the applicable box(es) below. The longer ID format will only apply to newly launched resources. To opt out of receiving longer IDs, uncheck the applicable box(es) below.
We are introducing longer identifiers for several resource types. The old resource ID format is a resource identifier ("i-", "vol-", etc.) followed by 8 characters, and the new format will be the same resource identifier followed by 17 characters.

Is this a problem for us? Or will everything work without making changes necessary?
Currently our instance ids look as follows: e.g. i-a370d808

**Comment by StavrevaS** [comment]
We are working with instance ids as strings. The maximum length is 255, set in the database.
So this change should not affect the AWS Controller.
