### ISSUE TITLE
vmware controller: instance IP address not displayed

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#173]
[Version]
V16.0 Fix 6
[Date]
2016/06/26

[Test category] 
Creative

[Description]
Access Info set to default in Tech service: 
 ParameterDefinition id="ACCESS_INFO" configurable="true" default="${HOST}, ${IP}" mandatory="false" valueType="STRING"

Create VMware instance,
log on to CTMG look at Subscription screen:
Host name is displayed, IP address isn't

Same is true for the notification email:
Dear Ms. Julia,
You have been granted access to the subscription VMware_Original_With_ALL(3). 
Freddy-000028, 
With best regards. 

[Steps to reproduce]
Create Vware instance with default from delivered TechService
[Expected result]
Hostname, IP-Address displayed in Email and Subscription screen
[Observed result] 
Only host address is displayed.
[Details]
See above; 

[Messages and logs]

**Comment by StavrevaS** [comment]
Fixed with [commit](https://github.com/servicecatalog/development/commit/123d8e34d2589384d6a652a373c029f99c0ccfd0).

**Comment by elfriedegoetz** [comment]
Master 2016/07/22
now it is ok
Dear user,
You have been granted access to the subscription VMware_4_Nics_Preset. 
Elfriede3, VM Network: [10.140.18.119, fe80::250:56ff:fe9d:1d30]
With best regards. 
This email has been automatically generated. Please do not reply to this email.
