### ISSUE TITLE
The operator client running failed and throw ClassNotFoundException due to the the necessary jar was not added in the classpath

### ISSUE THREAD

**Issue by wangyingfnst** [servicecatalog/development#175]
Date: 2016/07/01

[Steps to reproduce]
1. Enter the folder of "operatorclient";
2. Open a command line, input "ant -f build.xml";
3. Include the "oscm-rest-api-interfaces.jar" into the lib of "operatorclient";
4. Open the command line and "ant -f build.xml" again.

[Expected result]
In step 4, the operator client can be build successfully.

[Observed result]
In step 4, the operator client build failed and the " ClassNotFoundException" was thrown.

[Details]
The new added “oscm-rest-api-interfaces.jar” was not added in the class-path of the oscm-operatorsvc-client, please see the attachment.
![the operator client running failed and throw classnotfoundexception](https://cloud.githubusercontent.com/assets/14818896/16582800/ea00a7fa-42e3-11e6-95e6-e5d2547fbd6a.png)
![the oscm rest api interfaces jar was not added in the classpath of operator client](https://cloud.githubusercontent.com/assets/14818896/16582809/fe260a04-42e3-11e6-9cc9-562db9a3a4ce.png)

**Comment by MiethanerR** [comment]
I refactored the api and removed the dependency, shouldn't be a problem anymore.

**Comment by SylviaDehn** [comment]
does that mean it has been changed in master?

**Comment by MiethanerR** [comment]
yes, i just merged my changes

**Comment by jiangweiyi** [comment]
verified by FNST
[verified-build]20160715094705
[verified-details]Copy all the related jar to operatorclient, then execute the "ant -f build.xml" command, it is OK, so verified.
