### ISSUE TITLE
vmware-controller: On the controller interface parameters not grayed out if invalid

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#178]
[Version]
V16.0 Fix 6
[Date]
2016/06/26

[Test category] 
Creative

[Description]
On the vmware controller interface the values for "Host Balancing Settings" are not grayed out when they are not used. 
[Steps to reproduce]
Install VMWare Controller, open it.
Only when the value of the Balancer is set to "Distribute VMs equally over all hosts (static configuration)" the subsquent values are valid and will be evaluated. If the other two parameters are selected the values should be grayed put ot invisible. 

[Expected result]
Vales are not writable (or grayed out)
[Observed result] 
All vales are writable (or not grayed out) 
[Details]
See above; 

[Messages and logs]

**Comment by StavrevaS** [comment]
The UI behavior should be as following:
- Balancer option: "Distribute VMs equally over all hosts (dinamically)" - other settings (under balancer) shoud be disabled;
- Balancer option: "Distribute VMs equally over all hosts (static configuration)" - only the 3 weight settings should be enabled;
- Balancer option: "Distribute VMs in the order of configured hosts" - the 3 weight settings should be disabled, other enabled.

**Comment by badziakp** [comment]
[Details of fix]
Information about cluster, datacenter and balancing settings was deleted from vcenter.jsf page.

**Comment by SylviaDehn** [comment]
Cluster info is not deleted see other issue 244. 
Other info has been removed
2016/07/22
