### ISSUE TITLE
vmware controller: using default Tech-Service: passwords (linux-Widows) in clear text...

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#179]
[Version]
V16.0 Fix 6
[Date]
2016/06/26

[Test category] 
Creative

[Description]
using the default tech service the passwords are visible in clear text once the subscription gets displayed in the Configuration tab in the subscription area
[Steps to reproduce]
Create with the default tech service an instance, set the linux password and the windows password, Subscribe,
Change to Account subscritions choose the just created one, modify (administrate) 
Select Configuration, look up the password parameters
[Expected result]
Password are displayed scrambled with ******
[Observed result] 
![image](https://cloud.githubusercontent.com/assets/19411047/16586354/c319ad76-42c5-11e6-9c75-3760222df3c2.png)

[Details]
See above; 

[Messages and logs]

**Comment by kowalczyka** [comment]
I have additional question:

Shoul we provide also this for the form in blue portal (when defining/editing makrtable service) or in marketplace during creating new subscription? Or should it stay as it is now as standard input with string?

**Comment by GoebelL** [comment]
>Password are displayed scrambled with ******
No, there is no semantic interpretation of configuration settings. It's absolutely correct, that passwords must never be stored in clear text. The have to be stored encrypted. Like just any other configuration setting, the  values will be displayed here to the platform operator, same as they are stored.

**Comment by kowalczyka** [comment]
[Details of fix]
Password will be encrypted when user  set the value to _crypt:<password>

[Fixed build]
BES_MASTER_Delivery #733

**Comment by kowalczyka** [comment]
This was fixed only in UI (password is scrambled). Password encryption was decided to be resolved with separate feature.

**Comment by SylviaDehn** [comment]
verified password scrambled on UI pages 2016/07/22
