### ISSUE TITLE
vmware controller: error message in email could be improved

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#182]
[Version]
V16.0 Fix 6
[Date]
2016/06/26

[Test category] 
Creative

[Description]
call action on a instance where the back end is already deleted 
[Steps to reproduce]
To simulate errors:
subscribe to vmware image
delete the running instance on the backend (ess) via vShere client
call on CT MG side any action i.e.: Restart of virtual machine
Error is thrown (correct) but the wording in the email is 'very basic':
Dear user,
The current operation on subscription 'VMware_Original_With_ALL' for customer 'd5b8f512' has been suspended (Instance: '1467730620987').
Reported problem: Failed to check VM run state of xy. OSCM-Instance-ID: 1467730620987
To continue automatic processing, please click the following URL:
https://Time.DarkSide.com:28881/oscm-app/notify?sid=1467730620987&cid=ess.vmware&_resume=yes 
 
"Failed to check VM run state" is not very (lets say) elegant. The corresponding error in the log file states:
[2016-07-05 17:14:19] [__ejb-thread-pool9] ERROR Actions checkVMRunning Failed to check VM running state of instance 1467730620987
java.lang.Exception: Failed to retrieve information of VM xy

Failed to check VM running state of instance.... is better then the message in the email

[Expected result]
the error message in the email should contain pain correct English 
[Observed result] 
Failed to check VM run state of xy
[Details]
See above; 

[Messages and logs]

**Comment by StavrevaS** [comment]
The error message for email is changed according to the comment.

**Comment by elfriedegoetz** [comment]
ok with 2016/07/22
