### ISSUE TITLE
VMware: Cannot see the controller database configuration for vSphere from UI

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#183]
[Frequency]
Always

[How to reproduce]
Set up VMware adapter

[Expected result]
The controller database configuration for vSphere are shown in UI.

[Observed result]
The controller database configuration for vSphere are not shown in UI.

I could not find the way to see the controller database configuration for vSphere. After setup, user cannot check whether these parameter are correct or not.
User have to check these settings to administrate VMware adapter and vSphere.

**Comment by StavrevaS** [comment]
The UI for vSphere parameters was not planned nor required for VMWare adapter. This issue cannot be considered as a bug, or solved as a bug fix. We can only improve the import functionality for this release.
If UI for vSphere parameters is required, it should be planned as a new feature for the VMWare adapter.
