### ISSUE TITLE
The error message is not proper when "define publishing option" with a not accessible marketplace.

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#188]
Date: 2016/07/01 
[Test category]: creative Test

Severity: minor

[Steps to reproduce]
1. In first browser such as firefox, Platform operator create a closed marketplace "mp1" and make a supplier access to it.
2. In another browser, such as IE, login as supplier, go to "define publishing options" for some services, input all the information, select the marketplace "mp1", do not click "save" button, just stay at this page with all information input.
3. In first browser, platform make the supplier has no access to "mp1"..
4. In the second browser, supplier click on "save" button.

[Expected result]
Failed to save and give some proper message.

[Observed result]
Failed to save, but the error message is not friendly: "editForm:marketplace: Validation Error: Value is not valid"

**Comment by GoebelL** [comment]
This is a quite unrealistic use case, that service manger is restricted to access his marketplace just in the same time when he tries to publish services there. Anyway when reattempting the operation the list is reloaded and the marketplace will be no longer available. 
The feature is meant for restricting customers accessing other marketplaces. Of course, OSCM allows supplier and customer to be the same organization, but this restriction doesn't make much sense then. However, I don't consider a need for improving such message occurrence, which appears in special concurrency situation of a very uncommon case, where there are eventually no functional user impacts.
