### ISSUE TITLE
Omit Billing Address and Payment Info in the Subscription Process

### ISSUE THREAD

**Issue by mdehn** [servicecatalog/development#19]
In enterpise solution environments the service catalog is sometimes used to make internal services available to the employees of the company. In such "private" environments charging subscriptions may not be relevant.
In order to keep unnecessary information hidden to users in such environments an option should allow to reduce the 3-step subscription process to 2 steps, by omitting billing address and payment information.

**Comment by DawidCh** [comment]
#53

**Comment by mdehn** [comment]
Please do not close "feature" issues as long as the milestone, which they are assigned to, is not released.
