### ISSUE TITLE
The customer still can be registered when the marketplace is not accessible for this supplier.

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#191]
Date: 2016/07/01 
[Test category]: creative Test

Severity: minor

[Steps to reproduce]
1. In first browser such as Firefox, Platform operator create a marketplace "mp1" make a supplier access to it.
2. In another browser, such as IE, log in as supplier, go to "register customer", input all the information, select the marketplace "mp1", do not click "save" button, just stay at this page with information input.
3. In first browser, platform make the supplier has no access to "mp1".
4. In the second browser, supplier click on "save" button.

[Expected result]
Register customer failed, because the selected browser is not accessible at that time. And should give some error message.

[Observed result]
Register successfully with the message "The organization 96ef71d6 has been successfully registered."

**Comment by GoebelL** [comment]
This is not a bug. Some small synchronization gab is unavoidable, however the setting is read in the other browser session. Anyhow, after completing the registration the update is reflected correctly. This works as expected.
