### ISSUE TITLE
“VMWare controller:” Linux root password from Tech Service is not used

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#192]
[Version]
V16.0 Fix 6
[Date]
2016/06/26

[Test category] 
Creative

[Description]
Create Linux instance
Set TechService parameter 'Linux root password" to 'sunny'
Subscribe to service
Change to vSphere  Client
open console terminal of the just created instance
log on with root and new password (sunny)
[Steps to reproduce]
see above
[Expected result]
log on with root and given password
[Observed result] 
authetication error
[Details]
See above; 

[Messages and logs]

**Comment by StavrevaS** [comment]
The linux password can be set only with executing script. Initially the machine is provisioned with the default credentials from the VM template.

A sample script changeRootPassword.sh will be packaged into the vmware install pack to the samples directory.

The following service parameters are necessary to execute the script:
- SCRIPT_URL
- SCRIPT_USERID
- SCRIPT_PWD

The service parameter LINUX_ROOT_PWD contains the new linux root password which will be set with executing the script.

The sample script can be provided for example in the app-domain docroot directory. The URL will be:
http://<host-app>:<port-app>/changeRootPassword.sh


If the script contains placeholders for the service parameters like this sample script, it is necessary to insert the user credentials of the service manager as controller settings in the bssapp database with the following identifiers:
USERID_<sellerOrganizationId>
USERKEY_<sellerOrganizationId>
USERPWD_<sellerOrganizationId>

This functionality must be documented.

**Comment by SylviaDehn** [comment]
verified 2016/07/22
Script functionality is documented for setting LINUX password.
Script works ok. LINUX root password is not used from technical service instead script is provided.
