### ISSUE TITLE
Browse All Services does not work in category page

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#195]
[version]
V16.0 Fix6

[Frequency]
Always

[How to reproduce]
1. Login as customer to marketplace
2. Click category
3. Click "Browse All Services"

[Expected result]
- All services are shown

[Observed result]
- The window was not changed

**Comment by GoebelL** [comment]
I could reproduce this for categories and for tags. Filters have to be reset when clicking browse all. 
The bread crumb link behind "Home > All services" is working correctly. 
Fix: Same navigating logic required on "Browse all Services" button as for the "Home > All services".

**Comment by SylviaDehn** [comment]
[Build] 2016/08/01
