### ISSUE TITLE
The subscription is suspend with the "update payment information" after remove and add the access again

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#197]
Date: 2016/07/01 
[Test category]: creative Test

Severity: minor

[Steps to reproduce]
1. Log in as supplier, define a service and publish it on the "closed" marketplace.
2. Go to the "closed" marketplace, log in as an authorized customer, subscribe it.
3. Log in as supplier, go to "manage access" page, make the customer not accessible to the marketplace.
4. Then make the customer accessible to the marketplace again.
5. Go to marketplace log in as the customer, to check the subscription.

[Expected result]
The subscription should be displayed correctly.

[Observed result]
The subscription is suspend, but the information is "please update your payment information".
Why do customer need to update the payment during this process?

**Comment by GoebelL** [comment]
This refers to issue #164 and will be corrected there.
