### ISSUE TITLE
The service with tag can be displayed in the "closed" marketplace before any user log in.

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#198]
Date: 2016/07/01 
[Test category]: creative Test

Severity: minor

[Steps to reproduce]
1. Technical provider define some tags for a service definition.
2. Supplier define a service and publish it on a "closed" marketplace.
3. Go to this marketplace, click on a "tag".

[Expected result]
When accessing the home page of a "closed" marketplace, the list of services is empty.
 The user has to login first, before he can see any services.

[Observed result]
The page displayed the related services in the background, and when cancel the login dialog, it is show to the customer before he logged in.

![q -20160708134139](https://cloud.githubusercontent.com/assets/15228666/16678487/0dc3455a-4512-11e6-913f-42904c48be17.png)

**Comment by GoebelL** [comment]
The dialog must not be cancel-able.

**Comment by jiangweiyi** [comment]
Verified by FNST
[Verified-build]BES_MASTER_DELIVERY-7362016/07/15
[Verified-details]Now the login dialog is not cancel-able, so verified.
