### ISSUE TITLE
Suspend subscription can not be active when the HIDE_PAYMENT_INFORMATION set as true after some operations.

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#199]
Date: 2016/06/02
[Test category]: creative Test

Severity: minor

[Steps to reproduce]
1. Install CTMG with the HIDE_PAYMENT_INFORMATION set as true.
2. Log in as supplier, define a paid service and publish it on the "closed" marketplace.
3. Go to the "closed" marketplace, log in as an authorized customer, subscribe it.
4. Log in as supplier, go to "manage access" page, make the customer not accessible to the marketplace.
5. Then make the customer accessible to the marketplace again.
6. Go to marketplace to check the subscription. 

[Expected result]
The subscription should show correctly.

[Observed result]
The subscription is suspended, and there is the message: please update your payment information.

There is no payment to be updated by the customer in CTMG, and then the subscription can not be active any more.

**Comment by GoebelL** [comment]
This refers to issue #164 and will be corrected there.
