### ISSUE TITLE
"VMWare controller:" Dynamic Load Balancing Section "Distribute VMs in the order of the configured hosts" does not alternate

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#202]
[Version]
V16.0 Fix 6
[Date]
2016/06/26

[Test category] 
Creative

[Description]
The load balancer does not switch between configured systems
[Steps to reproduce]
settings for Load balancer:
![image](https://cloud.githubusercontent.com/assets/19411047/16724726/717f3d44-4754-11e6-8ebe-85159b313dd1.png)

instantiate 2 times the same vmware instance (make sure that the values "Target host name" and "Target staorage name" are empty to force the load balancer to work)
[Expected result]
system 1 (vm1-1Freddy-000107) should be on estvmwdev1... and disk VMdev0
System 2: (vm2-1Freddy-000108) should be on estvmwdev2... and disk VMdev1
[Observed result] 
System 1:
![image](https://cloud.githubusercontent.com/assets/19411047/16724764/8e88bcc6-4754-11e6-84b9-c12b41809f5e.png)

System 2:
![image](https://cloud.githubusercontent.com/assets/19411047/16724786/a14fea0a-4754-11e6-9eb6-f6dac7b1314d.png)

As one can see the second system has the same server and disk assigned. 

[Details]
See above; 

[Messages and logs]

**Comment by StavrevaS** [comment]
The functionality is not implemented in the backend yet. The UI should be adapted to support only the first 2 options for the balancer.

**Comment by StavrevaS** [comment]
The issue can be classified as duplicate to issue #177. The functionality is not implemented yet and dropped on UI.

**Comment by elfriedegoetz** [comment]
ok with 2016/07/22 but see issue #244
