### ISSUE TITLE
Support SAML 2 logout in an SSO setup (notify IdP only)

### ISSUE THREAD

**Issue by mdehn** [servicecatalog/development#21]
Currently OSCM supports the "login" in a SAML 2 SSO setup. The "logout" is not supported. In environments with multiple applications it may be important to inform the IdP, if in OSCM a "logout" is performed, in order to take further actions.
Note that a full support of the SAML 2 "logout" with OSCM consuming "logout" requests from the IdP could be implemented in a later version.

**Comment by GoebelL** [comment]
Please do not close "feature" issues as long as the milestone, which they are assigned to, is not released.

**Comment by GoebelL** [comment]
This feature has been implemented. Released with 16.0.6.
