### ISSUE TITLE
Unecessary database accesses when repeatedly requesting the marketplace portal 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#213]
[Version] 
16.0 Fix6

[Date] 
2016/07/01

[How to reproduce]
Compare DB accesses when repeatedly accessing marketplace portal from fix5 to fix6.

[Expected]
Only initially, an additional DB access is required for checking whether or not the marketplace is restricted to customers.

[Observed]
Additional DB accesses for marketplace restriction check with each request. 

[Detail]
MarketplaceBean#isRestricted loads the marketplace domain object with each request. There is no caching. This causes a performance drop.

**Comment by MiethanerR** [comment]
added caching of restriction in configuration

**Comment by GoebelL** [comment]
ClosedMarketplaceFilter needs to be fixed as well for recovering the system performance. This filter accesses to services, and loads user details as well as marketplace VOs on each request.

**Comment by MiethanerR** [comment]
reduced the database accesses via cached configs

**Comment by GoebelL** [comment]
The caching fix in MarketplaceBean and ClosedMarketplaceFilter is fine. The resulting system performance boost is evident.
 
However, there is still some tuning need left with the 'restrict marketplace access' feature. There are remaining some DB accesses which should be optimized. In particular the performance should be improved by adding similar caching to org.oscm.ui.beans.marketplace.ServicePagingBean#isSearchAvailable()

This is read two times in the marketplace header facelet 
\oscm-portal\WebContent\WEB-INF\facelets\tags\marketplace\header.xhtml
