### ISSUE TITLE
operation failed when marketplace not selected after deactivate

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#215]
Date:2016/07/13 (fix6+)

[Steps to reproduce]
1. As marketplace owner, choose "Marketplace/Manage access", define "Authorized customers only"
2. Log in as supplier that has a service that is currently published to marketplace of 1.
3. This supplier is not authorized in marketplace of 1.
4. deactivate service; goto define publishing options for this service
5. now you see no marketplace selected (which is ok);
    press save anyways

[Expected result]
save button is greyed, or error message that no marketplace has been chosen

[Observed result]
operation failed

[Details]
This is different than a new service, because publishing options already exist, but are incorrect (at least the 
marketplace).

**Comment by mdehn** [comment]
Please do not allow a marketplace owner to remove the access of a supplier to a marketplace as long as this supplier has published services on this marketplace.

**Comment by GoebelL** [comment]
The situation only occurs in case the marketplace manager has removed the marketplace access for the supplier, who already has published a service to that marketplace before. 

Solution as discussed with @mdehn
The marketplace manager must be disallowed to remove access for suppliers, who already have published services there. Same as it is now disallowed to remove the marketplace access for customers, who have active subscriptions on that marketplace.

**Comment by GoebelL** [comment]
Depended issue #164

**Comment by SuessI** [comment]
When doing this, please consider:
On the Manage Marketplace Access, when choosing "authorized customers only", all supplier organizations with published services must be selected automatically - in the same way as customer organizations with existing subscriptions. Then it must not be possible to remove the check mark.
Performance is an issue when checking for these supplier organizations...

**Comment by GoebelL** [comment]
The fix for this issue is in integration testing and will be included in 16.1 GA1.

**Comment by MiethanerR** [comment]
fix was merged into master

**Comment by jiangweiyi** [comment]
Build: BES_MASTER_DELIVERY-744 2016/07/22

This issue can be reproduced with following steps:
1. As marketplace owner, choose "Marketplace/Manage access", define "Authorized customers only", choose a supplier has access to a marketplace "mk".
2. This supplier publish a service and activate it on a marketplace "mk";
3. Supplier deactivate the service;
4. Marketplace owner make the supplier has no access to the marketplace "mk";
5. Supplier go to the "define publishing options" page, no marketplace is selected.

[Expected result]
Save button is greyed.

[Observed result]
Save button can be clicked, and after press, operation failed

So I think it should be reopened.

**Comment by MiethanerR** [comment]
Merged fix into master. The marketplace key will now be removed from the catalogentries of all products that belong to an organization that has no longer access to the given marketplace.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/09 verified
