### ISSUE TITLE
Restrict the access to marketplaces to organizations

### ISSUE THREAD

**Issue by mdehn** [servicecatalog/development#22]
Currently a marketplace owner cannot restrict the access of users to his marketplace. Any user, who knows the marketplase URL can view the service catalog and can subscribe to services.
A marketplace owner may preferre a "closed" marketplace, where he can control the access of users to the services listed in the catalog.

**Comment by mdehn** [comment]
Please do not close "feature" issues as long as the milestone, which they are assigned to, is not released.

**Comment by GoebelL** [comment]
Martin already asked you not to close "feature" issues as long as the milestone, which they are assigned to, is not released.

**Comment by kowalczyka** [comment]
I think that it was closed automatically with merge to master. I did not closed it intentionally.

**Comment by GoebelL** [comment]
This feature has been implemented. Released with 16.0.6.
