### ISSUE TITLE
Provide a controller for VMware IaaS

### ISSUE THREAD

**Issue by mdehn** [servicecatalog/development#23]
OSCM comes with mature integration capabilities for providing and provisioning IaaS services through its service catalog, e.g. OpenStack, Amazon Web Services or  Fujitsu Trusted Public S5.
VMware is a very popular virtual machine environment with a mature product portfolio. Therefore provide an adapter for IaaS services for VMware.

**Comment by mdehn** [comment]
For a discussion thread about the contribution of this feature please see #3.

**Comment by GoebelL** [comment]
This feature has been implemented. Released with 16.1.
