### ISSUE TITLE
Setting up and executing Unit/Integration tests

### ISSUE THREAD

**Issue by angarg12** [servicecatalog/development#230]
Hello,

I have followed the deverlopers setup and after finishing I would like to execute the suite of Unit and Integration tests to verify that everything is working fine.

When I try to execute the Unit tests on Eclipse I get several errors related to missing DB users and such. 

What are the necessary steps to get the tests up and running?

**Comment by GoebelL** [comment]
Hi @angarg12,

you can find ANT targets for unit and integration testing in  /oscm-build/cruisecontrol.xml :
runJUnitTestsBuild, runIntegrationTests

To run from ANT make sure ${JDK_HOME}/lib/tools.jar is on the classpath and VM heap size is sufficient (-Xmx...). You may need to specify your HTTP/S proxies using  -Dhttps.proxyHost, -Dhttp.proxyHost, -Dhttps.proxyPort and -Dhttp.proxyPort, in order that ivy can fetch the required 3rd party.

**Comment by angarg12** [comment]
Thanks, I was able to run the test suites using this script.
