### ISSUE TITLE
Wrong ports pre-configured in the OSCM Docker container?

### ISSUE THREAD

**Issue by bogdanbarzu** [servicecatalog/development#235]
Following the documentation of the OSCM Docker container on the [OSCM Dockerhub page](https://hub.docker.com/r/servicecatalog/oscm/), I would expect the following port configurations:
BASE_URL_HTTPS: 8081 (but currently it's 8080, same as HTTP, but it should be different)
REPORT_ENGINEURL: 8080 (but currently it's 18080, which differs with the documentation)

Of course those ports can be easily changed, following the [detailed host/port setup guide](https://github.com/servicecatalog/documentation/blob/master/DOCKER.md#configuring-docker-host-and-ports), but for an inexperienced OSCM user that might not be that obvious and she/he might loose patience. So considering that the purpose of the OSCM Docker container is to allow users to quickly and easily test the features of OSCM, I rather see this as major. 

Could somebody please check and repair the defaults for those the ports?

**Comment by kowalczyka** [comment]
The default ports has been updated.
