### ISSUE TITLE
Support keystone API v3 in OpenStack controller

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#241]
I want to add keystone API v3 support to OpenStack controller and some bug fix in order to use OpenStack controller for K5.
I added fix and test code for this function in my repository.
I want to add these function:
* add route to use keystone API v3
  * add parameter of domain ID and tenant ID
  * Using TLS v1.2 protocols to connect K5
* fix checking server exist logic in order not only to use server name "Server"

Can I pull request for this fix?

**Comment by GoebelL** [comment]
Hi @misako0927,

That 'll be a great feature for the OpenStack controller. You are welcome to contribute. 
I have setup the feature branch fb_k5_openstack_enhance. Please raise your pull request there.
