### ISSUE TITLE
getAPPAdministrator in APPConfigurationServiceBean is not public

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#242]
sendActionMailToAppAdmin and sendMail method in APPTImerServiceBean.java call getAPPAdministrator method in APPConfigurationServiceBean. But getAPPAdministrator method is not public. If calling getAPPAdministrator method from APPTImerServiceBean.java, "javax.ejb.EJBException: Illegal non-business method access on no-interface view" is occurred.

We should fix getAPPAdministrator method to public.

[Source code]
  oscm-app\javasrc\org\oscm\app\v1_0\service\APPConfigurationServiceBean.java
[How to fix]
  * before
~~~
    @TransactionAttribute(TransactionAttributeType.MANDATORY)
    VOUserDetails getAPPAdministrator() throws ConfigurationException {
~~~

  * after
~~~
    @TransactionAttribute(TransactionAttributeType.MANDATORY)
    public VOUserDetails getAPPAdministrator() throws ConfigurationException {

~~~

**Comment by StavrevaS** [comment]
The method is changed to public.
