### ISSUE TITLE
Operation button in subscription details is displaced

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#245]
[Date] 2016/07/22

[Test category] Creative

[Steps to reproduce]
1. create VMWare subscription and assign to user
2. go to MySubscriptions page and choose subscription from 1.

[Expected result]
Layout at bottom of page looks nice 

[Observed result]
Layout is crowded and ugly

[Details]
I do not understand the reason that this should be different for vmware and aws subscriptions. For aws subscriptions the layout looks ok.
See attachments:
![vmwaremysubscriptions](https://cloud.githubusercontent.com/assets/15086024/17059105/e18f64e2-5023-11e6-8a3c-fb3c9d7258dc.jpg)

 
![awsmysubscriptions](https://cloud.githubusercontent.com/assets/15086024/17059111/ebfc4bfc-5023-11e6-9115-440e46605c75.jpg)

**Comment by SylviaDehn** [comment]
[Date] 2016/08/09 
looks worse than before 
![details](https://cloud.githubusercontent.com/assets/15086024/17510273/8f516fc8-5e1e-11e6-960e-f8a919bf3564.jpg)

**Comment by kowalczyka** [comment]
Resolved in BES_MASTER_Unit 1588.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/11 verified in IE11, Chrome, Firefox
