### ISSUE TITLE
Self registeration in marketplace is not executed when displaying terms and conditions

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#247]
[Version]
V16.0.6
[Build]
2016-07-03

[How to reproduce]
1. Connect to a marketplace.
2. Press "Login" button.
3. Press "Register" button.
4. Input mandatory items.
5. Click content of "terms and conditions".
6. Push "Register" button.

[Expected result]
The user is registered temporary and has received an email.

[Observed result]
The empty register form displays again. No email sent.

**Comment by MiethanerR** [comment]
fixed and merged into master

**Comment by SylviaDehn** [comment]
[Build] 2016/08/01 verified

**Comment by misako0927** [comment]
Could you explain what is cause of this issue?

**Comment by MiethanerR** [comment]
When the terms site was opened (even in a new tab), a new java faces context was created and the old one discarded. When then the button on the registration site was clicked, a new context was created again, the site reloaded and previous values lost. I changed the link call, so the server doesn't see it as completely new site.
