### ISSUE TITLE
Unable to email ICLA to secretary@ml.css.fujitsu.com

### ISSUE THREAD

**Issue by zfouts** [servicecatalog/development#25]
This is the mail system at host kw-mxoi1.gw.nic.fujitsu.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

The mail system

<secretary@ml.css.fujitsu.com>: host ml.css.fujitsu.com[10.134.61.177] said:
    550 5.1.1 <secretary@ml.css.fujitsu.com>: Recipient address rejected: User
    unknown in local recipient table (in reply to RCPT TO command)

Final-Recipient: rfc822; secretary@ml.css.fujitsu.com
Original-Recipient: rfc822;secretary@ml.css.fujitsu.com
Action: failed
Status: 5.1.1
Remote-MTA: dns; ml.css.fujitsu.com
Diagnostic-Code: smtp; 550 5.1.1 <secretary@ml.css.fujitsu.com>: Recipient
    address rejected: User unknown in local recipient table

**Comment by otome0927** [comment]
ML for ICLA and CCLA is not "secretary@ml.css.fujitsu.com" but "secretary-oscm@ml.css.fujitsu.com".
Readme have to be fixed.

**Comment by bogdanbarzu** [comment]
Corrected in the README file.

**Comment by GoebelL** [comment]
Thank you Bogdan. The previous address was only working internally. The addresses in the README files and in ICLA and CCLA files are correct now.

**Comment by StavrevaS** [comment]
Welcome to the OSCM Community @zfouts! 

We are very happy, but also curious about the new contributions. Can you shortly present your ideas and how you discover the OSCM?

**Comment by zfouts** [comment]
Thank you, @StavrevaS. I was introduced to OSCM via the Linux Foundation Summit where Wolfgang Ries did a presentation.

I'm still trying to wrap my head around how the project is setup, etc.

**Comment by StavrevaS** [comment]
Hi @zfouts,

how is your progress with the OSCM setup? If you have any questions about installation or Docker image, we are glad to support you. 

Do you already know our [OSCM Forum](http://openservicecatalogmanager.org/ui/forums/)? You are welcome to share your questions or ideas. 

We are looking forward to hear from you!
