### ISSUE TITLE
Tags window cannot be closed

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#252]
[Version]
16.0.6

[How to reproduce]
1. The blue portal is logged in Technology provider.
2. Click the "Update service definition".
3. The technical service is selected. 
4. Click content of "Display the most popular tags".
5. Click Enter key.

[Expected result]
Tags window is close.

[Observed result]
Tags window is not close.

[Detail]
When 'Enter' is pushed, the Tags window cannot be closed. 
Can close the Tags window. 

[Message and logs]
Nothing

**Comment by SylviaDehn** [comment]
[Build] 2016/08/09 
FF 47
If the close button is pressed in the tags window, the tags window closes (good)
If the enter is pressed first, and then the close button, the window never closes (bad)
If enter is pressed, the "close" action should be carried out right away.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/09 verified
ENTER does not block close button anymore
