### ISSUE TITLE
The MockService in the latest version of the docker image contains a wrong provisioningUrl 

### ISSUE THREAD

**Issue by mfalkenhahn** [servicecatalog/development#256]
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tns:TechnicalServices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="oscm.serviceprovisioning/1.9/TechnicalService.xsd ../../oscm-serviceprovisioning/javares/TechnicalServices.xsd" xmlns:tns="oscm.serviceprovisioning/1.9/TechnicalService.xsd">
  <tns:TechnicalService accessType="LOGIN" allowingOnBehalfActing="false" baseUrl="http://localhost:8080/oscm-integrationtests-mockproduct" billingIdentifier="NATIVE_BILLING" build="20.10.2015" id="MockService" loginPath="/login" onlyOneSubscriptionPerUser="false" provisioningPassword="adminadmin" provisioningType="SYNCHRONOUS"

 **provisioningUrl="http://localhost:8081/oscm-integrationtests-mockproduct/ProvisioningService?wsdl"** 

should be replaced by:

 **provisioningUrl="http://localhost:8080/oscm-integrationtests-mockproduct/ProvisioningService?wsdl"**

........
provisioningUsername="admin" provisioningVersion="1.0">
    <LocalizedDescription locale="en">You can create
    	folders upload files and share them with other users.</LocalizedDescription>
    <LocalizedDescription locale="de">Sie können Ordner
    	anlegen, Dateien hochladen und diese mit anderen Teilnehmern

**Comment by GoebelL** [comment]
>kowalczyka added the bug/status/duplicate label ...
If this is already fixed with  #235 or #234 then please close this issue.
