### ISSUE TITLE
The service can be displayed in the "closed" marketplace before any user log in with SAML_SP mode.

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#258]
Date: 2016/07/22
[Test category]: creative Test

Severity: normal

[Steps to reproduce]
1. Marketplace owner add some categories for the marketplace "mk";
2. Set the marketplace to be "closed", and supplier has access to this marketplace;
3. Supplier publish a service and activate the service in the marketplace "mk";
4. Go to marketplace homepage, click the category link;

[Expected result]
Go to login page.

[Observed result]
In internal mode, the login window pop up, and category link cannot be clicked;
In SAML_SP mode, the category link can be clicked and the services are shown, (same situation with browse all service link and tag link).

**Comment by StavrevaS** [comment]
@grubskim, please consider this issue by fixing #194

**Comment by grubskim** [comment]
Will be fixed along with #194

**Comment by AndreasTWolf** [comment]
tested with build from 2016/08/07
