### ISSUE TITLE
Platform operator can not go to "closed" marketplace which he already has the access to it.

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#259]
Date: 2016/07/22
[Test category]: creative Test

Severity: normal

[Steps to reproduce]
1. Platform operator create a marketplace "m_sp", select a supplier as owner of this marketplace "m_sp";
2. Create a marketplace "m_pl", select platform operator as owner.
3. Login as this supplier, click "manage access" under marketplace, select marketplace "m_sp", check "Authorized customers only", then check platform operator, save.
4. Login as platform operator, click "go to marketplace" at the top, click the dropdown list.

[Expected result]
The drop-down "Marketplace" lists 
 - "open" marketplaces and 
 - "closed" marketplaces, which the user has access to.

There should be marketpalce "m_sp" and "m_pl" shown in the option

[Observed result]
There is not marketpalce "m_sp" shown in the option, only show "m_pl"

**Comment by StavrevaS** [comment]
The platform operator has only marketplace owner role, so he will see only the marketplaces he owns (opened and closed with access).

The supplier (and other seller roles reseller and broker) can also see the marketplaces where they can publish (opened and closed with access), not only the marketplaces they own.
