### ISSUE TITLE
Supplier can activate a service on a marketplace which he had no access to it

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#260]
Date: 2016/07/22
[Test category]: creative Test

Severity: normal

[Steps to reproduce]
1. Login as platform operator, create supplier S1 and S2, create marketplace M1 with owner S1, create marketplace M2 with owner S2. 
2. Log in as S2, click "manage access" under marketplace, select marketplace M2, check "Authorized customers only", then check S1, save.
3. Login as S1, define a service SV, input necessary information.
4. Click "Define publishing option", select service SV and marketplace M2, save and active it.
5. Login as S2,  the checkbox of S1 can't be unclicked in "manage access" under Marketplace.
6. Login as S1, deactive service SV, save.
7. Login as S2, unclick the checkbox of S1 in "manage access" under Marketplace, save.
8. Login as S1, go to " Activate or deactivate services" page, select the SV, click on "save" button to active the service SV, save.

[Expected result]
Because of step7, S1 can't active service SV on this marketplace.

[Observed result]
S1 can still active service SV.

**Comment by StavrevaS** [comment]
I think the expectation here is wrong. The closed marketplace is unavailable for the organization as customer if it has no access, It cannot see the published services and cannot subscribe. But in its role of supplier, the organization can still activate/deactivate the service on the marketplace, unless it is unauthorized seller for that marketplace.
@mdehn, please comment.

**Comment by mdehn** [comment]
S1 should not be able to activate the service. A message should tell him, that in publishing options he has to select a marketplace, which he has access to.

**Comment by StavrevaS** [comment]
This issue is fixed with #260 and #215.
