### ISSUE TITLE
During publish the service on marketplace, if check the broker or reseller, save operation is failed, if not, successfully.

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#264]
Date: 2016/07/22
[Test category]: creative Test

Severity: minor

[Steps to reproduce]
1. Platform operator create supplier, reseller, broker;
2. Supplier go to "define a service" page, input all the related information, click on "save";
3. Go to "define publishing options" page, select the service and select a marketplace, click on "save";
4. Check the reseller and broker, then click on "save" again.

[Expected result]
After step3 and step4, the reaction should be the same.

[Observed result]
After step3, save successfully;
After step4, Failed with the message "No price model has been defined for the specified service."

**Comment by MiethanerR** [comment]
According to documentation, this is intended functionality. See Supplier Guide (EN) page 18.
