### ISSUE TITLE
In marketplace home page, a huge long length number of service price will excced the service's frame

### ISSUE THREAD

**Issue by wangyingfnst** [servicecatalog/development#266]
Date: 2016/07/22
[Test category]: creative Test

Severity: minor

[Steps to reproduce]
    1. Login as a supplier, define two serivces.
    2. Define for these two service in the Price model. Fill the price with a huge long length number.
    3. Input the public opiton and active.
    4. Go to the marketplace, enter the home page."

[Expected result]
The huge long length number of service will present continuously from next line if it will exceed the length of frame.

[Observed result]
The number did not present from next line, the price number of the service in the left frame exceeds toward right and covers the service frame on the right.
![long length price number](https://cloud.githubusercontent.com/assets/14818896/17287443/49d9a4fa-5802-11e6-93f4-b3dca279caf4.JPG)

**Comment by StavrevaS** [comment]
This is not realistic case, so there is no need for development effort here.
There is no service which costs so much.
