### ISSUE TITLE
oscm-integrationtests-mockproduct information are not in Readme for sample of external billing

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#273]
[version]
v16.0 GA1

[Frequency]
Always

[How to reproduce]
See Readme.html in oscm-integration-pack\samples\billingPlugin\doc\BillingPlugin

[Expected result]
The information which oscm-file-adapter need oscm-integrationtests-mockproduct to use are in Readme

[Observed result]
No information of oscm-integrationtests-mockproduct are in Readme

[Note]
oscm-integrationtests-mockproduct is provided in oscm-integrationtests-pack. But we should put this example war in oscm-integration-pack\samples\billingPlugin in order only to use mock app for external billing as ESCM.
Please put oscm-integrationtests-mockproduct in billingPlugin sample directory and write about this exanple in Readme of external billing sample.

**Comment by SuessI** [comment]
The oscm-integrationtests-mockproduct is an application for general testing purposes particularly by development. In my opinion, it is now not in a state that allows to include it in a package that has product quality. Clean-up and review is required.
It would probably be helpful to have an application and technical service as a sample. But then we should give more thought to what we want to include and how this should look in detail. It should not only be included in the billing adapter sample, but as a sample of its own.
For testing purposes, there is no need to include the mockproduct with the billing sample. It can be obtained from the oscm-integrationtests-mockproduct package.
The billing plugin sample is focussed on the implementation of a billing adapter, not on the provisioning of applications. We should not mix things too much in my opinion.

**Comment by StavrevaS** [comment]
I agree with @SuessI. Providing a general-purpose application which implements the provisioning and operation service is better long-term solution. It may be derived from the existing mock product, but as written in the previous comment, review and renaming are necessary. The mocks are developed for test purposes for development team, and have no sample quality. 
The test teams can use the mocks since they are provided with the optional integrationtests package.
