### ISSUE TITLE
[PT]The "Show price model" is not displayed.

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#278]
[Summary]
The "Show price model" is not displayed. 

[Product name and version]
FUJITSU Software Enterprise Service Catalog Manager V16.1 GA1
BES_MASTER_DELIVERY-7442016/07/22 

[Client IDE]
OS       : Windows7 Pro SP1
Browser  : Firefox(48.0)

[Reproduce frequency]
Always

[GBP Bug Classification]
Short Name:PB-InvFun
Fundamental Function:Yes
Workaround:Yes
Severity:Major

[How to reproduce]
1. The service of external billing is activate.
2. The customer is click "Show Details".
3. Click "Get it now"
4. Click "next"

[Expected result]
The "Show price model" is displayed. 

[Observed result]
The "Show price model" is not displayed. 

[Detail]
"Show price model" is not displayed at the service of an external billing.
Please display the link of "Show price model". 

[Message and logs]
Nothing

**Comment by SylviaDehn** [comment]
[Date] 2016/08/08 verified, 
link is displayed and works.

**Comment by StavrevaS** [comment]
Code for external price model has been added in wrong place and was not executed. The fix modified the servicePriceLink.xhtml page and moved code with external price model to the first conditional.
