### ISSUE TITLE
Password in clear text in 'Update configuration settings'

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#284]
[Version]
V16.1 GA1
[Date]
2016/08/07

[Test category] 
Creative

[Description]
The content of the parameter 'SSO_SIGNING_KEYSTORE_PASS' in written in clear text.  
[Steps to reproduce]
Install CTMG in SAML mode. 
Open Portal.
Login as Platform Admininstrator
Open 'Update configuration settings' section
Check the entry 'SSO_SIGNING_KEYSTORE_PASS'
[Expected result]
The content of the password field is displayed as '******'
[Observed result] 
SSO_SIGNING_KEYSTORE_PASS "changeit"
[Details]
See above; 

[Messages and logs]

**Comment by AndreasTWolf** [comment]
This is a security issue....

**Comment by MiethanerR** [comment]
The UI now uses a password input field for passwords. Readonly passwords are shown as five stars.
