### ISSUE TITLE
'Single sign off' together with 'Access restricted marketplace' allows log on without re-authentication  

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#285]
[Version]
V16.1 GA1
[Date]
2016/08/07

[Test category] 
Creative

[Description]
'Single sign off' together with 'Access restricted marketplace' allows log on without re-authentication: Log on to access restricted marketplace where the uid is not allowed. IDP Log on screen appears; enter credentials and press enter;  The user gets placed to the error page that the access is denied, because the user id is allowed to access this particular marketplace. This is correct and expected.
Nor access with out leaving the browser an marketplace where the use has access to. 
The user is immediately logged on without getting asked for credentials again.  
When 'Internal Mode' is used the user gets asked for the credentials.
Security issue...

[Steps to reproduce]
Install CTMG in SAML mode
Create two marketplaces: one with access one without access to it;
Access the one where access is denied; After entering the credentials through the IDP the access to the marketplace is denied;
Now (without closing the browser) access a different marketplace where the user id has access, (e.g.: via direct link:  server.xxx/portal/marketplace/?mId=d5b8f512
[Expected result]
IDP Log in screen to enter the credentials
[Observed result] 
straight in in the given market place
[Details]
See above; 

[Messages and logs]

**Comment by AndreasTWolf** [comment]
Additionally:
The redirect out of the error page, once a logon to an restricted marketplace took place, is not always correct:
How to reproduce:
Test with an user who is customer only (No access to the portal), but has access to the marketplace written in the configuration setting: MP_ERROR_REDIRECT_HTTPS; (like server.xxx/portal/marketplace/?mId=d5b8f512)
Log on to an restricted market place with: server.xxx/portal/marketplace/?mId=f7c06118
Enter credentials at the IDP site, enter, get the error page.
Now change the URL to server.xxx/portal and press enter.
Nothing happens. The page remains.

Expected:
Once the URL server.xxx/portal is called, the system should redirect to the portal, detect that the user does not have authority to access the portal, redirect to the error URL, here the system should detect that an login did not (yet) happen and showing (dependent on the setting 'Featured Services' or 'grouping Services...') either the IDP login screen or the default landing page of the marketplace.

**Comment by DawidCh** [comment]
> Create two marketplaces: one with access one without access to it;
> Access the one where access is denied; After entering the credentials through the IDP the access to the marketplace is denied;
> Now (without closing the browser) access a different marketplace where the user id has access, (e.g.: via direct link: server.xxx/portal/marketplace/?mId=d5b8f512
Why it is security issue? User has access to marketplace which he should and does not have access to restricted marketplace. It seems to be correct behaviour.
Or maybe I did not understand sth here.
Just to be clear about when login is done. When you enter credentials in IDP and click login, authentication reponse is being created by IDP and sent to oscm. Here, saml envelope is being processed and session in OSCM is created. Then rights to requested pages are being resolved.
I do not think that another logging in is needed. If the session is established in OSCM, the user is known to the system as well as his rights of access to marketplaces or portal.
Just to sum up. The first scenario is not a bug for me. If you think it is, lets discuss.

The second one - we can do sth about it.

**Comment by DawidCh** [comment]
The second issue has been fixed. Discussion has not been picked up on first issue so closing bug.
