### ISSUE TITLE
 [PT]The service view imported from the definition of VMware sample is collapsed

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#289]
[Summary]
The service view imported from the definition of VMware sample is collapsed.

[Product name and version]
V16.1 GA1

[Client IDE]
OS       : Windows7 Pro SP1
Browser  : Google Chrome(52.0.2743.116 m)

[Reproduce frequency]
always

[Bug Classification]
Short Name:PB-InvFun
Fundamental Function:No
Workaround:Yes
Severity:Minor

[How to reproduce]
1. Login to administration portal as technology provider
2. Open Technical Serviceのimport service definition
3. Import TechnicalService_VMware.xml
4. Open Service view to click the imported TechnicalService
5. Scroll down on the Service view

[Expected result]
The service view is showed correctly.

[Observed result]
Operation definitions are overlapped with Parameter definitions.

[Detail]
After importing TechnicalService_VMware.xml, the service view is collapsed. Some part of  Operation definitions are overlapped with Parameter definitions..

[Message and logs]
nothing

**Comment by grubskim** [comment]
[Details of fix]
The cause of this issue was the CSS max-height property set to 100%. I have changed it to take the parameter, and in this case set it to "none" which fixed the issue.

**Comment by SylviaDehn** [comment]
[Build]2016/08/11 16.1 GA2 verified with Chrome, IE11, Edge, FF
