### ISSUE TITLE
no build for vmware controller shown in pop-up

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#290]
[Build] 
16.1 GA1

[How to reproduce]
1) as Tech Service provider of VMWARE go to
http://estsdehn.intern.est.fujitsu.com:8880/oscm-app-vmware/vcenter.jsf
2) press Fujitsu logo

[Expected result]
Version and Build number are shown

[Observed result]
only version number is shown, build is missing. For all other controllers this info is available
![buildmissing](https://cloud.githubusercontent.com/assets/15086024/17547756/18709c3c-5ee9-11e6-91b1-1df0d4d5df61.jpg)

**Comment by StavrevaS** [comment]
Fixed with adding a bean which reads the build number. This is the same solution as for other controllers.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/11 16.1 GA2 verified
