### ISSUE TITLE
If-Match is missing in Header, but etag property is not ignored

### ISSUE THREAD

**Issue by SchneiderW** [servicecatalog/development#293]
A PUT with oscm-trigger/v1/triggers/<nr> and a header
Content-Type: application/json
Authorization: Basic abcd
Accept: application/json

results in a 409 staus because the etag property in the body is not ignored.
Body looks like:

{
"description": "Subscription terminated 4",
"target_type": "WEB_SERVICE",
"target_url": "https://server:8881/sampleService/SampleService?wsdl",
"owner": { "id": 13000, "description": "ABC Inc." },
"action": "UNSUBSCRIBE_FROM_SERVICE",
"links": { "owner_id": 13000 },
"etag": "7",
"id": 15001
}

In this case the property etag should be ignored.

**Comment by MiethanerR** [comment]
Fix merged into master. ETAG is now handled correctly.
