### ISSUE TITLE
Mandatory properties not correctly handled

### ISSUE THREAD

**Issue by SchneiderW** [servicecatalog/development#294]
A PUT request to update trigger requires mandatory parameters:
* description
* suspend
* target_type
* target_url
* action
In case one of them is missing, different behavior can be seen.
Missing 'description' or 'action', "bad request" is returned,
missing 'target_type' or 'target_url', internal server error 500 is returned,
missing 'suspend', the value is set to false and 204 is returned.

**Comment by MiethanerR** [comment]
this will be fixed together with issue #293

**Comment by MiethanerR** [comment]
Fix merged into master. All required fields are now checked.
