### ISSUE TITLE
Customer organization as marketplace owner cannot update the marketplace settings

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#299]
Version 16.1

[How to reproduce]:

1. Login as platform operator;
2. Create customer organization ORG1 (no role selected);
3. Create marketplace and set the ORG1 as owner;
4. ORG1 admin receives a mail that ORG1 is marketplace owner;
5. Click the update marketplace link in the mail (e.g http://localhost:8180/oscm-portal/shop/updateMarketplace.jsf)

[Observed]
The administration portal is shown with error message: "You do not have sufficient authorities to view the requested page."
Furthermore, by managing users, the user role "marketplace manager" is not shown.

[Expected]
The user should be able to update the marketplace. Think about other marketplace managing tasks like authorizing sellers and manage access on marketplace.

**Comment by MiethanerR** [comment]
I don't know how to reproduce this since i can't create a organization without roles and without a marketplace.

**Comment by MiethanerR** [comment]
After clarifying some things I still can't reproduce the error with the current build from master.
