### ISSUE TITLE
Contribute a vmware controller

### ISSUE THREAD

**Issue by uspecht** [servicecatalog/development#3]
We want to contribute a controller for provisioning VMs over VSphere API.
Please advise how to proceed.
Open questions so far:
- Level of quality
- Branch or fork
- How to handle third party libraries added to oscm

**Comment by GoebelL** [comment]
That's great! You are welcome to contribute.
Please sign and submit the CLAs as described here: https://github.com/servicecatalog/development#contributions and proceed the steps.

Regarding open questions:
> Level of quality
Following is required:
- All source code is formatted (required templates will be shared)
- All source compiles in OSCM main build (target All.BUILD)
- Separate test projects according OSCM project layout 

> Branch or fork
Feel free to fork the OSCM repository. All contributions, fixes or new features are targeted to separate branches in OSCM. We'll provide you the respective branch in OSCM. Once you're done with coding and testing, above requirements are met and you are keen for merging your source, the only thing you need to do is to create a pull request from comparing your fork with this OSCM branch. Please see https://help.github.com/articles/using-pull-requests/ for sending pull request.

> How to handle third party libraries added to oscm?
OSCM is published with Apache 2.0 license and any of it's content including the third party must be complaint. Before introducing new third party, please first checkout what's already used in OSCM. If you're still going for adding third party, please state it. Try searching the needed  on central Maven and check for Apache license.

**Comment by StavrevaS** [comment]
Great idea @uspecht! 
A VMWare controller will be a perfect extension for OSCM, which already supports provisioning Amazon EC2 virtual machines and OpenStack instances.
I am curious about the use cases you want to support with the VMWare controller. Could you describe them?

**Comment by uspecht** [comment]
1. Create VM from existing template
When a subscription is created a virtual machine is cloned from a template. 
The installed operating system of the template can be any Windows or Linux.
The template can have up to four network adapters associated to it.
The service parameters of this subscription determine the available resources of that virtual machine.
The following virtual machine resources can be configured:
                - Amount of memory
                - Size of system disk space
                - Number and size of additional disks
                - Number of CPUs
                - The network adapters
                - The network configuration (DHCP or manual) for each NIC
The following operating system features can be configured:
                - Windows Domain Join or Workgroup creation
                - Local Windows administrator password
                - Linux root user password
                - Custom script execution, once after the VM has been created

The subscription creation can be paused after the VM is cloned and configured. 
That pause can be used by administrators to finalize the VM creation (installing Virusscanner, register Windows, ...).
The provisioning is continued by the administrator after he has done his work on the VM.


2. Modify VM
Memory, disk space and the number of CPUs can be modified by changing the subscription configuration

3. Delete VM
The VM is deleted when the subscription is terminated

4 Service Operations
We would support standard operations on VMs:
- Start
- Stop
- Restart

**Comment by StavrevaS** [comment]
Hello @uspecht,

we found that the intended functionality you have described for the VMWare controller is a good extension for the IaaS scenarios OSCM can support. 

Since the OSCM is an open source project with enterprise quality,  we want to do additional work for the VMWare controller, like internationalization(OSCM supports different locales, English, German, Japanese and is extensible), more integration tests to ensure quality, etc.
Therefore a new [Issue](https://github.com/servicecatalog/development/issues/23) is raised by @mdehn.

Can you say in which business domain you plan to use OSCM with VMware controller?

Do you already know the [OSCM Forum](http://openservicecatalogmanager.org/ui/forums/)? You are welcome to register and share your questions and ideas.
