### ISSUE TITLE
[PT]The marketplace is not available by a specific operation

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#301]
[Summary]
The marketplace is not available by a specific operation.

[Product name and version]
V16.1 GA2

[Client IDE]
OS       : Windows7 Pro SP1
Browser  : IE11

[Reproduce frequency]
always

[Bug Classification]
Short Name:PB-InvFun
Fundamental Function:Yes
Workaround:Yes
Severity:Major

[How to reproduce]
1. Create marketplace.
2. Go to the "Manage access"
3. "Authorized customers only" is checked.
4. Go to the "Create organization"
5. Create customer1 and apply the marketplace of No.2
6. Access the marketplace by customer1. 
7. Create customer2 and apply the marketplace of No.2
8. Accesses the marketplace by customer2. 

[Expected result]
The marketplace is available.

[Observed result]
The error of not enough authorities is showed after login.
[Detail]

If 2 customer is registered continuously, the marketplace is not  available by 2nd customer.
Please check the cause of the issue.

[Message and logs]
You do not have sufficient authorities to view the requested page.

**Comment by StavrevaS** [comment]
The marketplace cache which is application scoped bean in the portal application is the reason for this problem. It is refreshed only on saving manage access table, but not by registering customer organization.
Furthermore, if a changes is done not using the portal (e.g web service call, trigger approval), the portal application will not be "aware" of them.
The application scope was chosen to solve performance problems. A quick solution with changing the scope from application to session opens new problems and is not complete solution.

The marketplace cache cannot be avoided, otherwise with each request we have a database access which is not acceptable because of performance degradation.
The solution similar to the configuration cache should be implemented:

- Marketplace cache in backend, not portal application;
- Cache as singleton bean with read locks for reading the cache (set them explicitly as annotation, because without it the default is write lock);
- Refresh the cache by manage access to marketplaces, register organization (there are more register methods in accounting service - customer, known customer, organization) and check if there are other cases; Check web services and triggers - which methods are called.
- Refresh the cache also periodically (e.g 10 min) to support server-farm scenario. If the organization is registered on one node, the other node will receive the info with delay, but this is acceptable.

**Comment by MiethanerR** [comment]
Merged fix into master. I implemented suzanas solution and moved the cache to the backend. It is also cleared every 10 min.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/24 verified login, triggers, command line, timer
