### ISSUE TITLE
[PT]The error happens when the link of vSphere Cluster Settings in VMware Service Controller is clicked. 

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#302]
[Summary]
The error happens when the link of vSphere Cluster Settings in VMware Service Controller is clicked.

[Product name and version]
V16.1 GA2

[Client IDE]
OS       : Windows7 Pro SP1
Browser  : Google Chrome(52.0.2743.116 m)

[Reproduce frequency]
always

[Bug Classification]
Short Name:PB-InvFun
Fundamental Function:No
Workaround:No
Severity:Minor

[How to reproduce]
1. Login to VMware Service Controller
2. Click "vSphere Cluster Settings" link

[Expected result]
The result is showed correctly.
[Observed result]
The error happens. 
[Detail]
The error happens when the link of vSphere Cluster Settings in VMware Service Controller is clicked.
However we don’t understand how it works. The specification is not described in manual.
Is the link necessary to setup VMware?

[Message and logs]
APP VMware Controller Configuration

The following error occurred during the last operation:
Status Code: 500
Request-URI: /oscm-app-vmware/vcenter.xhtml
Servlet name: Faces Servlet
Exception: javax.servlet.ServletException

**Comment by SylviaDehn** [comment]
same as https://github.com/servicecatalog/development/issues/244
