### ISSUE TITLE
Command line tool, creating organzation - org.properties file and documentation operation.pdf incorrect

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#305]
[Version]
16.1 GA3, 2016/08/23

[How to reproduce]
1. unzip oscm-operatorclient.zip
2. set up command line tool as described in Operation.pdf
3. fill out org.properties file with the goal to creating a customer organization

[Expected result]
Correct fields in org.properties;
Correct documentation 

[Observed result]
org.properties has mandatory parameter "organization.marketplaceid="
documenation is incorrect for this parameter, and for salutation parameter.
user.additionalname seems to be no longer in use (but I'm not sure about this).

[Detatils]
- specifying "organization.marketplaceid=<orgid>" results in error Please specify mandatory parameter marketplaceid."
This parameter should be "marketplaceid" (without a prefix).
This should be fixed in file and  documentation.

- specifying "Mr." or "Ms." for as value for user.salutation as stated in documentation will result in no error, but the salutation is missing in the resulting Customer (any user).  Documentation should be changed to "MR" and "MS"

- specifying user.additionalname=MyOtherName will result in no error, and the platformuser entry added to table has this column with this value after command is executed. But what is this additional name? I cannot find it anywhere in the UI. Either I am missing something, or it is no longer used. In this case I would prefer it if the parameter was not in org.properties and not documented.

**Comment by StavrevaS** [comment]
All comments from @SylviaDehn are right. 
About the user.additionalname: it is used as mapped name for LDAP users, so it should stay and may be described like this.
@gertipoppel, please adapt the Operation.pdf. I will change the setting about marketplace in org.properties.

**Comment by gertipoppel** [comment]
Fixed the Operation.pdf as requested. Manually started docu build (2016-10-06)
