### ISSUE TITLE
Integrationhelper.jar requires additonal jar file "commons-lang3-3.4.jar"

### ISSUE THREAD

**Issue by SchneiderW** [servicecatalog/development#308]
I have a simple Java WebApplication integrated with OSCM 16.0 using "integrationhelper.jar". The application is deployed on tomcat6 and runs fine as s service.  

Using 16.1 GA3, an exception is thrown during runtime:
class not found: org.apache.commons.lang3.*

This can be solved by adding the Apache jar file:
commons-lang3-3.4.jar

Shouldn't the additional jar file be part of any oscm jar file?

**Comment by StavrevaS** [comment]
The dependency to the library is removed. Instead Java string methods are used.
