### ISSUE TITLE
CI environment on docker

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#31]
I as developer would like to have CI environment set up with the docker, instead of building environment from scratch using build scripts, to execute all the tests faster.

**Comment by DawidCh** [comment]
... and in parallel.

**Comment by StavrevaS** [comment]
I am not sure if we can have benefit here. First of all, if you run tests in parallel with more docker containers on your developer machine, I assume that the resources of that machine will be soon exhausted. So you cannot do your developer tasks.  If you plan to also develop on the docker container, it must have access to the network (Internet and internal). And you have to be careful to save the image updates, otherwise you will lose your work.

**Comment by DawidCh** [comment]
I meant to have docker containers used for testing purposes only. Currently our CI builds environment around 30 minutes. We can the time by downloading docker image and run the tests against the container.

**Comment by DawidCh** [comment]
@digitalfishpond finish configuration for shippable, as agreed.

For consideration: create jenkins job which will do following sequence:
1. BuildALL
2. Run unit tests and it tests.
3. Build docker image (use curently created job as template)
4. Run ws and web tests against the image
5. Push image to dockerhub.
The procedure above should take less time and jenkins resources than our current process.

Prerequisits list:
- get knowledge about running docker image under jenkins
- expose email client port from docker image to be reachable from web and ws tests
Post build action:
- gather all tests results (unit, it, ws and web)

**Comment by digitalfishpond** [comment]
[DoD]

Job #1
Git pull
Build enterprise version
Run Unit tests
Run Integration tests
Build docker image and publish on Artifactory

Job #2 
Pull docker image from Artifcatory
Run selenium
Option to build image again, so run #1 again

Job #3 
Pull docker image from Artifcatory
Run webservice tests
Option to build image again, so run #1 again

Job #4
Pull docker image from Artifcatory
Run Canoo tests
Option to build image again, so run #1 again

Job #5 
pipeline to run them all

**Comment by digitalfishpond** [comment]
So far, implemented on branch 'fb_web_integration_tests', and in Jenkins (jobs on the tab: 'CD on  Docker') the following have been implemented:
- pull project from Git hub and Git lab
- build enterprise version
- run Unit Tests
- run Integration Tests
- build Docker Image
- publish resulting docker image on Artifactory
- run selenium tests

Remains to be done:
- (successfully) run webservice tests
- (successfully) run canoo tests
