### ISSUE TITLE
Networks - support global IP addresses

### ISSUE THREAD

**Issue by mdehn** [servicecatalog/development#317]
Allow global IP addresses for all the supported IaaS controllers:
- AWS controller
- OpenStack controller (incl. K5 controller)

**Comment by HerbertNick** [comment]
Needs to include the K5 and Azure Controller.

**Comment by HerbertNick** [comment]
This feature should be accessible via APIs and the GUI

**Comment by HerbertNick** [comment]
The public & private IP should be returned after provisioning

**Comment by HerbertNick** [comment]
The user should have the choice if a public IP is required or not

**Comment by HerbertNick** [comment]
Support situations where IP addressing changes, either dynamically or through a relaunch of a VM.  i.e. always ensure that FCSM knows what IP address is assigned to each resource

**Comment by HerbertNick** [comment]
Support public IP address reservations

**Comment by mdehn** [comment]
The support for global IP addresses can be done for the AWS and the OpenStack controllers.
A K5 controller is not yet part of OSCM, but it is planned for release 16.2.
An Azure controller is not part of OSCM, but you are free to contribute such a controller.
