### ISSUE TITLE
Networks - support subnets: area/dommain/DMZ/VLAN

### ISSUE THREAD

**Issue by mdehn** [servicecatalog/development#318]
Support subnets like area/dommain/DMZ/VLAN for all the supported IaaS controllers:
-     AWS controller
-     OpenStack controller (incl. K5 controller)

**Comment by HerbertNick** [comment]
Needs to include Azure ARM and K5

**Comment by HerbertNick** [comment]
This feature should be accessible via APIs and the GUI

**Comment by HerbertNick** [comment]
![](https://www.rightscale.com/blog/sites/default/files/EC2%20networking.png)

**Comment by uspecht** [comment]
I think security groups are handled in #319. Or is there a subnet related feature of this?

**Comment by uspecht** [comment]
Sorry I was wrong. Subnets are attached to security groups.

**Comment by mdehn** [comment]
The support for global IP addresses can be done for the AWS and the OpenStack controllers.
A K5 controller is not yet part of OSCM, but it is planned for release 16.2.
An Azure controller is not part of OSCM, but you are free to contribute such a controller.
