### ISSUE TITLE
Trying to build the OSCM source code without proxy setting

### ISSUE THREAD

**Issue by pujarisat** [servicecatalog/development#325]
Hi Team ,

I am trying to build the OSCM source code and I don’t have proxy setting at my local environment .  while running the AAL.BUILD target of  “build-dev-PackageDeploy.xml” file(ant build) ,getting below error in the console.

D:\Git\development\oscm-devruntime\javares\devscripts\build-dev-PackageDeploy.xml:154: Can't assign value '${http.proxyPort}' to attribute proxyport, reason: class java.lang.NumberFormatException with message 'For input string: "${http.proxyPort}"'

Could you please help me.

**Comment by GoebelL** [comment]
Hi @pujarisat 

It seems that there is a dependency on HTTP proxy configuration. In fact the proxy usage needs to be optional. The build triggers ivy to fetch libraries from the internet. It won't be applicable for directly internet connections, in case the setting is mandatory. If it's like that, it should be fixed quickly.

@redmond2683 
Please check if this setting and adapt it for optional usage if required.

**Comment by pujarisat** [comment]
Hi Team,

I have set the proxy setting as below in ant properties in eclipse  , however I am getting other issue . please find the below console log

Proxy setting  :

http.proxyPort 8080
http.proxyHost  proxy

Console log : 

uildfile: D:\Git\development\oscm-devruntime\javares\devscripts\build-dev-PackageDeploy.xml
     [echo] Loading integration.properties from D:\Git\development\oscm-devruntime\javares\devscripts/../local/FCP-18224-D/integration.properties
All.BUILD:
ivyBuild:
     [copy] Copying 1 file to D:\Git\development\oscm-devruntime\javares\devscripts
resolve:

BUILD FAILED
D:\Git\development\oscm-devruntime\javares\devscripts\build-dev-PackageDeploy.xml:155: The following error occurred while executing this line:
D:\Git\development\oscm-devruntime\javares\devscripts\ivy-build.xml:9: The following error occurred while executing this line:
D:\Git\development\oscm-build\ivy-build.xml:9: Problem: failed to create task or type antlib:org.apache.ivy.ant:settings
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
No types or tasks have been defined in this namespace yet

This appears to be an antlib declaration. 
Action: Check that the implementing library exists in one of:
        -C:\prg\eclipse\plugins\org.apache.ant_1.9.6.v201510161327\lib
        -C:\Users\pujarisat\.ant\lib
        -a directory added on the command line with the -lib argument

Total time: 317 milliseconds

**Comment by DawidCh** [comment]
Hi.
In eclipse you should set the options with -Dhttp.proxyPort=8080 and -Dhttp.proxyHost=proxy switch in 'External tool configuration' menu. If you set some servers which does not exists it will fail. Does 'proxy' from your config is server which is routable from your machine?
Regards, Dawid.

**Comment by GoebelL** [comment]
Hi all,

as discussed, It should better be possible to run the build with omitting the setting. Red has already enhanced the script making the proxy optional. 
@redmond2683 
please comment your fix here.
@pujarisat 
Please update.

Regards, Lorenz

**Comment by redmond2683** [comment]
408a41150dfadb843bedaa2e57b29e0051374ccf makes proxy settings optional
