### ISSUE TITLE
Eclipse compiler error  after successfully  build the  All.Build target of “bulid-dev-PackageDeploye.xml” (ant file)

### ISSUE THREAD

**Issue by pujarisat** [servicecatalog/development#327]
Hi Team,

I have successfully done All.build target however in eclips project show same error message and below are page are not found error  

import javax.annotation.security.DeclareRoles;
import javax.annotation.security.RolesAllowed;
import javax.ejb.EJB;
import javax.ejb.Local;
import javax.ejb.Remote;
import javax.ejb.SessionContext;
import javax.ejb.Stateless;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.inject.Inject;
import javax.interceptor.Interceptors;
import javax.persistence.NoResultException;
import javax.persistence.Query; 

please find the below screen for same
![image](https://cloud.githubusercontent.com/assets/22190140/18702335/e2dbdfa0-7ffe-11e6-86bb-432031c5d69d.png)

**Comment by pujarisat** [comment]
Hi Team,

Do you have any update?

**Comment by DawidCh** [comment]
Hi.
It works for us. There must be misconfiguration on your environment. The jar with jee libraries is not found by your ecplise.
Regards, Dawid.

**Comment by uspecht** [comment]
I think it is not correct. It looks like the underlying dependencies are not found. This seems to be strange behaviour in eclipse, because the projects are already imported, and the classpath is resolved after the ivy targets.
Could you try closing and opening all projects as work around? It helped for me.
