### ISSUE TITLE
STANDALONE.setup target issue.

### ISSUE THREAD

**Issue by pujarisat** [servicecatalog/development#328]
Hi Team,

I am trying to run the STANDALONE.setup target from /oscm-integrationtests-setup/build.xml. however I am getting below error in console 

Console Error

verifySettings:

configSteps:

SETUP.Single:
        [echo] asadmin --user admin --passwordfile C:\Users\PUJARI~1\AppData\Local\Temp\BES\script981964363.txt create-domain
        [exec] The system cannot find the path specified.

BUILD FAILED
D:\Git\development\oscm-integrationtests-setup\resources\build.xml:105: The following error occurred while executing this line:
D:\Git\development\oscm-integrationtests-setup\resources\build-integration-setup.xml:166: The following error occurred while executing this line:
D:\Git\development\oscm-integrationtests-setup\resources\build-integration-setup.xml:176: The following error occurred while executing this line:
D:\Git\development\oscm-integrationtests-setup\resources\build-integration-setup.xml:210: The following error occurred while executing this line:
D:\Git\development\oscm-integrationtests-setup\resources\work\oscm-install-pack\install\build-glassfish.xml:30: The following error occurred while executing this line:
D:\Git\development\oscm-integrationtests-setup\resources\work\oscm-install-pack\install\build-glassfish.xml:43: The following error occurred while executing this line:
D:\Git\development\oscm-integrationtests-setup\resources\work\oscm-install-pack\install\build-glassfish.xml:72: The following error occurred while executing this line:
D:\Git\development\oscm-integrationtests-setup\resources\work\oscm-install-pack\install\macrodefs-glassfish.xml:824: The following error occurred while executing this line:
D:\Git\development\oscm-integrationtests-setup\resources\work\oscm-install-pack\install\macrodefs-glassfish.xml:668: exec returned: 1

Total time: 2 minutes 39 seconds

please find the below screen

![image](https://cloud.githubusercontent.com/assets/22190140/18709391/848437da-801d-11e6-9997-76677c827299.png)

**Comment by DawidCh** [comment]
Try target Standalone.setupWithoutCoverage.

**Comment by pujarisat** [comment]
Hi @DawidCh  ,

I have run the  Standalone.setupWithoutCoverage  target however I am getting the same error 

Error :
verifySettings:

configSteps:

SETUP.Single:
        [echo] asadmin --user admin --passwordfile C:\Users\PUJARI~1\AppData\Local\Temp\BES\script428183037.txt create-domain
        [exec] The system cannot find the path specified.

BUILD FAILED
D:\Git\development\oscm-integrationtests-setup\resources\build.xml:116: The following error occurred while executing this line:
D:\Git\development\oscm-integrationtests-setup\resources\build-integration-setup.xml:176: The following error occurred while executing this line:
D:\Git\development\oscm-integrationtests-setup\resources\build-integration-setup.xml:210: The following error occurred while executing this line:
D:\Git\development\oscm-integrationtests-setup\resources\work\oscm-install-pack\install\build-glassfish.xml:30: The following error occurred while executing this line:
D:\Git\development\oscm-integrationtests-setup\resources\work\oscm-install-pack\install\build-glassfish.xml:43: The following error occurred while executing this line:
D:\Git\development\oscm-integrationtests-setup\resources\work\oscm-install-pack\install\build-glassfish.xml:72: The following error occurred while executing this line:
D:\Git\development\oscm-integrationtests-setup\resources\work\oscm-install-pack\install\macrodefs-glassfish.xml:824: The following error occurred while executing this line:
D:\Git\development\oscm-integrationtests-setup\resources\work\oscm-install-pack\install\macrodefs-glassfish.xml:668: exec returned: 1

Total time: 2 minutes 35 seconds 

![image](https://cloud.githubusercontent.com/assets/22190140/18711304/e7ea09d6-8026-11e6-84ca-d1fa2270e091.png)

**Comment by DawidCh** [comment]
Do you have glassfish home property set correctly?

**Comment by pujarisat** [comment]
Hi DawidCh,

Yes, it’s seen I have configured correctly. Kindly find the below screen for the same .  
![image](https://cloud.githubusercontent.com/assets/22190140/18711675/a975bd9c-8028-11e6-9495-b34391f46bfe.png)
-Thanks 
Satling

**Comment by DawidCh** [comment]
Set verbose level in ant, to see what file is missing. Clearly some file cannot be found.

**Comment by pujarisat** [comment]
Hi Team,

Issue has been resolved by applying below solution 

There is space in jdk path in asenv.bat
