### ISSUE TITLE
How to update the jar file in project 

### ISSUE THREAD

**Issue by pujarisat** [servicecatalog/development#332]
Hi Team,

Currently oscm-app-aws project have a aws-java-sdk-1.5.2.jar file and I want to update this jar file .

As per the current requirement we want to update  the aws-java-sdk-1.5.2.jar verion to aws-java-sdk-1.8.10.1.jar verion

Could you please help or suggest 

-Thanks 
Satling

**Comment by GoebelL** [comment]
Hi,

generally speaking, when introducing new libraries we need to check the compliance with OSCM license, which is Apache 2.0. The new version here is available with same license from same repository and as the existing one. Therefore I don't see any problem with integrating this in OSCM. 

The existing library is used in the AWS adapter only, which is the one you are working on. I suggest, you try upgrading the library version and see if things are still working as expected. Take care of adapting the ivy scripts, classpath and package.properties files where needed.

Once we merge the respective contribution to OSCM, we will take for listing this version in the notice file.

**Comment by StavrevaS** [comment]
From license point of view, updating to a newer version is not a problem. The license is Apache 2.0.
However both SDKs support different AWS EC2 API versions:

- aws-java-sdk-1.5.2.jar      - API version 01-02-2013
- aws-java-sdk-1.8.10.1.jar - API version 15-06-2014

@uspecht or @skulle, can you check if such change can affect existing installations?

**Comment by uspecht** [comment]
I don't see problems in update scenarios.
However, why don't upgrade to most current version? I would recommend to take 1.11.37.

**Comment by StavrevaS** [comment]
Please take the newest version 1.11.37 and adapt the AWS controller.
