### ISSUE TITLE
SAML login redirect doesn't work

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#333]
Originally reported from @wangyingfnst 
[version]
16.1.1

[build]
2016-09-23 (delivered preview)

[detail]
Deploying the latest version from feature branch we cannot login.
When we access to the login URL of OSCM manually: http://.../oscm-portal, the page cannot redirect to http://.../openam/SSORedirect/metaAlias/idp there is no response and the page stays blank. 
There are no logs in OSCM, including master_index_server.log,bes_server.log, ex_server.log and sts_server.log, thus we have no idea to investigate this issue.
From 16.1.1 master branch it works.

**Comment by DawidCh** [comment]
Could you please tell me which exactly build has been taken for testing?

**Comment by GoebelL** [comment]
>Could you please tell me which exactly build has been taken for testing? 

I have provided them the delivery build created from your feature branch at 2016-09-22 20:34:16 (MULTITENANCY_DELIVERY-19-20160922214628)

>What DB version you have?

If they have upgraded 16.1 to the current version of above, they have upgraded 
schema version 2.9.3 to 2.9.4. @wangyingfnst, please confirm.

**Comment by DawidCh** [comment]
Tip: check bes system log file also. The exception may be hidden there as well.

**Comment by wangyingfnst** [comment]
Hi @DawidCh , I checked the tomcat and found it was already running.
I re-installed the 16.1-fix1_Multitenancy-Preview, after installing, I didn't do any operations, just to check the logs in all domains, which I will attach and email to you, then I try to access to : http://adv1-bss-win.bestesting.com:8080/oscm-portal, after that, I also checked the logs, but no additional contents output there compared to the logs when after installing.

**Comment by GoebelL** [comment]
@DawidCh 
I understand, you have found the cause of this issue and corrected it. Please give a fix comment and close this issue with respective label.

**Comment by DawidCh** [comment]
[Details of fix]
The tenant management module was missing from application-sts descriptor. Because of that module has not been found and endpoints for tenants have not been deployed.
