### ISSUE TITLE
Tenant specific certificates

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#337]
Tenant specific certificates should be imported to glassfish keystore. There should not be tenant specific keystore. Remove password to glassfish keystore from tenant settings and use it from configuration settings.

**Comment by StavrevaS** [comment]
The following settings are the same for all tenants and should be read from the configuration settings:

- SSO_SIGNING_KEY_ALIAS
- SSO_SIGNING_KEYSTORE
- SSO_SIGNING_KEYSTORE_PASS

The OSCM uses the same key for signing the logout requests for all tenants. Each tenant should import the OSCM certificate for signature verification of the logout requests.

**Comment by DawidCh** [comment]
The issue has been fixed within the commit https://github.com/servicecatalog/development/pull/310/commits/68d8d800f084803220068de797f3f23e7e180ac8
The properties mentioned above are taken now from configuration settings. They are not tenant specific.
