### ISSUE TITLE
SAML login response scam

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#342]
There is possibility to act as different tenant. OSCM should require login response signing and verify the signature of SAML envelope.

**Comment by StavrevaS** [comment]
By validating the SAML Assertion, the OSCM must verify that the SAML Assertion is in response to the same tenant, which issues the SAML Authentication request.

The verification here, can be similar to that of the SAML request ID.

More details will follow.

**Comment by GoebelL** [comment]
This proposal is fine. Please implement this solution for the next release.

**Comment by DawidCh** [comment]
The issue has been fixed within the commit https://github.com/servicecatalog/development/pull/310/commits/68d8d800f084803220068de797f3f23e7e180ac8
Adding tenantID parameter to saml assertion consumer was cause of not sending the post part of request. I was only retrieving get attributes without saml envelope. Instead tenantID is send as assertion defined in assertion attributes in IDP. Rest of the solution is as proposed.
