### ISSUE TITLE
SAML Assertion Issuer is not validated in OSCM

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#344]
During the code analysis for multitenancy feature, I found that the issuer id in the SAML Assertion is not validated. This must be fixed.

This issuer id must be configured in the platform like other SSO configuration settings. We need only setting for IDP for web browser SSO, since the SAML Assertion validation for Web Service calls is done by glassfish Metro. The same is valid for the tenant-specific settings.

The name of the setting could be "SSO_IDP_SAML_ASSERTION_ISSUER_ID".

The ADFS endpoint to see the issuer ID is the following:
<adfshost>/FederationMetadata/2007-06/FederationMetadata.xml

In the metadata xml the issuer id is known as entityID, e.g entityID="http://example.adfs.com/adfs/services/trust"

**Comment by StavrevaS** [comment]
This is an old bug, it is not introduced with the multitenancy feature development. But it is important to fix it for that feature.

**Comment by GoebelL** [comment]
Please don't forget about existing installations -> migration and default value?
In any case....

@SuessI
This new setting will require documentation when done.

**Comment by SuessI** [comment]
@gertipoppel  - please take care of the doc

**Comment by DawidCh** [comment]
[Details of fix]
New property in configuration settings, as well as in tenant settings, has been introduced. In filter which awaits saml response new code has been added which tests if issuer id from saml envelope is corelated with settings from DB for selected tenant.

**Comment by StavrevaS** [comment]
I reopen this bug, since it seems it is not understood. The solution does not correspond to the described problem. The solution is about comparing the requesting tenant and the tenant form response.
Please read the issue carefully.

**Comment by DawidCh** [comment]
The issue has been read carefully.
In saml assertion the content of   <saml2:Issuer>xxxx</saml2:Issuer> is being verified.
Could you please review the test and code which it covers: [SAMLResponseExtractorTest.java](https://github.com/servicecatalog/development/blob/master/oscm-saml2-api-unittests/javasrc/org/oscm/saml2/api/SAMLResponseExtractorTest.java#L132)
Close the issue, please,  if you agree if this is what you wanted.

**Comment by StavrevaS** [comment]
I have reviewed the following [commit](https://github.com/servicecatalog/development/commit/0a5a7a6eae243da92bcdd704e23096015f851a41) which fixes this issue. Yes, you are right, the issuer is validated. I will comment the commit, please read it. The issue should stay opened, till we resolve the commit comments.

**Comment by StavrevaS** [comment]
I will close this issue, since the functionality is OK. Refactoring will be done independently for 16.1.2
