### ISSUE TITLE
Issue while  download  the aws-java-sdk-1.11.37.jar using ivy.xml in OSCM AWS controller

### ISSUE THREAD

**Issue by pujarisat** [servicecatalog/development#345]
Hi Team,

I am trying to download  the aws-java-sdk-1.11.37.jar using ivy.xml and this file is downloaded successfully , however downloaded  aws-java-sdk-1.11.37.jar file contains only pom.xml and pom.properties file. There is no classes and artifacts in that file

To run the OSCM AWS controller we need to some classes must be present in the aws-java-sdk-1.11.37.jar file.

Could you please help me to integrate aws-java-sdk-1.11.37.jar file in the OSCM AWS Controller projects .

It would be great if we have call on this.

Please find the below screen of aws-java-sdk-1.11.37.jar file 
![image](https://cloud.githubusercontent.com/assets/22190140/18984185/a98c30f8-870e-11e6-95a5-76b888c09c6d.png)

-Thanks 
Satling

**Comment by StavrevaS** [comment]
Hello @pujarisat,

it seems that the AWS jdk does not contain classes any more, just dependencies to other jars. There is a possibility to fix this using ivy (to automatically download the dependent jars), but unfortunately we must have control over the downloaded versions of the jars. Please try to use the existing logic in the ivy scripts and add the necessary dependent jar files.
