### ISSUE TITLE
Impossible to create new organization for specific tenant when user id already exists for default tenant 

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/development#347]
[Steps to reproduce]
1. Login as a Platform Operator
2. Create an organization with user id: test_user with no tenant specified
3. Add new tenant
3. Create an organization with user id: test_user with tenant from step 3 specified

[Expected result]
Organization should be created as existing user id is used in the context of new tenant,

There is a problem in validateBusinessKeyUniqness method in DataService invoked for PlatformUser. 

Error exists only in case user is first created without specified tenant.
Similar cases (in admin and marketplace portal where user can be created) must be checked.

**Comment by DawidCh** [comment]
[Details of fix]
New method for persisting users within tenant context has been added in dataservice. The method checks if user exists for particular tenant. It is being called only when system is in saml_sp mode.

**Comment by StavrevaS** [comment]
The organization can be created now, but there is an error message when the organization admin with the same id tries to login: "Login failed. The specified user ID does not exist in Catalog Manager."
I have the following test scenario:
1. There is a user "Winston@adfs.com" in a supplier org. "A" which belongs to the default tenant;
2. The platform operator creates another supplier organization "B" with "Winston@adfs.com" as org.admin and assigns it to a tenant with ID=a37440ff; - OK
3. The organization admin "Winston@adfs.com" from "B" is redirected to the tenant-specific IDP - OK;
4. It logs in and the error is displayed.

Server.log:
Reason: EXCEPTIONID 1476711319066: Found incorrect recipient for assertion id=_fa527586-e132-4b09-aaa2-2dde84c6cbbb, expected is http://<host>:8180/oscm-portal/ or https://<host>:8181/oscm-portal/, but was https://<host>:8181/oscm-portal/?tenantID=a37440ff.

The SAML Assertion has the correct tenantID as attribute:
 <AttributeStatement>
      <Attribute Name="userid">
        <AttributeValue>Winston@adfs.com</AttributeValue>
      </Attribute>
      <Attribute Name="tenantID">
        <AttributeValue>a37440ff</AttributeValue>
      </Attribute>
    </AttributeStatement>


For me it seems that we have a problem by recipient validation. The security module initializes the assertion consumer service without tenant context. The tenant ID is already available to the security module via the password parameter. It should be not a big problem to fix.

**Comment by DawidCh** [comment]
I think there is a problem with the attribute. Could you please remove attribute tenantID from the 'response' address in adfs and add tenantID in assertion attributes instead?

**Comment by StavrevaS** [comment]
I've tested with suggested change, the login and logout works.  However it allowing the tenant to specify OSCM base url as SAML Assertion consumer endpoint may have some security implications. This will be reported as another issue.
