### ISSUE TITLE
properties file values are not stripped of blanks  during installation 

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#354]
[Version]
16.1 GA3, 2016/08/23

[How to reproduce]
1. fill out <install-dir>/databases\bes_db\configsettings.properties
2. for one value
SSO_LOGOUT_URL=http://estsdehn:8080/openam/IDPSloRedirect/metaAlias/idp
add a blank after "idp"
3. run 
ant -f build-db.xml initDB

[Expected result]
Creation and installation is successful

[Observed result]
An error is displayed that the format of the URL SSO_LOGOUT_URL is incorrect.

[Details]
Since it took me at least 15 mins to figure out that the problem was the blank and not something else, I decided to enter this bug.

**Comment by StavrevaS** [comment]
The following types of configuration settings should have blanks stripped by saving into db:
- boolean;
- URL;
- long;
- password; (this is new type for issue #284 )

Only string types should be left with blanks.

**Comment by MiethanerR** [comment]
I added a trim to the specified fields during config import and config service.

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix4
This works as described for URL
SSO_IDP_SAML_ASSERTION_ISSUER_ID
but not for 
SSO_LOGOUT_URL as described in original issue.
SSO_STS_METADATA_URL does not work either.
I tested with 
ant -f build-db.xml updateDB 

I presume that this is a similar issue that should be handled with the same routines.

**Comment by MiethanerR** [comment]
Fixed. Added URL to the group of types that get trimmed.
