### ISSUE TITLE
API getAccessibleMarketplaces

### ISSUE THREAD

**Issue by uspecht** [servicecatalog/development#358]
In many cases to subscribe to services or show services via API it is necessary first to list all accessible marketplaces for this customer.
As far as I know this already exits, but is restricted to the operator.

**Comment by StavrevaS** [comment]
Yes, this functionality is restricted to platform operator. It is not a part of the Platform API.

**Comment by mdehn** [comment]
Yes, currently there are no plans to extend the SOAP API, nevertheless contributions are always welcome.
