### ISSUE TITLE
SSO_IDP_SAML_ASSERTION_ISSUER_ID should be editable

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#366]
It is not guaranteed that, the OSCM operator have the possibility to change the Issuer in the IDP. 
So this setting should be editable on UI.

The setting is only required for SAML_SP authentication mode, so it cannot be mandatory.

**Comment by StavrevaS** [comment]
The setting SSO_DEFAULT_TENANT_ID should also be not mandatory (only SAML_SP mode requires it)

**Comment by StavrevaS** [comment]
@gertipoppel, please adapt in the documentation after the code is fixed

**Comment by DawidCh** [comment]
The SSO_IDP_SAML_ASSERTION_ISSUER_ID property should be set during installation/upgrade only. When the value will be modified in IDP by IDP_admin then logging in to portal will be impossible. If it will be modified by platform operator in portal, logging in will be impossible. In my opinion it should not be editable. Unless there is some other scenario, which I do not know about.
SSO_DEFAULT_TENANT_ID - ok.

**Comment by StavrevaS** [comment]
We should let the operator possibility to switch the IDP system if needed.  All SSO_IDP settings should be changed then, including the SAML Assetrion Issuer.

**Comment by DawidCh** [comment]
Ok.

**Comment by kowalczyka** [comment]
Can be verified with BES_MASTER_Unit - 1619.
