### ISSUE TITLE
Error message screen when tenant IDP is not configured yet.

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#369]
The error message screen looks not very nice and clicking on ? does not show any information in case the user tries to access the blue portal for a tenant which has no IDP settings yet.

The modal window is also not OK.

![error1](https://cloud.githubusercontent.com/assets/14818282/19436327/b58b3c8c-946f-11e6-8e98-f5e9d834a9a3.PNG)

**Comment by DawidCh** [comment]
In above commit only styling has been added to the dialog. Help page for it is still missing.

**Comment by gertipoppel** [comment]
@DawidCh 
Please provide the help id  - i.e. what must be the name of the HTML file that is to be opened when clicking the ? sign.

**Comment by gertipoppel** [comment]
@misako0927 
I added a help topic: tasks/error_generating_authnrequest.xml file.
Please translate this file and then close this issue. Thank you.

**Comment by redmond2683** [comment]
Done for Japanese.
