### ISSUE TITLE
Tenant in the selection lists should be represented with the name, not ID

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#370]
Displaying the generated tenant ID in the selection lists (e.g create organization, create marketplace pages) is not very user-friendly. The tenant name should be used instead.
@mdehn what do you think about this?

**Comment by mdehn** [comment]
Yes, please use in the end-user's user interface the tenant name rather than the tenant ID.

**Comment by StavrevaS** [comment]
Please check if the issue can be fixed for 16.1.2

**Comment by kowalczyka** [comment]
In create/update marketplace page we have autocomplete component for selecting the tenant. Should we adapt also selecting the tenant by matching name (now it is matched with id) or only displaying the name here (for example  tenant_id (tenant_name) - like in organization autocomplete component) is enough ?

**Comment by GoebelL** [comment]
The latter option is fine. Despite of less effort, it's better to be consistent with the organization autocomplete component.

**Comment by kowalczyka** [comment]
Can be verified with BES_MASTER_Unit - 1619
