### ISSUE TITLE
Links in registration mails

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#371]
After registering organization, the organization admin receives an email with the link to the portal.
The link is "http" (BASE_URL) which is normally not the case, especially in SAML_SP mode.

It is better to have always both links "http" and "https" in the registration mails, so the user is aware of that. If one link does not work, he will click the other.

If we let only "http" link in the mails, it means that the operator or whoever is responsible for configuring the IDPs, should always configure the SAML Assertion Consumer Endpoint as "http".

Similar case with marketplace link in the registration mails should be checked.

This is bug is an existing bug, it is not introduced with multitenancy feature. But since there will be information exchange between operator and tenants about configuring the IDP, it should be fixed.

**Comment by StavrevaS** [comment]
@mdehn, what is your opinion here about adapting the registration mails?

**Comment by mdehn** [comment]
that is fine for me.

**Comment by GoebelL** [comment]
Basically it sounds fine, but I am not sure if it's applicable. Please check the impact carefully. I think to remember that either HTTP or HTTPS can be used, but mixed access is not supported in OSCM. Further HTTP access can be restricted by omitting the BASE_URL configuration, so that only HTTPS is available.

**Comment by kwodzynski** [comment]
Windows Server 2016, jdk1.8u131, build BES_MASTER_UNIT-1897 2017/07/26 in SAML mode.
When I create new organization for default or non-default tenant and I do not specify any marketplace, I receive wrong value of Secure URL: {3} instead of https link. HTTP link is ok.

**Comment by kwodzynski** [comment]
I also have checked this for new user and new customer. In the both cases I always receive wrong value: Secure URL: {3}, even for customer, although I obligatory have to specify a marketplace (validation).

**Comment by kwodzynski** [comment]
Windows Server 2016, jdk1.8u131, build BES_MASTER_BUILD_NO_TESTS-232017/07/27 in SAML mode.
I have checked for new organizations, customers and users (created from blue portal and from marketplace). In every case I received correct values.

**Comment by kwodzynski** [comment]
Retested on Windows Server 2016, jdk1.8u131, build BES_MASTER_UNIT-1904 2017/07/27 (official 17.3.0) in SAML mode. 
It has been checked for new organizations, customers and users (created from blue portal and from marketplace). The links in the mails are correct.
