### ISSUE TITLE
new saml mode configuration settings should be commented

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#373]
[Build] 
17.10.2016
[Version]
16.1 fix2 pre-release

[How to reproduce]
look at ....databases\bes_db\configsettings.properties

[Expected result]
saml settings are commented because INTERNAL mode is default. (this is the case for existing
values that are saml specific)

[Observed result]
The following settings are NOT a comment (#):

# Default tenant ID used for proper identification default tenant. String has to have length of 8 characters.
SSO_DEFAULT_TENANT_ID=8f96dede 

# IDP issuer ID. Value used for validating if the response is being sent from proper IDP.
SSO_IDP_SAML_ASSERTION_ISSUER_ID=IDP_ID

**Comment by kowalczyka** [comment]
This issue is duplicate of #366 and it will be resolved with it.

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix2 verified
