### ISSUE TITLE
Uniqueness of default tenant ID

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#380]
As platform operator you can modify default tenant id in configuration settings. The check needs to be added to verify if tenant id given by user is unique with the ids which are already set in tenant specific settings.

**Comment by DawidCh** [comment]
Please create pull request for that, just to remember to merge it to master.

**Comment by grubskim** [comment]
[Details of fix] 
Added exception on save action when tenant id value is already present in tenant table.
