### ISSUE TITLE
wrong login to idp shown after login to marketplace is pressed

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#383]
Date:2016/10/20

[Steps to reproduce]
1. IDPs IDP1(used as default), and IDP2 exist
2. administrator (platform) uses IDP1, creates organization Org1 (tech provider and supplier), Org1Admin
and is in IDP2 
3. administrator creates marketplace M1, M2 and owner is set as Org1, and marketplace is in IDP2
4. log in as Org1Admin with http://estsdehn.intern.est.fujitsu.com:8180/oscm-portal/?tenantID=IDP
5. work in portal only and publish a service to M1 (I do not switch to marketplace)
6. log out as Org2Admin
(http redirect is set to http://estsdehn.intern.est.fujitsu.com:8180/oscm-portal/marketplace/index.jsf)
I end up at login page of M1. I do not know why (I expected an error page)(issue1)
7. then I press login to M1  (issue2)

[Expected result]
step 6. issue1: I do not know why I do not see an error page (no cookies were been saved before step 1.)
step 7. issue2: expect to login page of IDP2

[Observed result]
issue1: login page of M1
issue2: got login page of IDP1

**Comment by DawidCh** [comment]
Sylvia, you never entered to marketplace M1 in the browser session?

**Comment by SylviaDehn** [comment]
@DawidCh no, I never entered M1

Issue2 is verified in build 24.10.2016

**Comment by GoebelL** [comment]
>[Observed result]
>issue1: login page of M1
>issue2: got login page of IDP1

[Details of fix]
Issue1 is minor and could not be reproduced by developer yet.
Severe Issue2 has been fixed and verified.

**Comment by DawidCh** [comment]
@SylviaDehn I have question: what option do you have set in configurationsetting under the key: MP_ERROR_REDIRECT_HTTPS. Is there (I hope) M1 address?

**Comment by StavrevaS** [comment]
@SylviaDehn can you check and close if the solution is acceptable?

**Comment by DawidCh** [comment]
The bug is not reproducible.
