### ISSUE TITLE
No validation of property file for IdP connection

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#384]
[Version]
V16.2 

[Date]
2016/10/19

[Test category] 
Creative

[Description]
I can import an empty file (or with invalid content). There is not consistency check or parameter validation.  

[Steps to reproduce]
Add new Tenant, press save
import IdP connection file. 

[Expected result]
Proper error handling and messages if the content is not correct
[Observed result] 
The file is read, depending on the content no error is thrown 
[Details]
See above; 

[Messages and logs]
attached a sample file which throws no error, even if the content is marked as comment with #.
[Rock.properties.txt](https://github.com/servicecatalog/development/files/541342/Rock.properties.txt)

**Comment by badziakp** [comment]
It was made that way on purpose because 'Operation > Manage LDAP settings' works the same. Could you tell me if these two option should work consistently or maybe 'Operation > Manage LDAP settings' should also be fixed?

**Comment by StavrevaS** [comment]
The settings for the tenant-specific IDP can be empty, in that case the default tenant IPD is used for authentication.
In case some settings in the property file are commented out, they should be skipped by import. That is how the import of configuration settings is working and we should be consistent in that case. The OSCM behavior is correct in this case. 
However we should avoid writing any string in the database using this file. It should be validated if the specified settings are the expected ones, and also we should validate the completeness. 

As a usability improvement, maybe we can let exporting the file with settings keys, but with empty values. In that case, the platform operator would have all the necessary settings without consulting any documentation. @mdehn please decide.

@DawidCh please test or describe shortly here what kind of validation is implemented if any, so we can decide how to proceed with this issue.

**Comment by DawidCh** [comment]
> The settings for the tenant-specific IDP can be empty, in that case the default tenant IPD is used for 

> authentication.

I'm afraid it is not like this. If the tenant exists then only his settings are taken into consideration. Exception is being thrown if any of options are missing (if I finish issue #372)

**Comment by badziakp** [comment]
Only the validatation of settings keys is implemented, the same as on 'Manage LDAP settings'.

**Comment by mdehn** [comment]
The usability improvement suggested above by [StavrevaS ](https://github.com/StavrevaS) above is fine.

**Comment by StavrevaS** [comment]
@DawidCh about your comment. The default tenant settings should be fallback in case the tenant has no own IDP defined. But for this release is fine as it is. This can be fixed later.

**Comment by DawidCh** [comment]
It will not work. When I will call portal with tenantID="1" (and default tenant id is "2"), and there is no settings for IDP for this tenant portal will call default IDP. Even if I log in to the default tenant, SAML envelope from default tenant IDP will contain default tenant ID, which is 2. I will get exception in OSCM.
I can of course rework that part, but do we really need that? I can't think about real life scenario.

**Comment by StavrevaS** [comment]
It will not work anyway. If the platform operator wants to configure the same IDP for all tenants, it is not possible with the current SAML Assertion validation logic. It is expected, that the SAML Assertion contains only one tenantID and it is validated. This must be analysed and fixed.

**Comment by DawidCh** [comment]
@StavrevaS 
Just to be on the same page: should system support configuration of multiple tenants on one IDP?

**Comment by StavrevaS** [comment]
@DawidCh you are right. It does not make a lot of sense, since the multi-tenancy feature is introduced to have different IDP systems. Even if the platform operator should configure the same system as IDP, he can define, for example, different relying parties in ADFS. It must be only documented properly.

**Comment by StavrevaS** [comment]
Just to summarize:

@gertipoppel will fix the documentation according to the previous comment.

Code (validation and export functionality):

- Export should be always enabled, in case no IDP configured for the tenant. a file with all setting keys and empty values is exported.
- Validation of the settings - the correctness and completeness of the settings is validated (including logout setting). The valid URL format is also tested for URL settings.

**Comment by gertipoppel** [comment]
I have added the corresponding information to the documentation. 
Modified sources: 
DocSources12/en/InstallationGuide/Preparation/c_AuthenticationMode.xml
DocSources12/en/Shared/reference/c_IdPInfo.xml
DocSources12/en/Shared/reference/c_IdPInfo2.xml
DocSources12/en/InstallationGuide/Update/c_Update.xml
DocSources12/en/help/tasks/marketplace_update.xml
DocSources12/en/help/tasks/operator_manageTenants.xml

@misako0927 The c_IdPInfo.xml, c_IdPInfo2.xml, marketplace_update.xml and operator_manageTenants.xml are part of the online help and need to be updated in Japanese.

**Comment by StavrevaS** [comment]
@misako0927 please close this issue after the japanese translation is done.

**Comment by misako0927** [comment]
I translated it to Japanese.
