### ISSUE TITLE
I get "The entered marketplace URL is not valid" if I click ACCOUNT->Subscriptions

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/development#387]
Customer is logged in on Marketplace
click ACCOUNT->Subscription
a error message is shown
![marketplaceid1](https://cloud.githubusercontent.com/assets/15209605/19559606/e5ccc95c-96d0-11e6-9d75-b892f4e51484.PNG)
![markedplid2](https://cloud.githubusercontent.com/assets/15209605/19559610/ebc701c4-96d0-11e6-869f-6e24c8d52e2e.PNG)
![marketplaceid3](https://cloud.githubusercontent.com/assets/15209605/19559612/f1738e6c-96d0-11e6-9b76-00c4a453699f.PNG)

**Comment by elfriedegoetz** [comment]
I have Installed Internal Mode

**Comment by DawidCh** [comment]
The problem is because you have used estgoetz as machine name while logging in to marketplace but you base_url property in configuration settings is estgoetz.intern.est...
You have to use address which is set as base_url in configuration settings while accessing the application.
