### ISSUE TITLE
Input on configuration tab gets lost after subscribing 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#390]
[version] 
16.1.1

[build] 
~2016-09-26

[Frequency]
Often (happened several times in a demo)

[Steps reproduce]
1. Start subscribing a service with parameters in MP
2. Fill all fields on Configuration page
3. Click next

[Expected result]
Next page

[Observed result]
Stay on same page and all input is gone

**Comment by GoebelL** [comment]
@redmond2683 
Please provide the domain log files for analysis. Check if there is a relation with #105.
Until now we encountered such issue very seldom. The #105 is hard to reproduce and with special conditions. Now this similar issue seems to appear more often. Overall the subscribing process is affected, which is most important for users. Since the occurrence is not seldom I set the priority to P1.

**Comment by redmond2683** [comment]
Actually we encountered this issue during defining service several times. And I could reproduce it with the com.sun.faces.numberOfViewsInSession parameter 1, but nothing was output in server log. Besides, I also tested it with the com.sun.faces.numberOfViewsInSession parameter 15 (default), and I couldn't reproduce it so far.

**Comment by GoebelL** [comment]
@redmond2683, could you fix this please. 
I suspect, a certain number of views per session should be enough to solve this type of issue. This figure needs to be grater 1 but less than the default of 15. Too many views would cause a huge session footprint and impact the current system requirements. To be save here, I suggest to switch the parameter to 4. Please test it.

**Comment by redmond2683** [comment]
I set the parameter to 4, tested it, and it has not been reproduced so far after my doing the same procedure for about 30 minutes.

**Comment by redmond2683** [comment]
I found the exact way to reproduce this.

[version]
16.1.2

[build]
2016-11-09

[Frequency]
Always

[How to reproduce]
1. login to the administration portal as supplier
2. middle-click or left-click with control key any menu item to open link in new tab
3. go to the "Define service" page in the first tab
4. left-click any menu item in the second tab
5. finish defining a service in the first tab

[Expected result]
The service is defined correctly.

[Observed result]
The service is not defined and all information which is filled in on the page is lost.

**Comment by DawidCh** [comment]
Hi.
This is not bug, but configuration of jsf. numberOfViewsInSession and numberOfLogicalViews are set to 1 in web.xml, so operational on multiple tabs is not supported. Try to change the values to 15 each and test again.
Regards, Dawid.

**Comment by GoebelL** [comment]
Please wait. We will handle this issue.
