### ISSUE TITLE
Custom tab name allows blanks

### ISSUE THREAD

**Issue by grubskim** [servicecatalog/development#393]
During defining the new marketable service, the "Custom tab name" allows blank characters. The documentation and specification needs to be changed accordingly. Currently it says that the blanks are not allowed.

**Comment by gertipoppel** [comment]
Corrected the relevant online help topics. 
@misako0927 Please do the same in the Japanese topics
help/tasks/service_add.xml
help/tasks/service_edit.xml

**Comment by GoebelL** [comment]
@misako0927 is working on the custom tabs currently. 
@redmond2683 
Please could you care for the Japanese translations?

**Comment by redmond2683** [comment]
Done for Japanese.
