### ISSUE TITLE
[OpenStack Controller] The status are change to error when user execute start/ stop operation to instances when all instances are already started/stopped.

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#399]
This is not a bug but better to improve the function.

[How to reproduce]
Execute start/stop operation which all instances are already active/shoutoff

[Observed result]
Operation status change to ERROR and return the message "The start of the resources failed."

**Comment by misako0927** [comment]
The reason why this issue happen is OpenStack Controller execute operation without checking instance status. This is specification of start/stop operation which are already discussed.
But this specification is not user friendly because user cannot notice instance status are already expected status.

**Comment by misako0927** [comment]
On the other hand, the error code which is replied from OpenStack/K5 when OpenStack Controller execute this operation in same situation are not in OpenStack/K5 manual. This mean we cannot use this error status for handling this situation.

From the above I propose this specification change to like this:
1. Before execute operation, OpenStack Controller check all instance status
2. If all instance status are already expected status (the status are ACTIVE when start operation is executed and the status are SHUTOFF when stop operation is executed), OpenStack Controller does not execute these operation.
3. OpenStack Controller report ERROR status and the message "VMs are already started" or "VMs are already stopped".

**Comment by misako0927** [comment]
[Detail of fix]
1. Before execute operation, OpenStack Controller check all instance status
2. If all instance status are already expected status (the status are ACTIVE when start operation is executed and the status are SHUTOFF when stop operation is executed), OpenStack Controller does not execute these operation.
3. OpenStack Controller report ERROR status and the message "VMs are already started" or "VMs are already stopped".

**Comment by misako0927** [comment]
@Gerti
Please translate the German messages.

**Comment by gertipoppel** [comment]
Translated to German and closing this issue.
