### ISSUE TITLE
As customer admin of non default IDP, cannot assign roles to new users

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#401]
Date:2016/10/23 (multiple IDPs)

[Steps to reproduce]
1. IDPs IDP1(used as default), and IDP2 exist
2. customer org is assigned to IDP2
3. as customer org admin register new user and assign administrator or subscription manager

[Expected result]
user is created and has correct role

[Observed result]
error is displayed "You are not allowed to perform this operation."

[Details]
The user is actually created but the role assignment fails. 
This makes me believe that the unit tests (all) should be also executed not only for default tenant but also for another tenant other than default.

**Comment by StavrevaS** [comment]
The reason is the same as for #400, with different effect. So I will mark this issue as duplicate to #400.

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix2 verified
