### ISSUE TITLE
wrong units shown for customer user (of non-default idp)

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#402]
Date:2016/10/23 (multiple IDPs)

[Steps to reproduce]
1. IDPs IDP1(used as default), and IDP2 exist
2. customer org is assigned to default IDP, admin has user id "User1"
3. customer org is assigned to IDP2, regular user has user id "User1"
4. as "User1" of IDP2 go to Profile and look at units of user

[Expected result]
see units of "User1" of IDP2

[Observed result]
see units of "User1" of default IDP

**Comment by StavrevaS** [comment]
This issue has the same cause as issue #400, therefore I will set it to duplicate. Nevertheless it can be used as test case after fixing #400.

**Comment by SylviaDehn** [comment]
[build] 16.1 fix2 verified
