### ISSUE TITLE
What tenant to choose during organization creation

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#403]
When I select no tenant (default) while creation of organization I see all the marketplaces (assigned to default or not default).
To which tenant,organization should be assigned in situation when I select no tenant (default) and non-default tenant marketplace (let say marketplaceA)?
My point of view: I need to be in non-default tenant during logging in to marketplaceA, so in DB I would like to have my organization in non-default tenant assigned.
There is always but, how the customers are going to use that? I do not know.
Current implementation is that organization is assigned to the same tenant to which marketplace is assigned.
@mdehn could you please put more light on the problem?

**Comment by StavrevaS** [comment]
I would say that the chosen marketplace must always correspond to the chosen tenant. Otherwise the organization from one tenant will be redirected to the IDP of another tenant.

**Comment by mdehn** [comment]
Yes, that makes sense.
