### ISSUE TITLE
AWS : new service parameter do not follow naming conventions

### ISSUE THREAD

**Issue by SuessI** [servicecatalog/development#404]
Date:2016/10/24 

[Steps to reproduce]
Look at new service parameters of AWS integration:
- diskSize
- publicIP
- subnet

[Expected result]
The names follow the same conventions as the existing ones, i.e. all uppercase and with underscores where necessary, i.e.:
- DISK_SIZE
- PUBLIC_IP
- SUBNET

**Comment by StavrevaS** [comment]
Changes in the service parameter names will require migration in the OSCM database and APP database.

**Comment by StavrevaS** [comment]
@SuessI please adapt the documentation.

**Comment by MiethanerR** [comment]
I adapted the parameters and added a migration.

**Comment by SuessI** [comment]
Adapted the documentation:
- parameter descriptions in AWS Integration manual
- section in release notes (for Enterprise Edition)
