### ISSUE TITLE
operation failed when customer adds user in organization assigned to default IDP

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#405]
Date:2016/10/23 (multiple IDPs)

[Steps to reproduce]
1. IDPs: IDP1(used as default), and IDP2 exist
2. customer org1  is assigned to default IDP, admin has user id "Admin1"
3. customer org2 is assigned to IDP2, regular user has user id "User1"
4. as "Admin1" of IDP go to Users & Units and press "Add User" and create user with id "User1"

[Expected result]
User1 is created

[Observed result]
Operation failed (see attachment with server log)

[Details]
Actually User1 is created, but I cannot update him because then I get an error:
"The data has been modified or deleted in the meantime. Please execute the operation again."
Critical because the new user roles cannot be updated and thus not used. Also Operation failed should
never occur.

**Comment by SylviaDehn** [comment]
[server.log.txt](https://github.com/servicecatalog/development/files/547819/server.log.txt)

**Comment by SylviaDehn** [comment]
It actually does not matter if the user already exists in the non default IDP. The error still occurs.
Also none of the users can be updated.

**Comment by StavrevaS** [comment]
This issue have the same cause as #400, so I will set it to duplicate. Nevertheless, it can be used as test case after fix of #400.

**Comment by elfriedegoetz** [comment]
Date:2016/11/3
verified with 16.1.fix2
