### ISSUE TITLE
Unify account menu links 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#407]
This an improvement request. 

In compare to the buttons on the account index page, the marketplace account menu uses different navigation links for same targets. For example the show button for the profile uses a relative link implemented with a javascript onclick handler, while the Profile link in the account menu uses an absolute URL <BASEURL>/marketplace/account/profile.jsf computed from the configured base URL.
The local links within the marketplace portal should remain relative page links. Please unify the  implementation of links in the marketplace account.

**Comment by misako0927** [comment]
[Detail of fix]
Improve the URL except account menu to use relative path.
