### ISSUE TITLE
self registration at marketplace (associated with non-default IDP) does not work 

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#408]
Date:2016/10/24 (multiple IDPs)

[Steps to reproduce]
1. IDPs IDP1(used as default), and IDP2 exist
   UserX is known in IDP2
2. marketplace M1 is associated with IDP2
3. use marketplace URL to get to M1
4. press "register" fill out info
5. look at mail received and confirm new account

[Expected result]
confirmation is ok, and it is possible to login

[Observed result]
Your account has been activated, but the logging in failed. Please try again.

[Details]
I checked the tables, a user was created in platformuser table, and a new organization was created in organization table. But, the tenantID belonging to the marketplace was not entered in the column tenant_tkey of the organization table. Once I did this (manually), the user can login.
If self-registration is possible in SAML, it should work. If not, the field should be deactivated.

**Comment by gertipoppel** [comment]
The documentation (Installation Guide) states: 
"It is recommended to use the SAML_SP authentication mode if you want to operate CT-MG in a company network and use existing authentication mechanisms that support the SAML 2.0 standard. Customer self-registration is not supported in this case, and should thus be disabled."
