### ISSUE TITLE
Go to marketplace - user can select marketplace from different tenant

### ISSUE THREAD

**Issue by badziakp** [servicecatalog/development#411]
## Steps to reproduce
1. login as Platform Operator
2. create tenant1
3. create organization userId=supplier without selecting any tenant
4. create organization userId=supplier and assign it to the tenant1
5. create marketplace1 for supplier created in step 3. without assigning it to any tenant
6. create marketplace2 for supplier created in step 4, and assign it to the tenant1
7. login as supplier from step 4.
8. cllick Go to marketplace 

[Observed result]
list with marketplaces contains marketplace2(ok) and marketplace1 which was not assigned to any tenant.

[Expected result]
list with marketplaces contains only marketplace2

**Comment by badziakp** [comment]
[Suggested solution]
The method GoToMarketplaceBean.validateMarketplaceTenant has to be extended:

        String mplTenantId = marketplace.getTenantId();

        if (StringUtils.isNotBlank(mplTenantId)) {

            if (mplTenantId.equals(tenantId)) {
                return true;
            }
            return false;
        }
        if (StringUtils.isNotBlank(tenantId)) {
            return false;
        }
        return true;

**Comment by GoebelL** [comment]
Workaround solution: Marketplace owner configures access only for tenant organizations (use closed marketplaces)

**Comment by DawidCh** [comment]
Details of fix
Fix has been implemented as suggested by Paulina https://github.com/servicecatalog/development/issues/411#issuecomment-256455575
