### ISSUE TITLE
Wrong encoding used in org.oscm.app.security.StringScrambler

### ISSUE THREAD

**Issue by skulle** [servicecatalog/development#418]
Hi, 

if i am not mistaken a wrong encoding is used in line (45) `decoded = new String(encoded, "UTF8"); `in method `public static final String decode(final long[] obfuscated)`

UTF8 should probably be renamed to UTF-8. If the password was encoded with UTF8 it cannot be decoded with UTF-8.

**Comment by DawidCh** [comment]
I have done sample code. Just run it in two variants:
`public static void main(String... args) throws UnsupportedEncodingException {
        byte[] bytes = "łódź!@#$%^&*()".getBytes("UTF-8");
        byte[] bytes2 = "łódź!@#$%^&*()".getBytes("UTF8");
        for (int i = 0; i < bytes.length; i++) {
            if(bytes[i] != bytes2[i]) {
                throw new RuntimeException("Sven is right");
            }
        }
        System.out.println("No, he is not.");
    }`
and then change one of UTFs to ISO-8859-1.
I believe I can close the issue.

**Comment by skulle** [comment]
Hi Dawid,

that sounds great. Then you can simply use the correct locale. Did you change it?

Best regards,
Sven

**Comment by DawidCh** [comment]
Hi, I wish. Modifying that creates to big overhead (new branch, tests, jenkins). We have tight schedule and do not event have time for P2 issues.
I closed it without fixing as this is not an issue. Code is working as it should, right?
