### ISSUE TITLE
Problem with viewing page "Manage users" with huge number of users in DB

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#422]
OSCM 16.1.2 Saml mode
Windows 8.1 Enterprise x64
Browsers: IE11, Chrome 52, FF 49.0.2
197483 users in database
user: administrator
![1](https://cloud.githubusercontent.com/assets/18006407/20057485/0238e19c-a4ec-11e6-9e24-c960b23281c0.PNG)

I have the following comments:

- each transition to next/prev page takes more then 5 sec.
- on page I cannot see amount of pages
- if I am on page over then 1000, place with number of pages becomes unreadable
![2](https://cloud.githubusercontent.com/assets/18006407/20057586/b030c09e-a4ec-11e6-8d54-085df34770c4.PNG)
-after click "go" button I have no information about any action - for example we could add progress animation

**Comment by GoebelL** [comment]
Hoopla! 197483 users - that's a lot. Though I wished we had so many users, I fear it's is a bit over the limit.

**Comment by StavrevaS** [comment]
@kwodzynski, do you have an older OSCM version with the same number of users? It would be helpful for us to know if the problem is introduced with 16.1.2 (some multitenancy check maybe).

Development should check if we have DB pagination for the queries which supply data for this table. If this is not the case, that we can solve this issue later if required.

**Comment by DawidCh** [comment]
The issue has been introduced in multi-tenancy feature. The table is new, previously we had input field here. The table is paginated, sorted and filtered in UI. Yes implementing those features in DB will definitely speed up interaction with the component.

**Comment by elfriedegoetz** [comment]
@StavrevaS  this number of user is our setup of the load test we use all the time

**Comment by StavrevaS** [comment]
OK, @DawidCh has already answered the question. We should only schedule the DB pagination implementation.

**Comment by GoebelL** [comment]
The given use case is not realistic.  I agree that server-side paging, sorting, filtering ... etc. would be a useful extension to speedup the page handling. However it's not in scope for this release. 
If you have a need for it, please file a feature request.
