### ISSUE TITLE
user import from file does not check different tenant

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/development#424]
Date:2016/11/08 (multiple IDPs)
BES_MASTER_UNIT-1631 2016/10/28
[Steps to reproduce]
   create a organization SP1 with default tenant
   create a organization SP2 with  tenant1
step1 :login as administrator
step2: goto manage user
step3: tip organization ID from SP1
step4: import user from file 
step5: now import the same user for organization SP2
[Expected result]
user for SP1 and SP2 are created
[Observed result]
user of step4 are creadted
import of user for SP2 faild: 
0 out of 6 users were successfully imported.
The following users were not imported: 	user1: The user ID user1 already exists.

**Comment by elfriedegoetz** [comment]
to reproduce the problem it is necessary to import  for the default tenant first

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix4 
The error still exists, and only occurs if the users are first imported to default tenant organization (SP1) and 
then to non-default tenant org (SP2).
The error does not occur if this is done in the reverse order.
