### ISSUE TITLE
Multitenancy SOAP API - adapt mocks and samples

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#434]
Adapt the samples and mocks which act as web service clients, to use tenantID for SOAP API.

- IntegrationHelper
- mockproduct

Both applications have web pages which can be used for testing.
Mockproduct is important for integration tests

Check if there are other samples and mocks.

**Comment by kowalczyka** [comment]
Reopening due to the mockproduct which is not adapted

**Comment by GoebelL** [comment]
Added @gertipoppel for documentation of IntegrationHelper. 
@kowalczyka 
Please add if anything else is needed here.

**Comment by StavrevaS** [comment]
@kowalczyka if you finish with the mock product, please commit and close this issue.
