### ISSUE TITLE
Wrong redirecting when in link is "tenantid" instead of "tenantID"

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#436]
When I try log-in to non-default tenant and in link I have "?tenantid=XYZ" instead of "?tenantID=XYZ", I have been redirected to wrong tenant (to default, not XYZ)

**Comment by GoebelL** [comment]
If you specify the URL manually you need to take care on correct spelling. URL parameters are case-sensitive.  This works as designed.  
The observed applies to optional parameters, which can be omitted in URLs. Unrecognized URL parts such as wrongly spelled parameters are simply ignored. This is done for security reasons.
For example, the URL parameter **mId** is specifying the marketplace, while **mid** is just ignored.
https://myhost/oscm-portal/marketplace?mid=23ef3f will not redirect to the marketplace with ID 23ef3f, but to the the last visited, which is taken from the stored cookie. 
Whereas URLs like https://myserver/oscm-portal/marketplace?mId=23ef3f will surely direct you to this specified marketplace, if such exists and is accessible for you.

**Comment by GoebelL** [comment]
You are correctly redirected to the default tenant same as without "tenantid=XYZ".
Marking this issue as invalid.
