### ISSUE TITLE
Technical service parameters as passwords - encryption

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#439]
In the technical service definition, a new parameter type "PWD"  is introduced for password parameters.
The value in database is encrypted.

However, for compatibility reasons with already existing technical services, we should consider the old rule: passwords are declared as technical service parameters with type "STRING" and suffix "_PWD", e.g parameter identifier "WINDOWS_ADMIN_PWD".
This kind of parameters should be also encrypted in the database. This is not the case now.

SOAP API and export technical service definition are not in scope of this issue.

**Comment by SuessI** [comment]
I wonder:
Why don't we use the same mechanism as we already have in some config files:
Prefixing the value with "_crypt:"
For example, in configsettings.properties for APP, we have:
BSS_USER_PWD=_crypt:<password>
Replace <password> with the plain text password. The password is encrypted when it is stored in
the database.

**Comment by StavrevaS** [comment]
The APP relies also on the "_PWD" suffix for the UI. After encrypting the prefix is gone, so the encrypted value is like any other value.

**Comment by StavrevaS** [comment]
After some more deep analysis, I come to the following conclusion:

- The suffix "_PWD" for passwords parameters was introduced for the VMWare Adapter contribution, since there was no password parameter type at that time; 
- It was aimed to be temporary solution till the type is introduced (which is the case with 16.1.3, type "PWD") ;
- These parameters are hidden on OSCM UI, but not encrypted in the database;
- For compatibility reasons, we can let UI as it, but we will not encrypt the values in the database like when the parameter type is "PWD";
- @badziakp please check if updating of the services with existing subscription is possible (change parameter type from STRING to PWD), I assume not.

**Comment by badziakp** [comment]
No, updating of service parameter type is not possible. Values of parameters with suffix "_PWD" are not presented on UI.

**Comment by StavrevaS** [comment]
Even if they are configurable?

**Comment by badziakp** [comment]
I mean they are displayed as *****

**Comment by StavrevaS** [comment]
OK, so I close this issue.
