### ISSUE TITLE
Multi tenancy: API does not replace the sts urls correct 

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#441]
[Version]
V16.1 Fix2 

[Date]
2016/11/16

[Test category] 
Creative

[Description]
Setup a service which belongs to an non default Tenant. Calling the API show that the wrong STS is called.  
[Steps to reproduce]
Create multi tenancy (adfs default; Mock-STS tenant "c0a456f5"; second adfs 90f001ed)
Create service which belongs to a non default tenant
Try to use it: Major fault
[Expected result]
can use service
[Observed result] 
failed 
[Details]
See above; 
The service receives the wrong STS information. Instead of openam the wsdl file returns the default (adfs)
[Messages and logs]
content of the wsdl of the tenant c0a456f5 which is openam /mock STS shown clearly the wrong STS endpoint (adfs instead of mock)

http://time.darkside.com:8080/oscm/v1.9/EventService/STS?wsdl&tenantID=c0a456f5
...
<sp:RequireInternalReference/></wsp:Policy><sp:Issuer><wsaw:Address>https://Time.DarkSide.com/adfs/services/trust/13/usernamemixed</wsaw:Address><wsaw:Metadata><wsx:Metadata><wsx:MetadataSection><wsx:MetadataReference><wsaw:Address>https://Time.DarkSide.com/adfs/services/trust/mex/</wsaw:Address></wsx:MetadataReference></wsx:MetadataSection>
...

**Comment by kowalczyka** [comment]
[Details of fix]
Update of installation script so that it does not put the tenant settings value during patching the application.
