### ISSUE TITLE
APP - adapt to use generated encrypetion key, different from OSCM

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#443]
APP should be adapted to use own encryption key, different from the one of OSCM.
OSCM is already adapted to use generated encryption key. Use the same logic for APP.

**Comment by MiethanerR** [comment]
APP uses now a generated encryption key like OSCM. Fix merged into master.

**Comment by gertipoppel** [comment]
Added description of APP_KEY_PATH to the APP documentation and all Controller manuals.
