### ISSUE TITLE
APP - rollback of instance attributes in case of aborting instance modification

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#444]
The instance parameters are saved for rollback in case of aborted instance modification (e.g by some exception).
The same rollback logic is needed for the instance attributes,

**Comment by DawidCh** [comment]
I have added rolling back the instance attributes. I cannot find correct scenario for testing.
@StavrevaS Could you please find few minutes for review?

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/development/449)

**Comment by DawidCh** [comment]
TODO: increase coverage on that branch to pull up coverage on master.

**Comment by DawidCh** [comment]
[Details of fix]
Added rollback metod to ServiceInstance. Parameter for rollback are stored in new column in db just to have them saved to revert if error is raised.

**Comment by DawidCh** [comment]
[details of cause]
During implementation of rolling back instance modification, instance parameters were missed.
[details of fix]
Added rollback metod to ServiceInstance. Parameter for rollback are stored in new column in db just to have them saved to revert if error is raised.
[similar cases]
One similar case has been added - rolling back subscription reference
