### ISSUE TITLE
MP_ERROR_REDIRECT_HTTP handling

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#452]
[Version] 
ESCM 16.1 Fix3 SAML mode
[Build]
BES_MASTER_UNIT-16482016/11/18
[Environment]
Windows 8.1 Enterprise x64

Steps:
1. Supplier (non-default tenant) create new customer user
2. Delete session and cookies
3. Try to login with customer credentials
4. Login is correct, but I see default tenant marketplace 

It is caused by value of "MP_ERROR_REDIRECT_HTTP". 
I think that value should be tenant-specific, because user in tenant A must not know about marketplaces in tenant B.

To your decision.

**Comment by GoebelL** [comment]
Hi @kwodzynski, 
which value is set for MP_ERROR_REDIRECT_HTTP in your case? 
Actually this setting can be used for configuring any  platform-wide redirect target. But a tenant specific redirect setting sounds reasonable to me.

@mdehn, how do you judge this?

**Comment by kwodzynski** [comment]
Hi @GoebelL 
My value is: http://g02plxnnow29222:8080/oscm-portal/marketplace?mId=f702d44b

Regards,

**Comment by mdehn** [comment]
I agree that a user in tenant A must not know about marketplaces in tenant B.

**Comment by DawidCh** [comment]
@mdehn I think the question is should we develop MP_ERROR_REDIRECT_HTTP a tenant specific. It will not narrow visibility of any marketplaces.

**Comment by mdehn** [comment]
No need for now to implement a tenant-spedific redirect.
Describe in the doc that the MP_ERROR_REDIRECT_HTTP page is visible for all the tenants.

**Comment by gertipoppel** [comment]
Added the following hint to the following source files: 
"Note that this URL is used platform-wide. It is not tenant-specific."

DocSources12/en/OperationsGuide/Marketplace/c_ConfigureMP.xml
DocSources12/en/Shared/reference/r_ConfigSettings_config_properties.xml
DocSources12/de/Shared/reference/r_ConfigSettings_config_properties.xml
DocSources12/en/Shared/reference/r_IDP_Properties.xml

@redmond2683 - Please add the hint to the Japanese r_ConfigSettings_config_properties.xml file.

**Comment by redmond2683** [comment]
added the hint to the japanese page:
UserDoc/DocSources12/ja/Shared/reference/r_ConfigSettings_config_properties.xml

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix4
verified English
