### ISSUE TITLE
Name of Custom tab

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#455]
[Build]
PRIVATE-BUILD-ON-ESTITNB52016/11/22(master branch)

Case 1:
[Steps to reproduce]
1. Click update service
2. Set name of custom tab
3. Click save
4. Click Localize in update service

[Expected result]
Name of custom tab is shown in the source language

[Observed result]
Name of custom tab is empty

Case 2:
[Steps to reproduce]
1. Click update service
2. Set name of custom tab
3. Click save
4. Click Localize in update service
5. Enter localization(only one language ex. Japanese)
6. Click OK
7. Click Localize

[Expected result]
Name of custom tab is shown in each language in target space

[Observed result]
Name of custom tab is shown only in Japanese which I wrote in step 5 even if other language is selected.

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix4 
verified Japanese localization
