### ISSUE TITLE
Incorrect name of Defalt tenant in drop-down lists of "Tenant"

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#457]
[Version]
ESCM 16.1 Fix3 SAML mode
[Build]
BES_MASTER_UNIT-16482016/11/18
[Environment]
Windows 8.1 Enterprise x64

In each drop-down lists of "Tenant" (for example /oscm-portal/operator/createOrganization.jsf), we cannot see option "Default" - but we can choose this option as "-- Select one --". I think it should have a separate name.

**Comment by StavrevaS** [comment]
@mdehn can you specify if should changed the UI here?

**Comment by mdehn** [comment]
The current behavior seems confusing for a user.
Therefore provide a meaningful name here.

**Comment by grubskim** [comment]
Changed list to display "Default tenant"

**Comment by SylviaDehn** [comment]
[Build] 17.3+
[Date] 2017/08/30
verified
