### ISSUE TITLE
User with only administrator role in supplier/technology provider org cannot access blue portal

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#459]
[Version]
16.1.3

[How to reproduce]
1. Register a new user in an existing organization (supplier and technology provider) and give ONLY the "Administrator" role to this user.
2. Change the password and login.

[Expected]
The new administrator can access both portals, administration and marketplace.

[Observed]
The new administrator can access  only marketplace portal.

**Comment by badziakp** [comment]
[Details of fix]
The organization admin can access blue portal.

**Comment by SylviaDehn** [comment]
[Build] 16.1.4 2016/12/16
verified
