### ISSUE TITLE
Delete onbehalf user

### ISSUE THREAD

**Issue by skulle** [servicecatalog/development#46]
Hi,
it seems that a supplier user cannot delete the onbehalf user he created. Please refer to `IdentityServiceBean.cleanUpCurrentUser()`. 

And the `cleanUpCurrentUser` method name is a bit missleading or may be even inappropriate  since the corresponding method to create an onbehalf user is called `createOnBehalfUser`?

Greetings,
Sven

**Comment by StavrevaS** [comment]
Hi @skulle 
I agree that the name is misleading, but this method is a part of the OSCM platform API and simple renaming without versioning the API is not possible. But the documentation describes correctly the action taken with this method.
I don't understand why the supplier cannot delete the onbehalf user? Can you explain how to reproduce it?

**Comment by skulle** [comment]
Hi StavrevaS,
nevermind, I retested and it works fine. I guess i did something wrong the last time. 

My CT-MG installation is running in SSO mode and I created with a supplier user an onbehalf user for one of the supplier's customers. Afterwards I used the onbehalf user and called the mentioned cleanup method on the identity service.

Cheers,
Sven
