### ISSUE TITLE
subscriptionid in bssappuser.serviceinstance does not change when subscription update

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#461]
[build]
PRIVATE-BUILD-ON-ESTITNB52016/11/25(master-branch)

[Steps to reproduce]
1. Subscribe service
2. Update subscription name
3. Wait finishing update

[Expected result]
subscriptionid in bssappuser.serviceinstance is updated

[Actual result]
subscriptionid in bssappuser.serviceinstance is not changed

[Detail]
This is important for extension interface. subscriptionid used for check as authentication and extension interface cannot get information form IaaS cloud if authentication is failed.

**Comment by MiethanerR** [comment]
The problem was a wrong execution order after the last change. Fix was merged into master

**Comment by SylviaDehn** [comment]
verified 16.1 fix 3 build 01.12.2016
