### ISSUE TITLE
Missing busy indicator for the custom tab

### ISSUE THREAD

**Issue by grubskim** [servicecatalog/development#462]
[Version]
ESCM 16.1 Fix3 SAML mode

[Details]
The content of iframe in the custom tab on my subscription page takes some time to load. Busy indicator should be introduced, in form of "Loading. Please wait..." or something similar. Also a spinning cursor circle should be added.

**Comment by grubskim** [comment]
[Details of fix]
Added loading message with javascript. Sent emails for Japanese and German translations.

**Comment by SylviaDehn** [comment]
@grubskim: please verify with 16.1 fix4 ; I cannot check it, my custom tab loads instantly.
