### ISSUE TITLE
Subscription id string which is include Japanese and English is broken when that show in custom tab

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#463]
[Build]
PRIVATE-BUILD-ON-ESTITNB52016/11/25 (master branch)

[How to reproduce]
1. Subscribe service with subscription name which include Japanese and English.
2. See custom tab

[Expect result]
Subscription name is shown correctly

[Observed result]
Subscription name is not correct character.

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix4 2016/12/16
vierified
