### ISSUE TITLE
Attribute name cannot be emptied in custom attributes 

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#467]
[Build] 16.1 fix3 18.11.2016
[Steps to reproduce]
1. As supplier go to Account/Manage attributes
2. Enter a new attribute for customers or subscriptions
3. For attribute enter all fields and save
4. Edit this  attribute; empty attribute name and save

[Expected result]
attribute name is emptied

[Observed result]
nothing happens (old value stays)

**Comment by MiethanerR** [comment]
This was fixed and merged together with issue #443.

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix4 
not fixed

**Comment by MiethanerR** [comment]
Fixed. Locale strings for the attribute names are now deleted if a null value or an empty string is the input.

**Comment by SylviaDehn** [comment]
[Build]16.1. fix6 verified
