### ISSUE TITLE
Locale  does not change in extension interface when user locale change

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#470]
[Build]
PRIVATE-BUILD-ON-ESTITNB52016/11/29

[how to reproduce]
1. Change user locale(ex. Japanese)
2. Show extension interface in custom tab

[Expect result]
Extension interface is shown in Japanese

[Actual result]
Extension interface is shown in English

**Comment by grubskim** [comment]
Hello,

In the case of custom tab, only the tab header can be localized. This was specified in requirements of the feature. I tested it and it works fine.

I assume that what is required here is that the whole content of the custom tab is localized. This would require much more time than the regular bugfix (APP is not localized at all). If it is needed I think it should be logged as a feature.
