### ISSUE TITLE
Marketplace/Account/Profile Japanese texts missing

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#471]
[Build] 16.1 fix3 25.11.2016
[Steps to reproduce]
1. Log in as Customer to Marketplace with Japanese Profile
2. Go to Account/Profile
 
[Expected result]
Tabs are in Japanese

[Observed result]
Tabs are in English

![profile](https://cloud.githubusercontent.com/assets/15086024/20748496/abe52e62-b6ee-11e6-9cde-73da76132f92.png)

**Comment by redmond2683** [comment]
fixed in a5efed3f07ca672ec4af140d0a010a566775e837. could you please check again with the latest artifacts?
