### ISSUE TITLE
Cannot update subscription if new custom attributes were created after subscription was created

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#476]
[Build] 16.1 fix3 25.11.2016

[Steps to reproduce]
1. Create AWS subscription with subscription attributes
2. Update subscription ref ID, save (all is ok)
3. As Supplier, create a new subscription attribute I used one that is a user option, and encrypted
4. Update subscription ref ID, save

[Expected result]
updated reference ID is saved

[Observed result]
Very strange error message, that looks like something is wrong with the database
“The custom attribute {udaDefinitionKey=25010, targetObjectKey=178024} does not exist.”

[Details]
major, because customer does not know what the problem is, and update of subscription is not possible.

see screenshot
![newsubattr](https://cloud.githubusercontent.com/assets/15086024/20884650/c91722cc-baec-11e6-9c45-dd4f5a4d4cd1.png)

**Comment by SylviaDehn** [comment]
changed to critical because DB is broken. Update script needed. Also unit tests.

**Comment by MiethanerR** [comment]
I can't reproduce this with a current build of oscm

**Comment by MiethanerR** [comment]
I was able to reproduce the problem, it is specific to async modification.

**Comment by GoebelL** [comment]
This issue refers to a special case with asynchronous subscription modification, when creating customer UDAs and leaving attribute default values empty. A workaround exist, therefore I don't consider the severity as critical. 
Please add an update script with the fix and an integration test.

**Comment by MiethanerR** [comment]
There is no need for an update script for this case since the transaction was aborted. I added an check for null values to the save method to ensure that the UDA is created.

**Comment by SylviaDehn** [comment]
[Build] 16/12/2016
verified
