### ISSUE TITLE
TechnicalService.xml for openstack the parameter for "public IP" and "subnet" are missing

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/development#479]
[Build] 
BES_MASTER_UNIT-16762016/11/25 

[Description]
sample for TechnicalService.xml for openstack the parameter for "public IP" and "subnet" are missing

**Comment by GoebelL** [comment]
The definition of these parameters is included in the technical service template for K5. Similar should be integrated in sample template for OpenStack.

**Comment by redmond2683** [comment]
Updated TechnicalService_OpenStack.xml, template.json, and template.yaml in 0fbc0a3237f6bfe524c3daef4ef75679ddea0e8b.
These are available with the subsequent artifacts.
