### ISSUE TITLE
Documentation should be improved by adding info about choosing controller specific attribute names

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#485]
[Build] 16.1 fix3 01.12.2016

[Steps to reproduce]
1. As supplier define 2 custom customer attributes. One should be a password for AWS and one a password needed for using OpenStack. The supplier specifies the controller id for both passwords and the correct ID needed for the controller. 
2. The supplier publishes 2 services, one OpenStack, one AWS to the marketplace.
3. The customer sees the 2 attribute names in the profile tab, but does not know which he needs to set.

[Expected result]
You can tell which attribute is the password for which controller.

[Observed result]
As a customer admin, you cannot tell which attribute is the password for which controller because the Supplier did not choose good names for the attributes. (the UI does not show the controller id, and should not do so)

[Details]
The online documentation should tell the supplier to use meaningful names for controller specific attributes, because the customer will not have information which attribute is controller specific. e.g.  "AWS password"

**Comment by gertipoppel** [comment]
Added the corresponding information to the online help page (Adding a custom attribute).
Modified source file:
DocSources/en/help/tasks/createCustomUda.xml

@redmond2683 Could you please do the same for Japanese? Thank you.

**Comment by redmond2683** [comment]
Done for the Japanese documentation.

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix4 verified
