### ISSUE TITLE
Mock Product (sample) is not updated for new custom attributes or tenant id

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#486]
[Build] 16.1 fix3 01.12.2016

[Steps to reproduce]
1. create custom subscription and customer attributes as supplier
2. publish mock product service as supplier
3. as customer subscribe to service  
4. set subscription attributes 

[Expected result]
Check the mockproduct for the new parameters; 

[Observed result]
I cannot find the subscription attributes, only the customer attributes

[Details]
Please update the mockproduct. Currently if I update subscription attributes, I see 2 calls in my Mockproduct:
ProvisioningService.upgradeSubscription (?????)
and 
ProvisioningService.modifySubscription 
According to Robert this is incorrect information.
We need  this for testing. Please provide this.

Similar Issues:
Please also allow for the tenantID. 
The Mock product is also used for triggers, so we need adjust the settings with tenantID.
Example Service must be checked too.

**Comment by MiethanerR** [comment]
There was a wrong string set for the new saveAttributes method. The oscm tenant ID is currently not needed on the provisioning side and other interfaces of the mockproduct.

**Comment by GoebelL** [comment]
Please tag the resolution.

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix 4 16.12.2016
verified

**Comment by SylviaDehn** [comment]
tenantID is needed (not for provisioning) but for triggers etc (callback)

**Comment by SylviaDehn** [comment]
subscription attributes are verified,
but tenantID is needed and really important for testing.

**Comment by SylviaDehn** [comment]
Suzana found that it is possible. There is a properties file.
