### ISSUE TITLE
compatibility problem with ProvisioningService

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/development#488]
[Build] 
BES_MASTER_UNIT-16812016/12/06

[Description]
old ProvisioningService (v1.6) not running any more

see server.log:

[#|2016-12-09T11:26:44.111+0100|INFO|glassfish3.1.2|com.sun.xml.xwss.XWSSClientTube|_ThreadID=170;_ThreadName=Thread-2;|Response message processed in Tube [ com.sun.xml.xwss.XWSSClientTube ] Instance [ 138 ] Engine [ Metro/2.2.0-1 (tags/2.2.0u1-7139; 2012-06-02T10:55:19+0000) JAXWS-RI/2.2.6-2 JAXWS/2.2 svn-revision#unknown: Stub for http://estgoetz.intern.est.fujitsu.com:9080/WebCalendarProvision/ProvisioningService ] Thread [ http-thread-pool-8080(3) ]:
<?xml version='1.0' encoding='UTF-8'?>
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
  <S:Body>
    <S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope">
      <faultcode>S:Client</faultcode>
      <faultstring>Cannot find dispatch method for {http://bss.fujitsu.com/xsd}sendPing</faultstring>
    </S:Fault>
  </S:Body>
</S:Envelope>|#]

**Comment by StavrevaS** [comment]
The error should be reproduced with integration test. Old mocks should be included in the integration test to test the compatibility layers. 
It will be implemented as web service test, which pings a technical service which represents old provisioning service versions.

**Comment by StavrevaS** [comment]
@elfriedegoetz can you attach your technical service definition?
I've imported services for mockproduct in provisioning version v1.6 and v1.7. I can ping both services with 16.1.3 BES_MASTER_DELIVERY-8812016/12/01

**Comment by SylviaDehn** [comment]
@GoebelL why is this unclear?

**Comment by StavrevaS** [comment]
I have tested with BES_MASTER_DELIVERY-8912016/12/11 and still cannot reproduce the error.
The BES_MASTER_UNIT-16812016/12/06 was intermediate result and is not available anymore.

**Comment by StavrevaS** [comment]
@elfriedegoetz can you test it again in your environment?

**Comment by StavrevaS** [comment]
The problem is found on the application side which implements the ProvisioningService.
With the runtime versioning concept of the SOAP API, a static wsdl file need to be provided in order OSCM can recognize the service version. This was not the case with the given application, so OSCM can only see the wsdl automatically generated by the glassfish which has no documentation tag with the service version.
This issue is invalid.
