### ISSUE TITLE
Trailing blanks in Tenant definition are not ignored

### ISSUE THREAD

**Issue by SchneiderW** [servicecatalog/development#489]
OSCM 16.1. Fix3:
Use Case: Create a new tenant
Import tenant settings by a file incl. the key SSO_IDP_SAML_ASSERTION_ISSUER_ID.
The value of this key has trailing blanks, e.g.:
"SSO_IDP_SAML_ASSERTION_ISSUER_ID=http\://server.com\:9080/OpenAM-13_IDP2      "
(without quotes)
The blanks are not removed during import process and authentication will not work because CT-MG compares the values including the blanks. Therefore the ISSUER_ID does not match and the login fails.

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix4 2016/12/16 verified
