### ISSUE TITLE
Keystone API URL for UK region is not correct in TechnicalService_K5.xml

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#492]
Keystone API URL for UK region is not correct in TechnicalService_K5.xml.
[Observed] https://identity.jp-uk-1.cloud.global.fujitsu.com/v3/auth
[Expected] https://identity.uk-1.cloud.global.fujitsu.com/v3/auth

**Comment by SylviaDehn** [comment]
[Version] 16.1 fix6 2017/02/17 verified
