### ISSUE TITLE
Encryption of passwords for app database does not allow multiple updates; Backup of key files necessary

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#502]
[Build] 16.1 fix3 15.12.2016 (pre fix4)

[Steps to reproduce]
1. when updating app db with 

ant -f build-db.xml updateDatabase (necessary with most releases)

all settings (including password settings are updated).  These update configuration files contain passwords
like this "_crypt:mypasswd". 

[Expected result]
The update installation should always work.

[Observed result]
The update installation only works once, when the key file does not exist yet.

[Details]
With the new password encryption mechanism via a key file which is somewhere in the file system, this update mechanism works only once, when the key file does not exist yet. Please change it to always check for for _crypt:.... passwords. Otherwise update installations will no longer work.
For documentation:
Also make sure that if you backup your db (app and bes db) you have to backup your key files . And when you restore your db (e.g. in the event of a crash), to also restore your key file before you deploy the
software.
This has to be documented.

**Comment by gertipoppel** [comment]
Documentation has been extended 
(Release Notes, Operator's Guide, APP and all Controller manuals)

**Comment by MiethanerR** [comment]
APP will now check on every startup for _crypt in the config settings.
