### ISSUE TITLE
new setting KEY_FILE_PATH not in ..../databases/bes_db/configsettings.properties

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#506]
[Build] 16.1 fix3 15.12.2016 (pre fix4)

[Steps to reproduce]
The release notes for 16.1 fix4 state that 
"A new configuration setting (KEY_FILE_PATH) is available in the configsettings.properties file
located in <install_pack_dir>/ databases/bes_db.
This setting is used for specifying the location of the file containing the key required for encryption
and decryption of service parameters with data type PWD or custom attributes marked for
encryption."

[Expected result]
KEY_FILE_PATH is found as an optional parameter in configsettings.properties

[Observed result]
KEY_FILE_PATH is not found in properties file

[Details]
Please enter parameter (not mandatory) with default value shown

**Comment by MiethanerR** [comment]
I checked the file from the latest build and found the entry.

**Comment by SylviaDehn** [comment]
verified
