### ISSUE TITLE
update subscription (service) attributes are not received by service

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#507]
[Build] 16.1 fix3 15.12.2016 (pre-fix4)

[Steps to reproduce]
1. create custom subscription and customer attributes as supplier
2. publish mock product service as supplier
3. as customer subscribe to service
4. set subscription attributes when provisioning
5. update subscription attributes

[Expected result]
Check the mockproduct for the new parameters after update

[Observed result]
Subscription (Service) attributes are not received, only the customer attributes.

**Comment by MiethanerR** [comment]
I updated the modification flag to recognize uda only modifications. Fix merged to master.

**Comment by SylviaDehn** [comment]
[Build] 16.12.2016 16.1 fix4 
verified
