### ISSUE TITLE
Improve Search in "My Subscriptions" and "Account -> Subscriptions"

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#508]
Searches should work like follows:
1. subscription with name "automobilia"
2. Subscription is found when user types
- auto
- mobil
- bilia

Make sure that encrypted UDAs or params are not taken into consideration during indexing.

**Comment by kwodzynski** [comment]
I tested this feature on Glassfish 4, jdk1.8.0u121, build GLASSFISH4_EE_UNIT-85 2017/04/06 in SAML mode. The both searchers are working as expected.
