### ISSUE TITLE
operator client creates organization in wrong tenant (command line interface)

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#514]
[Version]
16.1 fix4 2016/12/16

[How to reproduce]
-  unzip oscm-operatorclient.zip
-  set up command line tool as described in Operation.pdf
-   fill out org.properties file with the goal of creating a customer organization. Specify a marketplace which does not refer to default tenant

e.g.

[Expected result]
new customer organization is setup in correct tenant (which is specified indirectly by marketplace)

[Observed result]
organization is created in default tenant

**Comment by SylviaDehn** [comment]
Could this be the same problem as https://github.com/servicecatalog/development/issues/424 ?
I think it is important to fix these bugs soon since nobody would want to import users manually ....

**Comment by kwodzynski** [comment]
Checked on Glassfish 4, jdk 8u121, Windows Server 2016, build GLASSFISH4_EE_UNIT-62-20170313093758. It works as expected, verified.
