### ISSUE TITLE
Provide a controller for Azure IaaS

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#515]

**Comment by GoebelL** [comment]
Hi @pujarisat 

please raise your pull request to [fb_azure_adapter](https://github.com/servicecatalog/development/tree/fb_azure_adapter).

**Comment by SuessI** [comment]
@pujarisat 
Hello,
in the next two weeks I am going to write a new manual for the Azure controller similar to the ones we already have for AWS, VMWare, ROR etc. 
As an input, could you please provide some basic information on the Azure integration:
- which components of CT-MG/APP and Azure are involved and how do they interact?
- which usage scenarios are supported?
Information similar to the one provided in Section 1.1 and 1.2 of all our existing integration guides would be very helpful for a start, just 1-2 pages. And of course: the sooner the better.
Thanks in advance

**Comment by DawidCh** [comment]
The controller has been delivered to pointed out branch.
