### ISSUE TITLE
TechnicalService_AWS.xml for aws should be updated in samples directory

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#516]
[Build] 16.1 fix4 16.12.2016 

[Steps to reproduce]

1. unpack aws install pack
2. use TechnicalService_AWS.xml in samples directory to build own technical service

[Expected result]
The default values are valid 

[Observed result]
The settings for aws have changed, so it is no longer possible to use service. 

[Details]
Specifically the image name has changed

**Comment by SylviaDehn** [comment]
[TechnicalService_AWS.xml.txt](https://github.com/servicecatalog/development/files/661197/TechnicalService_AWS.xml.txt)

**Comment by SylviaDehn** [comment]
Please also update the documentation

**Comment by gertipoppel** [comment]
Modified the example for the IMAGE_NAME parameter

**Comment by StavrevaS** [comment]
Changed sample service with values form the attached document in previous comments,

**Comment by SylviaDehn** [comment]
verified 17.1
