### ISSUE TITLE
Port number incorrect in custom tab documentation

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#519]
[Version]
16.1 fix4 2016/12/16

[How to reproduce]

1. check documentation for add service/ custom tab section 
help/en/help/tasks/service_add.htm

[Observed result]
example for  URL of a custom tab
For example:

https://MyAPPHost:8880/oscm-app-openstack/serverInformation.jsf

[Expected]
Either make it http: or use 8881 as a port number

**Comment by gertipoppel** [comment]
Corrected the sample. It now reads https and 8881
Modified source files: 
UserDoc/DocSources12/en/help/tasks/service_add.xml
UserDoc/DocSources12/en/help/tasks/service_edit.xml
UserDoc/DocSources12/de/help/tasks/service_add.xml
UserDoc/DocSources12/de/help/tasks/service_edit.xml
UserDoc/DocSources12/ja/help/tasks/service_add.xml
UserDoc/DocSources12/ja/help/tasks/service_edit.xml
UserDoc/DocSources12/en/ReleaseNotes/WhatsNew/c_ExtensionInterface.xml

**Comment by SylviaDehn** [comment]
[Version]
16.1 fix6 2017/02/17 verified
