### ISSUE TITLE
Extension interface token for custom content needs to be secured

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#533]
[Version]
16.1.4

[Detail]
In MySubscriptionsCtrl.getCustomTabUrlWithParameters() the extension interface URL is generated with  parameters specifying the context and a token. The later parameter needs to be encrypted.
Use the token containing timestamp to decide expiration after short time. Refer to restore password link for similar logic.

**Comment by MiethanerR** [comment]
I implemented a standard signing algorithm for the tokens creation and validation based on the certificates, that are exchanged between oscm and app.

**Comment by SuessI** [comment]
In context of solving issue #573 , the following settings were changed again from mandatory to optional:
SSO_SIGNING_KEY_ALIAS
SSO_SIGNING_KEYSTORE
SSO_SIGNING_KEYSTORE_PASS
The settings are only mandatory for signing SAML logout requests and requests from custom tabs.

**Comment by SuessI** [comment]
Updated documentation for this issue:
GitHub Sources:
•  Development/DocSources/en/APPInt/APP/r_ConfigSettings.xml 
•  Development/DocSources/en/Shared/Installation/c_Update.xml 
•  Development/DocSources/en/Shared/reference/r_ConfigSettings_config_properties.xml 
•  Development/DocSources/en/help/tasks/service_add.xml 
•  Development/DocSources/en/help/tasks/service_edit.xml
GitLab:
Development/UserDoc/DocSources12/en/ReleaseNotes/WhatsNew/c_ExtensionInterface.xml

**Comment by SylviaDehn** [comment]
[Version] 16.1 fix 6 2017/02/17
verified
- SSO parameters are optional again
- additional notes for custom tab ok

**Comment by GoebelL** [comment]
Due to this change of the token semantic the extension interface cannot be used with old versions of controllers. 
@gertipoppel 
We need a note in the documentation, that for using the extension interface, app and controllers need to be updated.

**Comment by gertipoppel** [comment]
I added the following note to the Release Notes for Fix 7 (sections What's New/Extension Interface and Update Installation: 

The new extension interface cannot be used with previous versions of APP or service controllers. For the extension interface to function correctly, you need to carry out an update installation for APP as well as the service controllers to V16.1 Fix 7.

GitLab sources:
Development/UserDoc/DocSources12/en/ReleaseNotes/WhatsNew/c_ExtensionInterface.xml
Development/UserDoc/DocSources12/en/ReleaseNotes/Compatibility/c_UpdateInstall.xml
