### ISSUE TITLE
configsettings.properties not updated for hidden menus etc

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#535]
[Build] 16.1 fix4 16.12.2016

[Steps to reproduce]

1. check configsettings.properties for hiding tenant menus

[Expected result]
It is possible to hide menu
# operator.manageTenants 

[Observed result]
The menus are not added to "#" items

**Comment by grubskim** [comment]
Added tenants link to the configsettings.properties list.

**Comment by kwodzynski** [comment]
Windows Server 2016, jdk1.8u131, build BES_MASTER_UNIT-1897 2017/07/26 in SAML mode.
The value "operator.manageTenants" is added to "#" items.

**Comment by kwodzynski** [comment]
Retested on Windows Server 2016, jdk1.8u131, build BES_MASTER_UNIT-1904 2017/07/27 (official 17.3.0) in SAML mode. 
The value "operator.manageTenants" is added to "#" items.
