### ISSUE TITLE
Enhance extension interface documentation 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#536]
[Version] 
16.1.4

[details]
Documentation of OSCM extention interface for custom tab needs to be extended.
Appended URL parameters:
- orgId = Organization owning the subscription
-    subId = Subscription Name (ID)
-    instId = ID of provisioned instance, e.g. Instance ID used in APP.

**Comment by gertipoppel** [comment]
Added the requested documentation to the Release Notes of Fix 5 as well as to the online help for the supplier (when defining a service).

**Comment by SylviaDehn** [comment]
[Version] 16.1 fix6 2017/02/17 
verified doc and release notes
