### ISSUE TITLE
configsettings.properties not updated for hidden menu / manage indexes

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#537]
[Build] 16.1 fix4+ 16.01.2017 (reset index branch)

[Steps to reproduce]
1.    check configsettings.properties for hiding tenant menus

[Expected result]
It is possible to hide menu
operator.manageIndexes
via config settings (menu is listed)

[Observed result]
The menus are not added to "#" items in configsettings.properties

**Comment by MiethanerR** [comment]
added missing entry to doc in configsettingKeys

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix 6 2017/02/17
reopen because similar issues e.g. "manage tenants" menu is not listed either.

**Comment by grubskim** [comment]
Fixed with f7e9501e21c101a2c1973c04c87e3b351b471d2a

**Comment by kwodzynski** [comment]
Windows Server 2016, jdk1.8u131, build BES_MASTER_UNIT-1897 2017/07/26 in SAML mode.
The values "operator.manageIndexes" and "operator.manageTenants" are added to "#" items.

**Comment by kwodzynski** [comment]
Retested on Windows Server 2016, jdk1.8u131, build BES_MASTER_UNIT-1904 2017/07/27 (official 17.3.0) in SAML mode. 
The values "operator.manageIndexes" and "operator.manageTenants" are added to "#" items.
