### ISSUE TITLE
description for resetting index can be improved

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#538]
[Build] 16.1 fix4+ 16.01.2017 (reset index branch)

[Steps to reproduce]
1. As platform operator go to "operation/update indexes"
2. look at description

[Expected result]
Deletes all indexes and recreates them. (better english)
Or possibly singular (for menu and description)

[Observed result]
Deletes index and creates it. Please check with Gerti for proper terminology.

**Comment by SylviaDehn** [comment]
Please also note that the spelling for "indexes" and "indices" should be unified if we stay with the plural.
Note that the message "Indices are updated" uses a different spelling.
The question I ask myself, do we have more than the search index? Or is it always just this one. Then we
could change both the menu and the index to singular. If more could exist in the future, then you could keep the menu in plural.

**Comment by MiethanerR** [comment]
Clarified the phrasing together with @gertipoppel and updated it in the branch. It uses now singular to not confuse the user. (even so there are two indexes for service search and subscription search).

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix 6 2017/02/17
verified
