### ISSUE TITLE
JMS queues work only with default values of jmsuser name and password - glassfish 4.1

### ISSUE THREAD

**Issue by badziakp** [servicecatalog/development#545]

**Comment by DawidCh** [comment]
There is workaround applied. User created during deployment of domains ("jmsuser") is added to "admin" group instead of "user" group. Now jms queue (embedded in glassfish) started to accept the credentials.

**Comment by kwodzynski** [comment]
Checked on Glassfish 4, jdk1.8.0u121, build GLASSFISH4_EE_UNIT-85 2017/04/06 in SAML mode.
It is working as expected.
