### ISSUE TITLE
Issue to search services - glassfish 4.1

### ISSUE THREAD

**Issue by victorhrsilva** [servicecatalog/development#549]
[Build] GLASSFISH4_WS-13-20170127122720

[Steps to reproduce]
Be sure that you have services activated on your marketplace
1. Login to Marketplace
2. Search for a service, with the top-right field

[Expected result]
See a list of services that satisfy the search criteria.

[Observed result]
It does not work, the page is loading without retrieve any response. Backend throws several exceptions, please see attached.

[master-indexer-domain-server.txt](https://github.com/servicecatalog/development/files/741359/master-indexer-domain-server.txt)
[bes-domain-server.txt](https://github.com/servicecatalog/development/files/741360/bes-domain-server.txt)

**Comment by GoebelL** [comment]
I confirm service search is not working. However, subscription can be searched. 
@DawidCh or assignee
Please check.

**Comment by StavrevaS** [comment]
Duplicate, see issue #555

**Comment by DawidCh** [comment]
Duplicate, so closing.
