### ISSUE TITLE
Birt reports

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#552]
Birt runtime environment seems to have problems when deployed on server which is run with java 8. The output from engine is:
enBIRT Report Viewerhttp://localhost:8180/birt/webcontent/birtfalsenullltrBIRT Report Viewer Toggle table of contentsToggle table of contentsRun reportRun reportExport dataExport dataExport reportExport reportPrint reportPrint reportPrint report on the serverPrint report on the server simpleExportDataDialogsimpleExportDataDialogsimpleExportDataDialogsimpleExportDataDialogExport DatasimpleExportDataDialogClosesimpleExportDataDialogsimpleExportDataDialog Available result setsAvailable ColumnsAdd allAdd allAddAddRemoveRemoveRemove allRemove allUpUpDownDownSelected ColumnsExport format:org.eclipse.birt.report.engine.dataextraction.csv">CSVcsvOutput encoding:Other(If blank,use the local encoding)Separator:Comma ( , )Semicolon ( ; )Colon ( : )Vertical Line ( | )Tab ( \t )Export column's data typeExport column as locale neutralExport data with Carriage ReturnsimpleExportDataDialogsimpleExportDataDialogsimpleExportDataDialogsimpleExportDataDialogOKOKsimpleExportDataDialogCancelCancel exceptionDialogexceptionDialogexceptionDialogexceptionDialogExceptionexceptionDialogCloseexceptionDialogexceptionDialog Show Exception Stack TraceHide Exception Stack TraceStack Trace:exceptionDialogexceptionDialogexceptionDialogexceptionDialogOKOKexceptionDialogCancelCancel parameterDialogparameterDialogparameterDialogparameterDialogParameterparameterDialogCloseparameterDialogparameterDialog Parameters marked with * are required. SessionId9dcd71fa20f3244b5bd934b43eceSessionId_displayText9dcd71fa20f3244b5bd934b43ece WSDLURLhttp://localhost:8180/Report/ReportingServiceBean?wsdlWSDLURL_displayTexthttp://localhost:8180/Report/ReportingServiceBean?wsdl SOAPEndPointhttp://localhost:8180/Report/ReportingServiceBeanSOAPEndPoint_displayTexthttp://localhost:8180/Report/ReportingServiceBeanparameterDialogparameterDialogparameterDialogparameterDialogOKOKparameterDialogCancelCancel exportReportDialogexportReportDialogexportReportDialogexportReportDialogExport ReportexportReportDialogCloseexportReportDialogexportReportDialog Export Format:docx">DOCXxls">Excelodp">OpenDocument Presentationods">OpenDocument Spreadsheetodt">OpenDocument Textpdf">PDFpostscript">PostScriptppt">PowerPointpptx">PPTXxls_spudsoft">Spudsoft Exceldoc">Wordxlsx">XLSXPagesAll pagesCurrent pagePages:( Enter page number(s) and/or page range(s). For example: 1-6 or 1,3,6 )Fit ToAutoActual sizeFit to whole pageexportReportDialogexportReportDialogexportReportDialogexportReportDialog

The problem occurs on birt runtime version 4.6 and 4.3 so we can assume the problem lies somwhere else.

**Comment by DawidCh** [comment]
This is official bug on eclipse birt runtime:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=459440

**Comment by DawidCh** [comment]
There is an issue with buffer="none" in jsp pages. It has to be removed from birt. In addition this has to be fixed as well in scope of this bug:
https://java.net/jira/browse/GLASSFISH-20880

**Comment by DawidCh** [comment]
As a workaround I may advise to deploy and set up birt runtime on glassfish 3 (or Tomcat) set up on Java 7. After that set REPORT_ENGINEURL property using platform_operator user to that address, ie:
http://<glassfish3_host>:<glassfish3Port>/birt/frameset?__report=${reportname}.rptdesign&SessionId=${sessionid}&__locale=${locale}&WSDLURL=${wsdlurl}&SOAPEndPoint=${soapendpoint}&wsname=Report&wsport=ReportPort
work in progress to get the reports running on java8.

**Comment by DawidCh** [comment]
It cannot be fixed easy (in short time). I was able to get the reports without parameters to work but those which use parameters needs more work. We will wait for ecplise birt community to fix the problem.

**Comment by grubskim** [comment]
Tested birt on:
Apache Tomcat/7.0.42
JVM Version 1.7.0_45-b18

Reports are displaying properly.

**Comment by StavrevaS** [comment]
@DawidCh, did you report the problem as a bug in birt?

**Comment by DawidCh** [comment]
Nope, the bug is already reported. See [comment.](https://github.com/servicecatalog/development/issues/552#issuecomment-276937746)

**Comment by StavrevaS** [comment]
@gertipoppel, we will document how to run birt.

**Comment by DawidCh** [comment]
Birt reports needs to be tested with https setings in configurationsettings.

**Comment by gertipoppel** [comment]
I have added the corresponding information to the Installation Guide. It is currently in review. I will close this issue as soon as I get the information that the documentation is correct now. 
The updated documentation is available in the GlassFish feature branch of the documentation repository.

**Comment by badziakp** [comment]
I tested Birt with https setings and the reports work correct.

**Comment by DawidCh** [comment]
@gertipoppel Are you still waiting for review?

**Comment by gertipoppel** [comment]
Included review comments. New version is available in the GlassFish feature branch of the documentation repository.

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8u121, glassfish 4, build: BES_MASTER_DELIVERY-10192017/04/20 in SAML mode. It is working as expected.
