### ISSUE TITLE
Default for glassfish.domain.JMS_PROVIDER_PORT incorrect

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#553]
[Build] 16.1 fix6 pre-delivery

[Steps to reproduce]
Check oscm-install-pack\domains\bes_domain\glassfish.properties

[Expected result]
Default ports all reflect the same portbase

[Observed result]
8000 and 8100 portbase are mixed

[Defails]
glassfish.domain.JMS_PROVIDER_PORT=8176
uses different portbase than other ports (8000)

**Comment by SylviaDehn** [comment]
Also think about changing the name so it is similar to the ones already defined ....jms..... etc. (if possible)

**Comment by DawidCh** [comment]
[Details of fix]
Modified value of the property. Name will remain the same as it is correlated with the name used in glassfish.

**Comment by SylviaDehn** [comment]
[Version] 2017/02/27 verified, domain base has been corrected
