### ISSUE TITLE
 double port definition in oscm-install-pack\domains\indexer_domain\glassfish.properties

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#554]
[Build] 16.1 fix6 pre-delivery

[Steps to reproduce]
Check oscm-install-pack\domains\indexer_domain\glassfish.properties

[Expected result]
One variable per port should be enough

[Observed result]
glassfish.domain.jms.port=8476 (already exists)
glassfish.domain.JMS_PROVIDER_PORT=8476

[Defails]
Is this really necessary? Or can you use one variable for both?

**Comment by DawidCh** [comment]
[Details of fix]
Unnecessary property has been removed from configuration files.

**Comment by SylviaDehn** [comment]
[Version] 2017/02/27 verified
