### ISSUE TITLE
Ant Build Error

### ISSUE THREAD

**Issue by pujarisat** [servicecatalog/development#557]
Hi  Team,
 i have taken update from mater branch and tying to run all All.BUILD command ,however we are getting below error in console 
_log:
     [echo] build id PRIVATE-BUILD-ON-FCP-18224D-20170206103930
     [echo] host FCP-18224D
     [echo] time stamp 20170206103930
     [echo] ant version Apache Ant(TM) version 1.9.6 compiled on June 29 2015
     [echo] java version 1.7
     [echo]     
_dependencies:

BUILD FAILED
D:\Git\development\oscm-devruntime\javares\devscripts\build-dev-PackageDeploy.xml:163: The following error occurred while executing this line:
D:\Git\development\oscm-build\build.xml:143: java.lang.NullPointerException

do you have made any change in build file ?.

-thanks and Regards
Satling

**Comment by GoebelL** [comment]
That's surprising. Our developers use this target all the time. Could you check if you have got updated everything? oscm-devruntime and oscm-build  must be in-sync.

@StavrevaS 
If it's still unclear, could you take a look to his environment please?

**Comment by pujarisat** [comment]
Hi Team,

There some issue in my local repository and we have resolved issue, now ti's working fine 

-Thanks & Regards
Satling
