### ISSUE TITLE
SSO settings after installation in INTERNAL authentication mode have incorrect defaults

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#558]
[Version]
16.1 fix5+ 2017/02/06

[How to reproduce]
1. Install CTMG with INTERNAL mode authentication. Do not specify any SSO settings in configsettings.properties (settings have "#" at the beginning of line").
2. After installation log in as platform operator and check configuration settings

[Expected result]
No defaults should be shown for all SSO settings after installation with INTERNAL mode. 

[Observed result]
Lots of SSO settings are specified 
e.g. SSO_DEFAULT_TENANT_ID

**Comment by SylviaDehn** [comment]
[Version] 2017/02/27 verified 
Please keep in mind that one of the SSO settings is also used for the custom url (as of fix 6) and will therefore have to be shown starting with fix6

**Comment by SylviaDehn** [comment]
See my comment above

**Comment by SylviaDehn** [comment]
The settings that are used for the custom tab requests are the following:

SSO_SIGNING_KEY_ALIAS=s1as
SSO_SIGNING_KEYSTORE_PASS=changeit
SSO_SIGNING_KEYSTORE=C:/glassfish4/glassfish/domains/bes/config/keystore.jks

These settings should be shown to the platform administrator even if authentication mode is INTERNAL. The platform operator should also be able to change them so we need them in configuration settings.

**Comment by grubskim** [comment]
The three settings Sylvia mentioned are now displayed regardless of the authentication mode.

**Comment by SylviaDehn** [comment]
[Version] 16.1 fix6+ 2017/03/06 verified
