### ISSUE TITLE
Copyright statement in files needs to be updated for install packs

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#560]
[Version]
16.1 fix5+ 2017/02/01

[How to reproduce]
check files in install pack

[Expected result]
2017 copyright statements

[Observed result]
2016 copyright statements

**Comment by grubskim** [comment]
Updated copyrights in all files.

**Comment by SylviaDehn** [comment]
[Version] 16.1 fix6 2017/02/17
verified
