### ISSUE TITLE
install package oscm-aws-install-pack.zip has bad default for GLASSFISH_HOME

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#561]
[Version]
16.1 fix5+ 2017/02/06

[How to reproduce]
1. get app package: 
2. check app-domain\glassfish.properties file

[Expected result]
GLASSFISH_HOME=<path to glassfish>

[Observed result]
GLASSFISH_HOME=C:/glassfish3

[Details]
Check all controller packages

**Comment by DawidCh** [comment]
Fixed in respective commit.

**Comment by SylviaDehn** [comment]
[Version]16.1 prefix7 2017/02/27 verified
