### ISSUE TITLE
Link from a marketplace to the respective admin portal

### ISSUE THREAD

**Issue by mdehn** [servicecatalog/development#562]
With v16.1.3 a user with administrator rights can navigate from a marketplace to the respective admin portal. This functionality is available only when using OSCM with SAML authentication mode in a SSO environment. This functionality is missing with INTERNAL authentication mode.

**Comment by DawidCh** [comment]
I see the link to admin portal from marketplace. Is the user has access to portal provided?

**Comment by mdehn** [comment]
I checked it again with Open Service Catalog Manager 16.1.4 CE UNIT FOR GITHUB RELEASE-68 2016/12/16 and it works fine.
