### ISSUE TITLE
master-indexer-domain server.log filled with too many ERRORS

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#564]
[Version]
16.1 fix5+ 2017/02/06

[How to reproduce]
1. install ctmg
2. carry out normal operations 
3. check server.log of master-indexer

[Expected result]
no ERRORs, almost no WARNINGS

[Observed result]
Filled with too many ERRORS which fill up the log file very fast and are killing disk space.

[Details]
see attached file in last comment

**Comment by SylviaDehn** [comment]
[server.txt](https://github.com/servicecatalog/development/files/757837/server.txt)

**Comment by GoebelL** [comment]
Hugh. Lot's of ConnectException's. The JMS configuration doesn't look healthy.

**Comment by StavrevaS** [comment]
@SylviaDehn, please check the following:
- is the indexer domain is running?
- check the domain.xml of indexer domain, can you find the port 8476?
Maybe the installation of indexer domain configures the JMS port wrong.

**Comment by SylviaDehn** [comment]
You are correct, Suzanna. Indexer domain was not running when I copied the file. So I am changing the bug to ERRORs that are in system.log of master indexer. It is filling up like crazy. 8476 is in domain.xml.

**Comment by SylviaDehn** [comment]
[server.txt](https://github.com/servicecatalog/development/files/760354/server.txt)

**Comment by SylviaDehn** [comment]
![image](https://cloud.githubusercontent.com/assets/15086024/22738429/b204aeb2-ee07-11e6-907d-42613adf8bfd.png)

**Comment by SylviaDehn** [comment]
See log files above and how many are created in written per minute ....

**Comment by SylviaDehn** [comment]
The problem I have, my disk fills up, with master-indexer errors. If I stop the master-indexer, then the disk fills up with bes-domain connect errors .... so the situation is not acceptable

**Comment by StavrevaS** [comment]
@SylviaDehn, please check if <domain_path>/imq/instances/imqbroker/lock file exists when the domain is stopped. If yes, please delete it and start the domain again. Do this for indexer and bes domains.
This can be a reason of the embedded imq broker start problem which is reported in the master indexer log. 

Please test with jdk8u60, I see jdk8u121 in the logs. There maybe other problems with the higher versions.

**Comment by DawidCh** [comment]
[Details of fix]
Default port for jms queue for domains was changed in gl4. So we updated installation process and set up correct port. The connection troubles should not occur again.

**Comment by SylviaDehn** [comment]
Problem still occurs. New logfile is attached. 
[server_log.txt](https://github.com/servicecatalog/development/files/803704/server_log.txt)

**Comment by DawidCh** [comment]
The logs are connected with the issue #568 
This fix is for jms related problems.

**Comment by SylviaDehn** [comment]
The other bug is closed, my original problem report is still valid. Do you want me to open a new bug?

**Comment by SylviaDehn** [comment]
verified 17.2
