### ISSUE TITLE
Support for the Microsoft Edge browser

### ISSUE THREAD

**Issue by mdehn** [servicecatalog/development#57]
Currently OSCM supports the Microsoft Internet Explorer browser version 9 to 11. The Microsoft Edge browser has been released in 2015. Especially in business environments using Windows systems this browser is expected to become more and more popular.
Therefore it is essential that OSCM supports the Microsoft Edge browser.

**Comment by GoebelL** [comment]
We have done some quick tests with OSCM on Microsoft Edge browser. No problem’s have been discovered and we don’t expect bigger issues here. 

@SuessI
Please add the information of edge browser support in the user documentation for 16.0.5.

**Comment by SuessI** [comment]
Added Microsoft Edge to the supported browers in Installation Guide (Section 2.6) as well as a corresponding section in the Release Notes. Will be available with release 16.0.5.
