### ISSUE TITLE
JMS issue while subscribing

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#572]
Hi.
There is exception thrown during subscription. It can be found in jms logs in bes domain. The issue is clearly the one: 
https://java.net/jira/browse/GLASSFISH-21289 - not fixed yet bug.

**Comment by StavrevaS** [comment]
This problem was seen also by web service tests. It is gone, after data service is used to create query for reading configuration, instead of using the configuration singleton bean,

**Comment by DawidCh** [comment]
Fixed in the scope of glassfish4 upgrade process.

**Comment by kwodzynski** [comment]
Checked on Glassfish 4, jdk1.8.0u121, build GLASSFISH4_EE_UNIT-85 2017/04/06 in SAML mode.
I've got no errors with logfile.
