### ISSUE TITLE
Bad English in configsettings.properties comment

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#573]
[Version]
16.1 fix5+ 2017/02/13

[How to reproduce]
1. check 
databases\bes_db\configsettings.properties

[Expected result]
proper english  .... custom tab messages (or the way it is written in manuals)
in # Name of the keypair stored in the keystore used for signing SAML and Customtab messages 

[Observed result]
Customtab messages (see all such entries)

**Comment by SuessI** [comment]
Solved for 16.1.6 - reviewed and improved the descriptions of all new/changed settings

**Comment by SylviaDehn** [comment]
[Version] 16.1 fix 6 2017/02/17
verified
