### ISSUE TITLE
New settings missing in APP configsettings.properties

### ISSUE THREAD

**Issue by SuessI** [servicecatalog/development#575]
[Version]
16.1.6

[Detail]
For issu #533 , new settings were introduced for the configsettings.properties of APP. 
However, I think they are missing in the configsettings.properties file we distribute 
( Source: oscm-app/resources/configsettings.properties )

**Comment by MiethanerR** [comment]
added the missing settings

**Comment by SylviaDehn** [comment]
[Version] 16.1 fix6 2017/02/17
verified
