### ISSUE TITLE
Using Heat Templates with Yaml 

### ISSUE THREAD

**Issue by arjunm183** [servicecatalog/development#576]
Hello Team,

I am using OSCM and i would like to know is there a possibility to use HEAT Templates with yaml format instead of using it with json ( AWS CFN ) Format.

THanks and REgards,
Arjun.M

**Comment by StavrevaS** [comment]
Hello @arjunm183,

you can use yaml heat templates. There are some samples in the [code|https://github.com/servicecatalog/development/tree/master/oscm-app-openstack/resources]. You can read the integration guide how to define the parameters for the templates, or see the sample technical service definitions provided with the templates,

Regards
