### ISSUE TITLE
Active Directory Integration

### ISSUE THREAD

**Issue by arjunm183** [servicecatalog/development#577]
Hello Team,

Can you help me in binding the oscm app with AD .

I Have imported LDAP Settings however it says bind was not successfull.

As far i know there is no place where i can mention the LDAP binddn username and password for binding it.

Kindly help me

Thanks and REgards,
Arjun.M

**Comment by StavrevaS** [comment]
Hello @arjunm183,

please refer to (Operator's Guide)[https://github.com/servicecatalog/documentation/blob/master/Development/oscm-doc-user/resources/manuals/installation+operation/en/Operation.pdf], Appendix C: LDAP Keys.

Regards
