### ISSUE TITLE
Check following files

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#585]
If needed:
1. sun-ejb-jar.xml - all of them
2. requiredGlassfishResources.properties - all of them.

**Comment by DawidCh** [comment]
Check ess version.

**Comment by grubskim** [comment]
Fixed with  597dc95

**Comment by DawidCh** [comment]
Check also all beans.xml files if they have proper descriptor version.

**Comment by grubskim** [comment]
Fixed with 570dd0c
