### ISSUE TITLE
No class def found error

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#586]
Also an ERROR occurs in server.log file . I do not know if this is the same problem:

[2017-02-27T14:48:51.002+0100] [glassfish 4.1] [ERROR] [] [org.hibernate.resource.transaction.internal.SynchronizationRegistryStandardImpl] [tid: _ThreadID=228 _ThreadName=p: thread-pool-1; w: 27] [timeMillis: 1488203331002] [levelValue: 1000] [[
HHH000260: Exception calling user Synchronization [org.hibernate.search.backend.impl.EventSourceTransactionContext$BeforeCommitSynchronizationDelegator@4edc024f] : java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils]]

**Comment by DawidCh** [comment]
The error has not been noticed again.

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8u121, glassfish 4, build: BES_MASTER_DELIVERY-10192017/04/20 in SAML mode. I have been checking it since a few days on different builds. I've got no errors in log file.
