### ISSUE TITLE
index directory for hibernate search is not created

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#587]
[Version]
16.1 fix6+ 2017/02/01

[How to reproduce]

1.    install ctmg
2.    delete db, and upgrade pre GF4 database; start ctmg
3.    check index files 

[Expected result]
all hibernate search index files are created

[Observed result]
hibernate.search.shared.sourceBase=C\\:/glassfish4/masterSourceBase (in my case)
is not found.
slave index directory is created; master index directory is created

**Comment by kowalczyka** [comment]
SylviaDehn could you please check if the issue still exists in the build glassfish4_EE_UNIT#57? 

I was not able to reproduce it but it could have beed related to the #589

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix6+ 2017/03/10 verified. Seems to have been the same problem as #589
