### ISSUE TITLE
update search index does not work as expected

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#588]
[Version]
16.1 fix6+ 2017/02/27

[How to reproduce]

1.   as platform admin, call Operation/Update search index
2.   check if existing index files for master-indexer-domain are deleted, and then recreated

[Expected result]
all hibernate search index files are created/updated

[Observed result]
nothing changes; indexes are not recreated.

**Comment by kowalczyka** [comment]
Issue has been fixed with the commit 81e3091

[Details of fix]
Missing library added.

[Fixed build]
glassfish4_EE_UNIT#57

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix6+ 2017/03/10 verified
