### ISSUE TITLE
Wrong message for JDK during installation ctmg

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#590]
[Version]
16.1 fix6+ 2017/03/02

[How to reproduce]

1. call 
ant -f build-glassfish.xml SETUP

[Expected result]
correct message stating which jdk version should be used.

[Observed result]
Make sure that JAVA_HOME points to 1.7, 64 bit JDK

[Details]
see screenshot

**Comment by SylviaDehn** [comment]
![jdk](https://cloud.githubusercontent.com/assets/15086024/23506195/4b5016ce-ff47-11e6-8f9b-16a3dd286b7f.jpg)

**Comment by SylviaDehn** [comment]
Please take care of similar cases .... app installation

**Comment by DawidCh** [comment]
I have searched the string in all files in project. Only one occurrence has been found.

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix6+ verified for bes, app
