### ISSUE TITLE
Warning messages in bes server.log

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#592]
[Version]
16.1 fix6+ 2017/03/02

[How to reproduce]
1. install with GL4 version
2. use existing db and upgrade
3. after domain start check bes server.log

[Expected result]
server.log contain only "good" messages

[Observed result]
lots of messages indicating that some jars:
e.g.
FileNotFoundException: C:\glassfish4\glassfish\domains\bes\applications\oscm\lib\..\modules\javax.batch-api.jar (The system cannot find the path specified)

[Details]
These messages make me feel worried about the system.
see attached logfile.

**Comment by SylviaDehn** [comment]
[server_logMar03.txt](https://github.com/servicecatalog/development/files/821217/server_logMar03.txt)

**Comment by DawidCh** [comment]
[Details of fix]
Packaging was modified and gl-client.jar is removed from libraries of ear.

**Comment by kwodzynski** [comment]
Checked on Glassfish 4, jdk1.8.0u121, build GLASSFISH4_EE_UNIT-85 2017/04/06 in SAML mode.
Such errors do not occur.
