### ISSUE TITLE
wrong defaults in configsettings.properties file

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#593]
[Version]
16.1 fix6+ 2017/03/06

[How to reproduce]
1. during installation configsettings.properties file have to be adapted for bes and app
2. the defaults are usually stated (even if the property is a comment)

[Expected result]
defaults are stated in files:
\# KEY_FILE_PATH=./key

[Observed result]
\# KEY_FILE_PATH=<path>/key

**Comment by grubskim** [comment]
Checked all install packs. Paths are correct: for oscm-install-pack it's <path>/key, for others it's ./key.

**Comment by grubskim** [comment]
Changed path in oscm-install pack to ./key

**Comment by SylviaDehn** [comment]
@gertipoppel Please check if doc mentions the default value. Change accordingly

**Comment by gertipoppel** [comment]
The documentation states that the default in the configsettings.properties file is ./key 
and that the default location is 
<GLASSFISH_HOME>/glassfish/domains/app-domain/config and
<GLASSFISH_HOME>/glassfish/domains/bes-domain/config

**Comment by kwodzynski** [comment]
Windows Server 2016, jdk1.8u131, build BES_MASTER_UNIT-1897 2017/07/26 in SAML mode.
In the file configsettings.properties and in documentation the value is correct.

**Comment by kwodzynski** [comment]
Retested on Windows Server 2016, jdk1.8u131, build BES_MASTER_UNIT-1904 2017/07/27 (official 17.3.0) in SAML mode. 
In the file configsettings.properties and in documentation the value is correct.
