### ISSUE TITLE
Weird APP_SUSPEND value in configurationsettings table of app db

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#595]
[Verson] 16.1 fix6+ 2017/03/06
[How to reproduce]
1. install APP/AWS
2. with db tool look at configurationsettings table of app db

[Expected result]
APP_SUSPEND has true or false as value

[Observed result]
APP_SUSPEND has value changeIt

[Details]
Have you checked if APP_SUSPEND functionality still works? Please check

**Comment by SylviaDehn** [comment]
Please also check MASTER branch fix 6

**Comment by grubskim** [comment]
Changed APP_SUSPEND to default to false instead of changeIt. This issue is also on master branch, will fix after code freeze.

**Comment by GoebelL** [comment]
Hi @grubskim 
>This issue is also on master branch, will fix after code freeze.
Please create a pull request for the fix in master today.

**Comment by grubskim** [comment]
@GoebelL 
As i said in my email from 17.03, i have tested this functionality:

> I have tested restarting the domain with different values in APP_SUSPEND.
In general, the domain can be started no matter what value is in there – true/false/any string.
When its set to true, on domain start it gets changed to false, that is the only thing I noticed.
Please let me know if I should merge to master.

**Comment by GoebelL** [comment]
@grubskim Please merge to master.

**Comment by grubskim** [comment]
Change is in master.

**Comment by SylviaDehn** [comment]
verified 17.1
