### ISSUE TITLE
Fix before gl4 release

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#599]
1. Revert ID.xls file from commit 901cea223e08afa208806183cb796c0d25b81802
2. Test TaskQueueServiceBean using injected jms resources (revert commit 7b503524efe0542324a9ca5647967eab89b9b836)
3. Uncomment and merge REST api (6c0055a99ad4ef666cce9819587f0e634ccc16eb)

**Comment by grubskim** [comment]
Merged REST API to glassfish 4 branch.

**Comment by DawidCh** [comment]
Ad1 - moved to #619 
Ad2 - tested and did not helped to #563 
Ad3 - REST API merged, now need to be tested but in #621
