### ISSUE TITLE
deleting custom attributes for subscriptions does not delete custom attributes for existing app service instances

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#601]
[Version]
16.1 fix6+ 2017/03/14

[How to reproduce]
1. with 16.1 fix3 create aws subscription, with defaults for e.g. INSTANCE_TYPE defined in Tech. Service. Encrypted parameters e.g. INSTANCE_TYPE are defined by supplier
2. upgrade to 16.1 fix5 delete all subscription and customer specific custom attributes, that are controller specific
3. upgrade to 16.1 fix6+ (probably has nothing to do with error)
4. check app database for deleted subscription custom attributes

[Expected result]
deleted subscription custom attributes no longer exist

[Observed result]
deleted subscription custom attributes still exist

[Details]
If I look at the instanceattribute table of the app db, I find all my encrypted parameters still exist for the 
subscription. Shouldn't they have been deleted when I deleted the (encrypted) customer and subscription  custom attributes?

**Comment by MiethanerR** [comment]
adapted the saving method for instance attributes in app

**Comment by SylviaDehn** [comment]
@MiethanerR: please explain the custom attribute handling at time of delete. Also if this needs to be documented.

**Comment by MiethanerR** [comment]
@SylviaDehn The custom attributes (independent of customer or subscription attribute) are updated on update or upgrade of the subscription. Now, additionally to adding new attributes, old ones are also deleted.
