### ISSUE TITLE
Japanese translations missing

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#61]
Date: 2016/05/09

[Steps to reproduce]
Check \oscm-portal\javares\org\oscm\ui\resources\Messages_ja.properties and \oscm-doc-user\resources\faq\ja\faq.html in documentation

[Expected result]
Translations existing for new search sections in Japanese FAQ and for marketplace.searchSubscriptions in Japanese message bundle 

[Observed result]
No translations exist.

**Comment by redmond2683** [comment]
Translated the sections into Japanese in cde2966

**Comment by SylviaDehn** [comment]
[Build] 2016/08/11 verified
