### ISSUE TITLE
Multitenancy: Supplier can't publish service in marketplace of different tenant he has access to

### ISSUE THREAD

**Issue by MiethanerR** [servicecatalog/development#610]
[Version]
16.1 fix6+ 2017/03/15

[How to reproduce]
1. Configure default tenant (D) and one additional tenant (A)
2. Create Supplier in D
3. Create Marketplace Owner and Marketplace in A
4. Create Service with Supplier in D
5. Configure Publish Options for Service in D

[Expected result]
service can be publish on Marketplace in A

[Observed result]
Marketplace in A is not in the option list

**Comment by MiethanerR** [comment]
@mdehn Might this be intended?

**Comment by mdehn** [comment]
Yes, this is currently the intended behavior.

**Comment by mdehn** [comment]
Even though this was the original implementation, we need to support multi-tenant scenarios in which a supplier can publish services on marketplaces of other tenants.

**Comment by MiethanerR** [comment]
fixed. Removed the restriction for publishing per tenant.

**Comment by GoebelL** [comment]
@MiethanerR 
I am missing the commit link. I assume your are referring to your pull request #600? For better tractability, I advice you to use respective [closing commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/). It's convenient and common practice.

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8u121, build BES_MASTER_DELIVERY-10192017/04/20 in SAML mode. It is working as expected

**Comment by elfriedegoetz** [comment]
BES_MASTER_UNIT-17552017/05/16

**Comment by elfriedegoetz** [comment]
The scenario above dos not work for closed marketplace ( see comment mdehn 30 Mar above). If the marketplace will be closed all supplier have to be listed to choose for access. But only the supplier of the related tenant are listed. So it is not possible to publish services to marketplaces with different tenant

**Comment by MiethanerR** [comment]
@elfriedegoetz I can not reproduce this. Also the list on the "Manage Sellers" page does only show the excluded sellers not all available ones.

**Comment by elfriedegoetz** [comment]
No, Marketplace -> manage access it is not possible. "Manage Sellers" is not the write menue

**Comment by MiethanerR** [comment]
@elfriedegoetz this is the intended behavior. Only customers of the tenant can login into a marketplace and so only the access for these customers has to be restricted by the owner.

**Comment by MiethanerR** [comment]
The query for viable marketplaces for publishing a service takes the customer access restriction into account. This has to be removed.

**Comment by elfriedegoetz** [comment]
reproduce the error:
step 1: Login as Administrator/MPL owner
step 2: go to Manage Access and choose a MPL1 from Tenant1
step 3: click Authorized customers only  ( only organisation of the own tenant are listed)
step 4: go to Update marketplace
step 5: choose MPL1
step 6: Authorized sellers only is disabled ( all sellers are allowed)
step 7: Login as Supplier SP belongs to Default tenant
step 8: try to publish to MPL1
-- MPL1 are not listed

**Comment by MiethanerR** [comment]
Adjusted query for viable marketplaces.

**Comment by elfriedegoetz** [comment]
Note: You can close the marketplace for customers with " Manage Access" or/and close the marketplace for supplier with "Update marketplace".  " Manage Access" should not have any impact for supplier.
With Master_unit 1773 it works fine. see scenario above
