### ISSUE TITLE
Multitenancy: Can't self-register user if same name exists already in different tenant

### ISSUE THREAD

**Issue by MiethanerR** [servicecatalog/development#612]
[Version]
16.1 fix6+ 2017/03/15

[How to reproduce]
1. Configure default tenant (D) and one additional tenant (A)
2. Create user in D with name "test"
2. Create Marketplace Owner and Marketplace in A
3. Login into Marketplace in A and try to self-register a new customer with user name "test"

[Expected result]
registration is successful

[Observed result]
Error: User already exists

**Comment by SylviaDehn** [comment]
@MiethanerR : what do you mean by self-register? The customer admin adds a new user?
I tried this with a customer admin who adds a new user that already exists in default tenant, and had no problem.
Self-Registration is not permitted with SAML_SP at the marketplace.

**Comment by SylviaDehn** [comment]
see self-registration issue https://github.com/servicecatalog/development/issues/408

**Comment by MiethanerR** [comment]
Gerti also told me. I tried to fix it and the initial problem was solved but after that I was confronted with more fundamental issues with self-registration. Dropping this issue.
