### ISSUE TITLE
Multitenancy: register customer for non-default tenant

### ISSUE THREAD

**Issue by MiethanerR** [servicecatalog/development#617]
[Version]
16.1 fix6+ 2017/03/15

[How to reproduce]
1. Configure default tenant (D) and one additional tenant (A)
2. Create user in D with name "test"
3. Create Marketplace Owner and Marketplace in A
4. Register new customer with user name "test" for Marketplace in A

[Expected result]
registration is successful

[Observed result]
Error: User already exists

**Comment by MiethanerR** [comment]
fixed and merged. #631 was found during bugfixing.

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8u121, build BES_MASTER_DELIVERY-10192017/04/20 in SAML mode. Registration of new user as described above is successful.
