### ISSUE TITLE
Import Heat templates

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#618]
OSCM OpenStack integration needs to provide for uploading heat templates.
Cloud admins / technology manager in OSCM need to use their own provisioning templates. Currently there are two options: Either they provide such templates on external host (referencing with URL in the technical service), or the OSCM operator provides them on the host file system. Both options are not applicable for case OSCM is provided to them as-a-service and operated in a separate network.

**Comment by mdehn** [comment]
Provide functionality for a user with the respective technology manager permissions 

    upload new templates,
    list uploaded templates,
    remove templates. 

When defining a technical service such templates can be referenced.
When provisioning the respective service the referenced template must be used.

**Comment by MiethanerR** [comment]
feature finished and merged to master
