### ISSUE TITLE
Japanese translation is missing

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#62]
Date: 2016/05/10

[Steps to reproduce]
Translate please entry:
marketplace.searchSubscriptions=Search subscriptions
from file:
oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties

[Expected result]
Translation existing for new search feature

[Observed result]
No translations exist.

**Comment by GoebelL** [comment]
Duplicate with issue #61.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/10 verfied
