### ISSUE TITLE
Test Rest API

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#621]
Test rest API

**Comment by MiethanerR** [comment]
I tested the REST API with a local build and it worked. It still showed some warnings in the logs about non-loading classes. After some research I found out that also others have this problem but could find any valid solution.

**Comment by DawidCh** [comment]
The endpoints:
GET/POST: https://<host>:<port>/oscm-trigger/v1/triggers
GET/PUT/DELETE: https://<host>:<port>/oscm-trigger/v1/triggers/{id}

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8u121, build BES_MASTER_DELIVERY-10192017/04/20 in Internal mode. It is working as expected.
