### ISSUE TITLE
change page message unnecessary when saving payment info

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#63]
Version: 16.0.3+
Date: 2016/05/09
[Test category] creative

[Steps to reproduce]
0. as platform operator (administrator), set set HIDE_PAYMENT_INFORMATION=true
1. log in as supplier
2. go to Customer/Manage payment types (see warning that "Payment types are not used on this platform" .... OK)
3. change a payment type anyways, and press save. 
-> message is displayed that payment types have been saved ... OK
4.  click on any other menu item

[Expected result]
newly chosen menu item is displayed

[Observed result]
dialog box with "You have unsaved changes that will be lost if you continue.
Click OK to confirm."

[Details]
I press OK, and leave go to the other menu item, and my changes are saved anyways (good). So really just the dialog with the unsaved changes message is out of place.

**Comment by kowalczyka** [comment]
[Details of fix]
Added missing default value for page being dirty.

**Comment by SylviaDehn** [comment]
verified 16.0 fix6 0607.2016
