### ISSUE TITLE
Installer APP: separate http listener for web services (SOAP)

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#634]
In some operational environments it is necessary to have a separate certificate for the SOAP communication between OSCM and APP. 
In the cloud environments, the cloud admin is responsible to import a valid certificate for the host of the applications (https access to OSCM/APP/Controller UI via browser).

The communication between OSCM and APP is not necessarily via public network. Further more, APP authenticates the OSCM instance using certificates (CLIENT-CERT authentication for SOAP). The internal host name of APP may not be equal to the public one. In that case the authentication will fail, if the admin doe not provide separate certificates for the public and internal communication.

For the Glassfish configuration, it means that there is a need for additional secure http listener.

Current installation has 2 http listeners:

- http-listener-1, port 8880
- http-listener-2, port 8881, ssl enabled, cert-nick s1as

A new listener should be added:

 - http-listener-3, port 8882, ssl enabled, cert-nick s1as

The admin can configure later, which secure listener will be used for the web services and choose another cert-nick for the listener dedicated to the web part (UI).

**Comment by c-yan** [comment]
> cert-nick sa1s
Is not s1as typo?

**Comment by StavrevaS** [comment]
Corrected typo.

**Comment by StavrevaS** [comment]
@gertipoppel we have added additional glassfish property for APP - glassfish.domain.WS_PORT_SECURE with default value 8882. It gives the possibility to use separate listeners for SOAP communication and specify separate certs from the one used for web. Please document this accordingly.

**Comment by gertipoppel** [comment]
Added the following to the APP documentation (topic - Setting up the Application Server Resources): 

Depending on your environment, it may be required to provide separate certificates for external and internal communication between CT-MG and APP. In this case, you can use the secure HTTP listener port (default: 8082).

In addition, added to the description of the GlassFish configuration settings: 

glassfish.domain.WS_PORT_SECURE
The port used for a secure HTTP listener for Web service connections of the application server. 
In some operational environments it is required to use separate certificates for the SOAP communication between OSCM and APP and for Web browser access, i.e. separate certificates for internal and external communication must be provided. 
Default: 8082

Changes are available in the fb_GF4 branch of the documentation repository.
