### ISSUE TITLE
security group and subnet parameters for AWS can be specified but have not effect

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#642]
[Version]
16.1 fix7 2017/03/17

[How to reproduce]

1. when provisioning, specify subnet or security group for aws service
2. look at created instance on aws

[Expected result]
the parameters specified should be reflected in the created aws resource

[Observed result]
values used in aws are default

[Details]
In logfiles I see that the parameter values are sent to app by bes domain. I cannot find the parameters
after that. To me it looks like app ignores them.
When I look at the Service instance operation page of aws controller, and click on the subscription, I find my parameters. But they never get sent to AWS.

**Comment by SylviaDehn** [comment]
[TechnicalService_AWS_161f7_SecGroup_xml.txt](https://github.com/servicecatalog/development/files/889537/TechnicalService_AWS_161f7_SecGroup_xml.txt)

**Comment by SylviaDehn** [comment]
At FT time of US-8617 US-1618 these features were OK for AWS.

**Comment by skulle** [comment]
Hi, I am also interested in this fix since I am using the AWS controller for CT-MG IaaS demos. Can anyone tell me what the target milestone will be for the fix?

**Comment by MiethanerR** [comment]
I checked and found that your tech. service uses the old, lower case parameters. These have been updated to upper case. I updated the service and tested it. Both subnet and sec group are configured correctly in AWS.

**Comment by SylviaDehn** [comment]
@MiethanerR Is this correct? Is it no longer compatible with previous versions? So we cannot use existing services?

**Comment by MiethanerR** [comment]
https://github.com/servicecatalog/development/releases/tag/v16.1_Fix6

These parameters were introduced with 16.1.4 and updated with 16.1.6 with no backward compatibility.

**Comment by SylviaDehn** [comment]
Previous versions of services are upgraded my an sql script. New services imported have to be correct. Otherwise this feature will fail. 
Verified.
