### ISSUE TITLE
birt installed to bes-domain with GF4

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#647]
[Version]
16.1 fix6+ 2017/04/03

[How to reproduce]
1. install oscm-install-pack.zip

[Expected result]
birt is not installed to bes-domain

[Observed result]
birt is installed to bes-domain

[Details]
To my knowledge birt does not work with GF4 if installed to the same application server as CTMG. So I believe it makes no sense to automatically installed it there.

**Comment by SylviaDehn** [comment]
If we deliver birt, then it should be described where to find birt in order to deploy it to a different application server.
@gertipoppel Please keep track of this bug

**Comment by gertipoppel** [comment]
For **OSCM**, the Installation Guide states: 

CT-MG uses BIRT to generate reports. BIRT is not included in the CT-MG packages. To be able to generate reports, you need to obtain and manually deploy BIRT on your own.
BIRT needs to be deployed on a different application server than CT-MG. The following application servers are supported:
Oracle GlassFish Server, version 3
Apache Tomcat, version 8
Proceed as follows:
1. Download the latest version of Eclipse BIRT runtime, for example, from http://www.eclipse.org.
2. Deploy the birt.war archive to a domain on the GlassFish 3 or Tomcat application server. 
3. Add the CT-MG report designs and localized labels to the folder of the birt application on the application server. 
The CT-MG report designs and labels are available in the following archive provided for each release: oscm-reports.zip. 
Extract the contents of this archive to the root folder of the birt application:
<GLASSFISH3_HOME>/glassfish/domains/<domain>/applications/birt or
<TOMCAT_HOME>/webapps/birt.
4. Restart birt.

Each time you install a new release of CT-MG, you should also check for new releases of BIRT and changes in the CT-MG report designs and labels and update them as required. 

For **ESCM**, the Installation Guide states: 

CT-MG uses BIRT to generate reports. BIRT is included in the CT-MG packages. BIRT needs to be deployed on a different application server than CT-MG. The following application servers are supported: 
Oracle GlassFish Server, version 3
Apache Tomcat, version 8
To be able to generate reports, proceed as follows:
1. Deploy the birt.war archive located in <install_pack_dir>/domains/bes_domain/applications to a domain on the GlassFish 3 or Tomcat application server.
2. Restart birt.

**Comment by gertipoppel** [comment]
Sorry, for OSCM CT-MG is obviously OSCM (this is a condition in our XML source files...)

**Comment by SylviaDehn** [comment]
Sorry, this is really an ESCM bug. I will close it and move it to Bugzilla

**Comment by SylviaDehn** [comment]
verified (ESCM issue)
