### ISSUE TITLE
Improve messages when setting the pwd

### ISSUE THREAD

**Issue by mdehn** [servicecatalog/development#649]
Reported by Govind K. Mane:
When password criteria are not met the error message should be clearer, e.g. "Your password does not meet the criteria, please re-enter your password."
The message displayed with successful  account creation rather than saying "password setting completed" should say e.g. "Your account password has been successfully created."

**Comment by GoebelL** [comment]
I guess some generic error messages like "invalid input" are given here, which are applied by default to all input components. So that's probably not solvable by just rephrasing them. To hit the mentioned use cases, it may require dedicated JSF validators with separate error handling.

Please check.

**Comment by SylviaDehn** [comment]
I think a good idea would be also to have 2 fields when setting the password, "re-enter" password, to make sure that the correct password is set.

**Comment by digitalfishpond** [comment]
@mdehn , @SylviaDehn  What is the process for reproducing? The 'set password' fields that I have found do not fit this description.

**Comment by mdehn** [comment]
Govind Mane to comment.

**Comment by govindmane23** [comment]
Whenever any new user account build in catalog manager, it sent email notification to respective user to reset the password. Also if any existing customer want reset his/her password, email notification received to respective user to reset the password. This email has a link to access reset password page. On password rest page, user need to enter the userid, new password and retype of password. This is a page were validation is not taken care in case password criteria doesn’t meet, also on successful password reset message should be some meaning. I seems, given message has some meaning and it gives generic understanding on user action to reset password.

**Comment by DawidCh** [comment]
The issue is not in the code of catalog manager application.
