### ISSUE TITLE
Subscription process "Previous" button does not work correctly

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#65]
Version: 16.0.3+
Date: 2016/05/09
[Test category] creative

[Steps to reproduce]
1. as platform operator (administrator), set set HIDE_PAYMENT_INFORMATION=true
2. as customer subscribe to service with costs
3. check "previous" button at each step

[Expected result]
should always bring me back to last page

[Observed result]
If I press previous button on last confirm page, an error message shows up for a fraction of a second, and then I am redirected to Account/Subscriptions page

[Details]
Please check similar issues

**Comment by SylviaDehn** [comment]
what is the status here? The same type of error was found in the last KENSA. It would not look good if
the error is not fixed.

**Comment by kowalczyka** [comment]
[Details of fix]
Subscription wizard has been updated to manage this issue when payment step is omitted.

**Comment by SylviaDehn** [comment]
16.0 fix6 verified
