### ISSUE TITLE
The search results displayed in the screen delayed for a period of time

### ISSUE THREAD

**Issue by wangyingfnst** [servicecatalog/development#66]
Date: 2016/05/06 
[Test category]: creative Test

[Steps to reproduce]
1. Log in marketplace as customer;
2. Select a service to make a subscription with the "test1" as subscription name and assign customer to this subscription;
3. Click on "MY SUBSCRIPTIONS", then input "test1" into the search box and click on the search button;
4. Click on "ACCOUNT->Subscription", then modify the subscription name from "test1" to "test2";
5. Click on "MY SUBSCRIPTIONS", then input "test1" into the search box and click on the search button.

[Expected result]
In step 3, the "test1" should be displayed in the screen;
In step 5, no subscription should be displayed in the screen.

[Observed result] 
In step 3, a period of time would have to pass before the "test1" can be displayed;
In step 5, the "test1" still can be displayed, and must after a period of time, there will be no subscription displayed.

**Comment by StavrevaS** [comment]
There is a delay between an OSCM operation and indexing. It is an expected behavior and cannot be changed.
This bug is invalid
