### ISSUE TITLE
APP: Make Java keystore location configurable

### ISSUE THREAD

**Issue by shimizuf** [servicecatalog/development#668]
Currently the locations of the Java keystores keystore.jks and cacerts.jks in the file system are hard coded in APP. This means that they cannot be placed in a different directory by the operator. Please make the location configurable.

**Comment by StavrevaS** [comment]
Can you explain why do you want to move the keystores on other location?

**Comment by MiethanerR** [comment]
Since a operator has to able to use his own keystores (because of exchanging certs etc.), in kubernetes he can store these in a "secret" which is simply a mountable folder. We need to be able to set the path to this folder in the container to use the custom keystores.

**Comment by StavrevaS** [comment]
Please analyze if overwriting the setting in domain.xml can solve this issue.

**Comment by shimizuf** [comment]
Setting the location in domain.xml is not sufficient for the APP domain. If the setting in domain.xml is adjusted and the keystores are in a custom location, the trust between the APP and BES domains fails.

**Comment by StavrevaS** [comment]
Do you have some error logs? I am not aware that we have hard-coded paths in the APP code. @MiethanerR maybe you know more?

**Comment by shimizuf** [comment]
I'll provide error logs tomorrow.

As for the APP code, I'll discuss with @MiethanerR and we'll provide that info asap.

**Comment by shimizuf** [comment]
How to reproduce in APP:
* Put custom keystores keystore.jks and cacerts.jks in a different directory, e.g. /opt/jks
* Configure keystore locations in domain.xml to point to the custom keystores
* Remove the default, automatically generated keystores in the domain's config directoy

Result: Glassfish does not start up.

`INFO: JVM invocation command line:
-XX:+UnlockDiagnosticVMOptions
-XX:MaxPermSize=512m
-XX:PermSize=128m
-XX:NewRatio=2
-Xmx1024m
-server
-javaagent:/opt/glassfish3/glassfish/lib/monitor/flashlight-agent.jar
-Dfelix.fileinstall.disableConfigSave=false
-Dproduct.name
-Dsun.java2d.print.polling=false
-Djavax.net.ssl.keyStore=/opt/jks/app/keystore.jks
-Djava.awt.headless=true
-Dfelix.fileinstall.poll=5000
-Djava.endorsed.dirs=/opt/glassfish3/glassfish/modules/endorsed:/opt/glassfish3/glassfish/lib/endorsed
-Dfelix.fileinstall.bundles.startTransient=true
-Djavax.net.ssl.trustStore=/opt/jks/app/cacerts.jks
-Dcom.sun.enterprise.security.httpsOutboundKeyAlias=s1as
-Dorg.apache.catalina.loader.WebappClassLoader.ENABLE_CLEAR_REFERENCES=false
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Djava.security.auth.login.config=/opt/glassfish3/glassfish/domains/app-domain/config/login.conf
-Dgosh.args=--nointeractive
-Dfile.encoding=UTF8
-Dosgi.shell.telnet.maxconn=1
-Djdbc.drivers=org.apache.derby.jdbc.ClientDriver
-Dfelix.fileinstall.dir=/opt/glassfish3/glassfish/modules/autostart/
-Dsun.net.inetaddr.ttl=3600
-Dosgi.shell.telnet.port=8866
-Djava.security.policy=/opt/glassfish3/glassfish/domains/app-domain/config/server.policy
-Dfelix.fileinstall.log.level=2
-Dcom.sun.aas.instanceRoot=/opt/glassfish3/glassfish/domains/app-domain
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-Dosgi.shell.telnet.ip=127.0.0.1
-Dcom.sun.aas.installRoot=/opt/glassfish3/glassfish
-Djava.ext.dirs=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.131-2.6.9.0.el7_3.x86_64/lib/ext:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.131-2.6.9.0.el7_3.x86_64/jre/lib/ext:/opt/glassfish3/glassfish/domains/app-domain/lib/ext
-Dfelix.fileinstall.bundles.new.start=true
The Master Password is required to start the domain.  No console, no prompting possible.  You should either create the domain with --savemasterpassword=true or provide a password file with the --passwordfile option.
Command start-domain failed.`

**Comment by shimizuf** [comment]
Other variants:
1) Default keystores exist in config directory but have a differing storepass:
`[...]Caused by: java.lang.IllegalStateException: java.io.IOException: Keystore was tampered with, or password was incorrect[...]`

2) Default keystores exist in config and have the same storepass as the custom keystores:
Domain starts up but later trust cannot be established between BES and APP.

@StavrevaS: I can provide additional logs for these cases but reproducing is time consuming. Please tell me if you need these as well.

**Comment by StavrevaS** [comment]
@shimizuf I assume there is a glassfish configuration problem here.

**Comment by shimizuf** [comment]
Did more testing. The table configuration setting contain keystore locations in the following databases:
* BES: keystore.jks and cacerts.jks
* APP: cacerts.jks

I replaced these with the absolute paths of our custom keystores. Custom keystores also specified in the domain.xml files. Tested these scenarios:

1. Domain config directory contains the same custom keystores
-> Everything works

2. Domain config dir contains default keystores (different storepass, no added certs)
-> BES and APP startup fails with the following exceptions.

BES:
> Caused by: java.lang.IllegalStateException: java.io.IOException: Keystore was tampered with, or password was incorrect
>         at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.loadStores(SecuritySupportImpl.java:217)
>         at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.initJKS(SecuritySupportImpl.java:150)
>         at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.<init>(SecuritySupportImpl.java:122)
>         at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.<init>(SecuritySupportImpl.java:117)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
>         at java.lang.Class.newInstance(Class.java:383)
>         at com.sun.hk2.component.ConstructorCreator.create(ConstructorCreator.java:65)
>         ... 47 more

APP:
> Caused by: java.lang.IllegalStateException: java.io.IOException: Keystore was tampered with, or password was incorrect
>         at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.loadStores(SecuritySupportImpl.java:217)
>         at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.initJKS(SecuritySupportImpl.java:150)
>         at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.<init>(SecuritySupportImpl.java:122)
>         at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.<init>(SecuritySupportImpl.java:117)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
>         at java.lang.Class.newInstance(Class.java:383)
>         at com.sun.hk2.component.ConstructorCreator.create(ConstructorCreator.java:65)
>         ... 56 more

3. Domain config dir contains no keystore files (only the custom keystores in another directory exist)
-> BES and APP domains fail to start with the following messages.

BES:

> The Master Password is required to start the domain.  No console, no prompting possible.  You should either create the domain with --savemasterpassword=true or provide a password file with the --passwordfile option.

APP:

> The Master Password is required to start the domain.  No console, no prompting possible.  You should either create the domain with --savemasterpassword=true or provide a password file with the --passwordfile option.

**Comment by shimizuf** [comment]
In scenario 3 (no keystore files in domain config dir), also tried to add the master-password file into the same directory as the custom keystores. Same error, the Glassfish domains cannot start:

> The Master Password is required to start the domain.  No console, no prompting possible.  You should either create the domain with --savemasterpassword=true or provide a password file with the --passwordfile option.

**Comment by shimizuf** [comment]
Also tried to adjust the keystore locations in the domain.xml files for both servers, including default. Same error:

> The Master Password is required to start the domain.  No console, no prompting possible.  You should either create the domain with --savemasterpassword=true or provide a password file with the --passwordfile option.
> Command start-domain failed.

**Comment by StavrevaS** [comment]
Probably we are facing the known glassfish issue:
https://java.net/jira/browse/GLASSFISH-18173

**Comment by shimizuf** [comment]
Agreed, we seem to be hitting the Glassfish issue. Please close.
