### ISSUE TITLE
Installation of bes-domain causes SEVERE errors

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#672]
[Build] 16.1 fix7 06.04.2017

[Steps to reproduce]
1. fill out properties files for ctmg installation
    call ant -f build-db initDB
    call ant -f build-glassfish.xml SETUP

[Expected result]
no SEVERE errors in logfile

[Observed result]
SEVERE errors in server.log

[Details]
This error occurs several times:
[2017-04-06T10:55:55.550+0200] [glassfish 4.1] [SEVERE] [] [javax.resourceadapter.mqjmsra] [tid: _ThreadID=19 _ThreadName=RunLevelControllerThread-1491468880634] [timeMillis: 1491468955550] [levelValue: 1000] [[
  Unable to generate UID:[C4060]: Login failed:  user=guest, broker=localhost:8176(54107)]]

**Comment by DawidCh** [comment]
Closed as duplicate of #671

**Comment by SylviaDehn** [comment]
verified 16.1 fix7 final delivery
