### ISSUE TITLE
Installation or documentation of upgrade to GF4 version should be clarified

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#673]
[Build] 16.1 fix7 06.04.2017

[Steps to reproduce] 
(as described by documentation currently)
1. Backup db and key files for GF3 bes and app domain
1.1 Update app and bes DBs
2. Install new application server
3. Install bes
4. install app
5. exchange certificates
5. copy key files to new bes and app domain, restart domains

[Expected result]
installation of both domains is successful

[Observed result]
app domain installation fails

[Details]
The reason for this (I believe) is that the app tries to contact bes with the credentials in app DB which are encrypted. But since the new installation creates a new key file in the config directory and cannot use it to encrypt the passwords already stored in the DB, the installation fails.

There are more ways to solve this. 
1. make sure (document installation instructions) customer uses updateDB of app with settings having the original passwords, **not** encrypted passwords. Call updateDB before SETUP of glassfish domain.
(e.g. _crypt:secretpwd)
2. change the the app_db/configsettings.properties files to specify the key file name with location outside 
the domain (where the customer saved a backup of the file). Then install.
3. change the installation to take a parameter where the key file is stored and installation copies it to 
<app-domain>/config/key
4. or document to backup db and delete db and do a new installation for app (which is almost like 1. only takes longer) 

My favourite: document "1."  Since the installer will soon become obsolete anyways (containers etc), and this is a one time task, the effort should be minimized

NOTE: this is only a problem for app domain. Not for bes domain. bes installation is successful without a problem and key file backup can be copied to config directory and domain can be restarted.
One should also think about the bes domain too, and check if the instructions should be standardized.

@StavrevaS : as discussed please clarify what should be done.

**Comment by SylviaDehn** [comment]
@gertipoppel please check what Suzana decides

**Comment by StavrevaS** [comment]
Go for alternative 3, the issue cannot be solved for APP per documentation (even if we solve the encrypted passwords as in alternative 1, the custom attributes in the APP database still remain encrypted with the old key).
Dev:
Add copying the old key from existing location in the installer package. Do it for OSCM and APP.
Docu:
Describe this in update installation for OSCM and APP.

**Comment by badziakp** [comment]
For now I implemented it as followed:
1. User has to build oscm-app-install-pack and copy key file from the old domain into oscm-aws-install-pack\domains\app_domain\installer
2. Run glssfish setup

[Observed result]
Installation script was executed successfully

I have a few questions to this solution:
1. Should installation script always fail if the key file was not copied to oscm-aws-install-pack\domains\app_domain\installer ?
2. Should I add new param to configsettings.properties (for app and bes) to let user to define path from where key file can be copied? Or oscm-aws-install-pack\domains\app_domain\installer can stay fixed?

**Comment by StavrevaS** [comment]
Let the path fixed. The installer should not fail by missing key file, because by the first installation there is no key file.

**Comment by badziakp** [comment]
[Details of fix]
If operator wants to install app on existing app database, he needs to copy "key" file from the old domain config directory to installer directory in extracted install-pack.
If "key" file exists in the installer directory it will be copied to the newly created domain config directory.
If "key" file doesn't exist in the installer directory, installation process is executed as it was before.

**Comment by gertipoppel** [comment]
Is the same procedure applied when updating OSCM on an existing BES database?

**Comment by badziakp** [comment]
Installation of bes domain worked also before my implementation but I think the procedure from my last comment should be recommended for bes domain as well.

**Comment by StavrevaS** [comment]
There should be the following hint in the documentation. It is possible that the operator has changed the default key file path (./key) in the configuration settings. The installation does not read the database, and expects the default location. So the operator should provide the default key path prior to the installation (update config settings).

**Comment by SylviaDehn** [comment]
verified with 17.0
