### ISSUE TITLE
Cluster set up

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#675]
Check if set up as cluster works after glassfish 4 migration.

**Comment by StavrevaS** [comment]
@DawidCh, we do not support glassfish cluster setup, but deployment of independent glassfish nodes for failover. Please close this issue if the glassfish cluster is what you mean.

**Comment by GoebelL** [comment]
I agree to @StavrevaS  
@DawidCh 
I close this. If you meant something else, please reopen.

**Comment by GoebelL** [comment]
So, what's this issue about?

**Comment by DawidCh** [comment]
I have found old properties for clustering but Suzana told me that they are not used anymore. So I will clsoe.
