### ISSUE TITLE
APP UI - add APP URL and admin email

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#677]
It should be possible for the APP admin to change at least its email address and the public APP URL (used in notification mails) using the web UI. It would be good to have all properties (similar as by controller configuration UI).
It is not acceptable to use database scripts in case OSCM/APP is running as a service.
The page can be accessed from a link provided in the app page where controller are registered.

The following properties must be available on UI:

APP_BASE_URL=http://\<server\>:\<port\>/oscm-app
APP_ADMIN_MAIL_ADDRESS=admin@example.com

BSS_USER_KEY=\<userKey\>
BSS_USER_ID=\<userId\>
BSS_USER_PWD=_crypt:\<password\>

**Comment by kwodzynski** [comment]
Checked on Windows 8.1, jdk1.8u121, Glassfish 3, build PRIVATE-BUILD-ON-ESTESSBESCIJS3 2017/05/10 - OSCM. It is working correctly.

**Comment by SylviaDehn** [comment]
See other errors for reopen reason

**Comment by DawidCh** [comment]
@SylviaDehn - which errors? Where are I can see them?

**Comment by SylviaDehn** [comment]
follow the links for issues above

**Comment by kwodzynski** [comment]
#713 is related to this

**Comment by DawidCh** [comment]
Problems in this issue have been fixed. @grubskim please merge it. All the linked issues are separate ones and should be treated separately.
