### ISSUE TITLE
In "Account--Subscriptions" pages of supplier, there only listed the subscriptions subscribed by himself, but after searching, it can display the subscription by customer.

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#68]
Date: 2016/05/06
[Test category]: creative Test

[Steps to reproduce]
1. Login as supplier, define a service, set price model, publishing option for it, then activate this service.
2. Login as customer, subscribe this service named as "cu_bug", put the configuration and price model information, then assign this subscription to himself.
3. Login as supplier, subscribe this service named as "sp_bug", put the configuration and price model information, then assign this subscription to himself.
4. Go to "Account"->"subscription" page.
5. Search the word "bug".

[Expected result]
After step4, there are all the subscriptions listed.
After step5. there are the subscription with "bug" listed.

[Observed result]
After step4, there is only one subscription "sp_bug".
After step5, there are two subscriptions "sp_bug" and "cu_bug".

**Comment by StavrevaS** [comment]
The observed result after step4 is correct, you are logged in as supplier, so you can see only your subscription sp_bug, not the one from the other organization.

**Comment by DawidCh** [comment]
Hello.
Previously, in account->subscriptions page, supplier did not see the customer's subscriptions. If you do not use subscription filter, then old query for subscriptions is used. Subscription filter is used as filter on the results returned by old query.
Query for blue portal is (was) different than for marketplace.
The question is: should supplier see the customer's subscriptions, consider the fact that before search feature has been implemented, he did not?
Regards, Dawid.

**Comment by SylviaDehn** [comment]
The supplier is acting as a customer in this case. So it should be exactly the same.

**Comment by DawidCh** [comment]
Supplier role should be used for managing marketable services in marketplace. All 'managing stuff' of services and such is being done on blue portal. Supplier should see his clients' subscriptions there. When supplier switches to marketplace, he is no longer admin but regular client.
Conclusion: in marketplace supplier should not see his clients' subscriptions.

**Comment by StavrevaS** [comment]
The bug is related to issue #76, so set to duplicate.

**Comment by jiangweiyi** [comment]
Verified by FNST
[verified-version]V16.0 fix5
[verified-details]Now the supplier in the marketplace can only see his owen subscriptions, and can not search out the other organization's subscrptions, so this bug can be verified.
