### ISSUE TITLE
OSCM Installer:  the web service listener should be secure

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#682]
Related to https://github.com/servicecatalog/development/issues/634

The OSCM installation already supports separate http_listener which can be used for the SOAP web services. It is not secure. Change the installation to support security for this http_listener.

**Comment by StavrevaS** [comment]
@gertipoppel, please document the following for bes domain settings:
- the glassfish.domain.WS_PORT is renamed to glassfish.domain.WS_PORT_SECURE 
- the http listener created for this port is secure (uses ssl with default glassfish certificate s1as).

Existing installation are not affected from this change, it is valid only for new installations.

**Comment by gertipoppel** [comment]
Added a note in the Release Notes and changed the description for WS_PORT in the APP and the Controller documentation.
