### ISSUE TITLE
UI for importing heat templates should only be shown for controllers where this is supported

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#687]
[Version]
16.1 fix7 2017/05/03 branch: fb_app_file_upload

[How to reproduce]
1.     goto http://server:8880/oscm-app-somecontroller/index.xhtml

[Expected result]
UI for importing heat templates (bottom section) should only be shown where this is 

[Observed result]
Importing heat templates is shown for each controller.

 [Details]
OpenStack should be possible. I do not know of any others where our controller supports this. 
@MiethanerR comment on this and let me know if TEMPLATE_NAME is supported for any other controllers.

**Comment by MiethanerR** [comment]
@SylviaDehn Currently only the openstack controller can make use of the local template. @mdehn  just clarified this. I will hide the interface for other controllers.

**Comment by MiethanerR** [comment]
Fixed. The template UI is now only available for the openstack controller.

**Comment by SylviaDehn** [comment]
[Build] 2017/05/04 verified (checked openstack and aws)
