### ISSUE TITLE
default incorrect for controller_settings.properties "TEMPLATE_BASE_URL"

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#688]
[Version]
17.0 2017/04/21

[How to reproduce]
check controller_settings.properties in openstack install pack.

[Expected result]
the parameters "TEMPLATE_BASE_URL" default should be correct:
#TEMPLATE_BASE_URL=http://\<app\>/templates/

[Observed result]
#TEMPLATE_BASE_URL=http://\<app\>/docroot/templates/

[Details]
It is correct that the directory is docroot/templates, but "docroot" does not need to be specified in the url
@gertipoppel please also fix documentation.

**Comment by SylviaDehn** [comment]
Please note, this is still necessary even if heat templates can be imported. It can still be used in addition to the import heat template functionality.

**Comment by SuessI** [comment]
I changed the sample in the documentation for the Azure integration, where this is also relevant.
@grubskim - should also be changed in Azure sample technical service
@gertipoppel - still needs to be changed in OpenStack documentation.

**Comment by gertipoppel** [comment]
I changed the sample in the documentaton for the OpenStack integration manual.

**Comment by DawidCh** [comment]
#593 should also be fixed in the scope of this bug.

**Comment by grubskim** [comment]
Changed default value in Azure sample technical service (branch fb_azure_adapt) and 
Fixed TEMPLATE_BASE_URL in openstack controller (master branch).
