### ISSUE TITLE
Container: No organizations found in manage organization

### ISSUE THREAD

**Issue by MiethanerR** [servicecatalog/development#692]
[Version]
16.1 fix7 2017/05/08 Containerized Version

[How to reproduce]
1. Login to portal
2. Goto "Manage Organization"
3. Search for Organiation

[Expected result]
Available organizations are shown in a list.

[Observed result]
List says: "No organizations found"

[Details]
The issue was also observed with other fields of the same type.

[Suggestion]
Change the field to a dropdown field like with other identifiers.

**Comment by shimizuf** [comment]
No log entries in bes, indexer and imq logs when trying to list organizations.

**Comment by shimizuf** [comment]
javax.faces library had to be patched/updated.
