### ISSUE TITLE
BSS_USER_PWD should not be in clear text in in app ui

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#698]
[Version]
17.0 2017/05/15 (bugfix branch, including issue #677)

[How to reproduce]

1.    go to http://&lt;host&gt;:8880/oscm-app/
2.    look at BSS_USER_PWD

[Expected result]
password cannot be read 

[Observed result]
password can be read in clear text

[Details]
Use input type="password" in form

**Comment by grubskim** [comment]
Fixed in hotfix/issue-677 and hotfix/issue-677-gf3.

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.7.0_45, Glassfish 3, build PRIVATE-BUILD-ON-ESTESSBESCIJS3 2017/05/16 in SAML mode.

The input has type="password", but I can read password (plain text) in source code of page or using tool eg. Firebug

<input type="password" name="appSettings:j_idt65:4:j_idt71" value="admin123" onchange="setDirty(true)">

**Comment by SylviaDehn** [comment]
@kwodzynski this is also the case for all other password settings in APP. So it is OK

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8.u121, Glassfish 4, build PRIVATE-BUILD-ON-ESTESSBESCIJS1 2017/05/16 in SAML mode. The input has type="password".
