### ISSUE TITLE
Order of parameters for APP UI is incorrect

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#699]
[Version]
17.0 2017/05/15 (bugfix branch, including issue #677)

[How to reproduce]
1.   go to http://estsdehn.intern.est.fujitsu.com:8880/oscm-app/

[Expected result]
APP general parameters are grouped together;
User specific parameters are grouped together

[Observed result]
Parameters are all mixed up

[Details]
please use order as specified in User Story (CB)

**Comment by grubskim** [comment]
Fixed in hotfix/issue-677 and hotfix/issue-677-gf3.

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.7.0_45, Glassfish 3, build PRIVATE-BUILD-ON-ESTESSBESCIJS3 2017/05/16 in SAML mode. APP settings are grouped together and the USER settings are grouped together.

**Comment by kwodzynski** [comment]
and checked on Windows Server 2016, jdk1.8.u121, Glassfish 4, build PRIVATE-BUILD-ON-ESTESSBESCIJS1 2017/05/16 in SAML mode. APP settings are grouped together and the USER settings are grouped together.
