### ISSUE TITLE
When edit the subscription of customer by supplier there is error message.

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#70]
Date: 2016/05/06
[Test category]: creative Test

[Steps to reproduce]
1. Login as supplier, define a service, set price model, publishing option for it, then activate this service.
2. Login as customer, subscribe this service named as "cu_bug", put the configuration and price model information, then assign this subscription to himself.
3. Login as supplier, go to "Account"->"subscription" page.
4. Search the word "bug".
5. Click the subscription "cu_bug" in the searched list.

[Expected result]
Can be edited.

[Observed result]
There is the error message "The data has been modified or deleted in the meantime. Please execute the operation again."
If the subscription cannot be edited by supplier, the error message is wrong.

**Comment by StavrevaS** [comment]
The expected result is not corrected. On the marketplace portal Account->Subscriptions, the supplier can see only own subscriptions, just like any other customer.  That is why editing is not possible.  Anyway it is a bug, but with minor severity and duplicate to [#68](https://github.com/servicecatalog/development/issues/68).

**Comment by jiangweiyi** [comment]
Verified by FNST
[verified-version]V16.0 fix5
[verified-detials]Now the other organization's subscription can not be searched out, this bug can be verified.
