### ISSUE TITLE
APP UI: APP Platform Settings should read "APP Settings"

### ISSUE THREAD

**Issue by gertipoppel** [servicecatalog/development#700]
[Version]
17.0 2017/05/15 (bugfix branch, including issue #677)

[How to reproduce]
1.   go to http://estsdehn.intern.est.fujitsu.com:8880/oscm-app/

[Expected result]
The title of the section for updating the APP cfg settings is "APP Settings"

[Observed result]
The title is "APP Platform Settings"

[Details]
Since APP is the abbreviation for Asynchronous Provisioning Platform, the "Platform" in the title is superfluous.

**Comment by digitalfishpond** [comment]
This seems to have been changed already to APP Controller Configuration in the latest version. @gertipoppel Is this acceptable?

**Comment by digitalfishpond** [comment]
My bad. Comment made about previous version of APP. Will fix now.

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1778 2017/06/29 (Official 17.2.0) in Saml mode. Now the title is "APP Settings".
