### ISSUE TITLE
Operator client - getsubscriptionusage

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#704]
Currently all the subscriptions are taken into consideration during the report. It needs to be narrowed down to as low set as possible before writing csv file.

**Comment by DawidCh** [comment]
Fixed in scope of #712

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1769 2017/06/02 in SAML mode.
Command getsubscriptionusage works as expected.

**Comment by kwodzynski** [comment]
Retested on Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1778 2017/06/29 (Official 17.2.0) in Saml mode. Command getsubscriptionusage works as expected.
