### ISSUE TITLE
Datamodel for write back the number of VMs is not as suggested in User Story

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#708]
[Version]
17.0 2017/05/16 (Feature Branch "vms export data")

[How to reproduce]

1. The number of VMs are written to bes subscription table. 

[Expected result]
Controllers can retrieve any information from the target IaaS service as long as this information is provided by the respective IaaS API.
This information should be then written to respective service parameters of the subscription as suggested by the user story and as discussed with Suzana

[Observed result]
The subscription table is used.

[Details]
This does not allow CTMG billing to extract the necessary information for period based billing which is needed in the future.

**Comment by GoebelL** [comment]
This not a bug but an implementation concern.

**Comment by badziakp** [comment]
Before test it is needed to export existing technical service definitions add:
    </ParameterDefinition>
	    <ParameterDefinition configurable="false" default="0" id="VMS_NUMBER"
                         mandatory="true" valueType="LONG">
      <LocalizedDescription locale="en">The number of VMs of IaaS subscriptions</LocalizedDescription>
    </ParameterDefinition>

and import them once again.
VMS_NUMBER parameter will be added to the existing  subscriptions after first run of timer.

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8u121, build US9442 EXPORT USAGE UT-22 2017/05/30 in SAML mode. It works as expected.

**Comment by gertipoppel** [comment]
Updated the release notes and the technology provider guide accordingly on May31

**Comment by victorhrsilva** [comment]
Retested on Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-17662017/06/01 in SAML mode. The value can be found on the parameter table for the new Technical Services with this parameter definition.

**Comment by kwodzynski** [comment]
Windows Server 2016, jdk1.8u121. build BES_MASTER_UNIT-1775 2017/06/28 in SAML mode.
It works as expected.
