### ISSUE TITLE
Operator's export usage data lists terminated subscriptions and not just those IaaS Subscriptions

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#709]
[Version]
17.0 2017/05/16 (Feature Branch "vms export data")

[How to reproduce]
1.  java -jar lib/oscm-operatorsvc-client.jar <userkey> <password> getsubscriptionusage filename=\<filename\>

[Expected result]
Only subscriptions in state:
ACTIVE, SUSPENDED, and PENDING_UPDATE should be listed

[Observed result]
All subscriptions are listed (some only have numbers as a name, and were terminated years ago)

**Comment by StavrevaS** [comment]
The query is adapted to list only subscriptions in ACTIVE and PENDING_UPD mode. The SUSPENDED mode will trigger deprovisioning of the cloud resources, so it is not of interest.
Subscriptions without VMs are not listed.

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016. jdk1.8u121, Glassfish 4, build US9442 EXPORT USAGE UT-9 2017/05/22.
Only subscription with VMs and ACTIVE or PENDING_UPD status are listed.

**Comment by DawidCh** [comment]
Bug is reopened because latest commit lists all subscriptions even, with the vm numbers with value 0.

**Comment by DawidCh** [comment]
Query has been fixed and returns only subscriptions for which number of vms is > 0.

**Comment by kwodzynski** [comment]
Retested on Windows Server 2016. jdk1.8u121, build BES_MASTER_UNIT-1775 2017/06/28 in SAML mode.
Only subscriptions with number of VMs greater than 0 and ACTIVE or PENDING_UPD status are listed.
