### ISSUE TITLE
Operation failed when edit some subscriptions of customer by supplier

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#71]
Date: 2016/05/06
[Test category]: creative Test

[Steps to reproduce]
1. Login as supplier, define a service, set price model, publishing option for it, then activate this service.
2. Login as customer, subscribe this service named as "bug", put the configuration reference number as "12" and price model information, then assign this subscription to himself.
3. Login as supplier again, subscribe this service named also as "bug", put the configuration set the reference number as "34" and price model information, then assign this subscription to himself.
4. Go to "Account"->"subscription" page.
5. Search the word "bug", then edit the subscription "bug".

[Expected result]
The "bug" subscriptions can be showed.

[Observed result]
After step4, there is only one subscription named "bug" which has reference number "34".
After step5, there are two subscriptions named "bug", both of them has the reference number "12"; After choosing one of the "bug" subscriptions to edit, there shows "operation failed" page.

**Comment by StavrevaS** [comment]
You are logged in as supplier and after the search in step5, you see also the subscriptions of your customer which match the search criteria. This is wrong, but it is the same problem described in the issue [#68](https://github.com/servicecatalog/development/issues/68). So, this issue can be closed as duplicate.

**Comment by jiangweiyi** [comment]
Verified by FNST
[verified-version]V16.0 fix5
[verified-details]Now the supplier can only searched out his own subscription, so this bug can be verifed.
