### ISSUE TITLE
Wrong order of values in generated report - getsubscriptionusage

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#712]
Build: US9442 EXPORT USAGE UT-6 2017/05/16 
Windows Server 2016
jdk1.8u121
SAML mode

[How to reproduce]
Use getsubscriptionusage command in Operator Client
Read generated report

[Expected result]
The values have been written in following order:

    Customer organization id
    Customer organization name
    Subscription name
    Marketable service name
    Technical service name
    Supplier organization id
    Supplier organization name
    Number of users
    Number of VMs 

[Observed result]
The order is wrong

    Customer organization id
    Customer organization name
    Subscription name
    Marketable service name
    Technical service name
    Supplier organization name
    Supplier organization id
    Number of users
    Number of VMs 

[Details]
The order of the following values should be swapped

    Supplier organization id
    Supplier organization name

**Comment by DawidCh** [comment]
[Details of fix]
Modified order of data written to CSV, added tests and closed stream.

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8u121, build US9442 EXPORT USAGE UT-9 2017/05/22. The order is correct.

**Comment by kwodzynski** [comment]
Retested on Windows Server 2016, jdk1.8u121, build US9442 EXPORT USAGE UT-22 2017/05/30 in SAML mode. The order is properly

**Comment by victorhrsilva** [comment]
Retested on Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-17662017/06/01 in SAML mode. The order is properly

**Comment by kwodzynski** [comment]
Retested on Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1769 2017/06/02 in SAML mode. The order is incorrect

**Comment by kwodzynski** [comment]
Sorry, it is my fault. The order is correct.

**Comment by kwodzynski** [comment]
Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1775 2017/06/28 in SAML mode.
Retested with above build, the order is correct.

**Comment by kwodzynski** [comment]
Retested on Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1778 2017/06/29 (Official 17.2.0) in Saml mode. The order is correct.
