### ISSUE TITLE
Number of VMs (servers) must be supported for all controllers

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#714]
[Version]
17.0 2017/05/17

[How to reproduce]
For controllers other than openstack, this user story has to work too. 

[Expected result]
Controllers can retrieve any information from the target IaaS service as long as this information is provided by the respective IaaS API. So if there is only one AWS server in a subscription, then 1 has to be returned.

[Observed result]
Subscriptions other than OpenStack only show "0" VMs in the respective tables.

[Details]
see user story

**Comment by GoebelL** [comment]
Currently OpenStack/K5 adapter support orchestration with multiple VMs. Azure is not available yet.
Other adapters are for AWS EC2 and VMWare. These should return "1" as fix number.

**Comment by DawidCh** [comment]
@GoebelL Requirements says:

> If the number of VMs is not available, i.e. if it is not relevant, it is left empty.
We provide 0 for that instead of null. Should we rework it?

**Comment by mdehn** [comment]
For IaaS services the number of VMs has to be a digit.
For non-IaaS services the field must be empty, because it is not relevant.

**Comment by GoebelL** [comment]
> Non-IaaS subscriptions do not have a number of VMs. 
>It must be evident that here this number is not relevant.

@badziakp 
Is this reflected? [0a30000](https://github.com/servicecatalog/development/commit/0a300005a4ad46c74359d653898601abdc575af2) doesn't seem to address this.

**Comment by badziakp** [comment]
@GoebelL 
As I understood Non-IaaS subscriptions are those which are not connected to any controller. Am I right?
If yes, then method  0a30000 will be not called for them and in the result no value will be stored. Can you write me a test case when the solution will fail?

**Comment by GoebelL** [comment]
Ok, I got it. You are right, the commit solves it.

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8u121, build US9442 EXPORT USAGE UT-22 2017/05/30 in SAML mode for AWS, Vmware and Openstack. It works as expected.

**Comment by victorhrsilva** [comment]
Retested on Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1766 2017/06/01 in SAML mode for AWS and Openstack. It works as expected.
