### ISSUE TITLE
Remove ivy from release artifacts

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#715]
[observed]
ivy.jar is contained in binaries

[expected]
ivy.jar is not needed in binaries

**Comment by StavrevaS** [comment]
The apache-ant-contrib directory contains ivy jar and some other apache common jars which are already in other directories. All of them are removed from packaging.

**Comment by SylviaDehn** [comment]
[Build] 17.3+
[Date] 2017/08/30
verified install pack and aws open stack controller packages
