### ISSUE TITLE
The details of subscription displayed inproperly

### ISSUE THREAD

**Issue by wangyingfnst** [servicecatalog/development#72]
Date: 2016/05/06
[Test category]: creative Test

[Steps to reproduce]
1. Log in marketplace as customer;
2. Select a service to make a subscription named as "test", then assign customer to this subscription;
3. Click on "MY SUBSCRIPTIONS", select the subscription which subscribed just now to see the details;
4. Input some words of the search box to make the search result null or do not contain the "test".

[Expected result]
In step 3, the details of "test" should be displayed successfully;
In step 4, the details of "test" should not be displayed.

[Observed result]
In step 3, the details of "test" was displayed successfully;
But in step 4, the details of "test" was still displayed.

**Comment by DawidCh** [comment]
Hello.
The behaviour proposed in expected result is inconsistent with existing column filter. If you filterout currently chosen subscription, it will not disappear from the details view. In my opinion we should keep it consistent and change both functionalities (column filter and subscription filter) or none.
Regards, Dawid.
![my_subs](https://cloud.githubusercontent.com/assets/14540695/15283395/70e70c08-1b4a-11e6-8cd9-ade1d9c5ffc5.png)

**Comment by GoebelL** [comment]
>...we should keep it consistent 
Yes.
>and change both ... or none.
I vote for both. I think the details pane should be consistent with the selection in the table.

@mdehn 
Please decide.

**Comment by mdehn** [comment]
Please do not show the details if no subscription is selected in the list of subscriptions.
So change both.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/09 verified
