### ISSUE TITLE
Travis build

### ISSUE THREAD

**Issue by grubskim** [servicecatalog/development#725]
Task involves:
- integrating Github with Travis
- run unit tests on Travis
- if green build Docker image
- push Docker image to Dockerhub

**Comment by grubskim** [comment]
Travis now builds and runs unit tests after every commit on the blueprint repository.
TODO: Docker part.

**Comment by GoebelL** [comment]
We need to ensure license checks before pushing in Dockerhub.

**Comment by grubskim** [comment]
Moving all blueprint issues to https://github.com/servicecatalog/blueprint-service, as we cannot link commits to here
