### ISSUE TITLE
The service can not be subscribed by subscription manager when the subscription name is the same as the customer subscribed

### ISSUE THREAD

**Issue by wangyingfnst** [servicecatalog/development#73]
Date: 2016/05/06
[Test category]: creative Test

[Steps to reproduce]
1. Log in marketplace as customer;
2. Select a service to make a subscription with "just_test" as subscription name;
3. Log in marketplace as subscription manager;
4. Select a service to make a subscription, also with "just_test" as subscription.

[Expected result]
In step 4, the service should be subscribed successfully.

[Observed result]
In step 4, the service can not be subscribed with the error message "The subscription name just_test already exists. Please enter another subscription name.". But the subscription manager does not make a subscription named as "just_test", only the customer does.

**Comment by StavrevaS** [comment]
The subscription id is unique per customer organization, not per user. So I will close this issue as invalid
