### ISSUE TITLE
conflict markers exists

### ISSUE THREAD

**Issue by toshihiro-shiino** [servicecatalog/development#737]
a lot of conflict markers exists on current master.
Although we saw often this problem in this project, is there no culture to confirm differences before committing?

https://github.com/servicecatalog/development/blob/master/oscm-installation/install/macrodefs-glassfish.xml#L260
https://github.com/servicecatalog/development/blob/master/oscm-installation/install/macrodefs-glassfish.xml#L261
https://github.com/servicecatalog/development/blob/master/oscm-installation/install/macrodefs-glassfish.xml#L265
https://github.com/servicecatalog/development/blob/master/oscm-installation/install/macrodefs-glassfish.xml#L282
https://github.com/servicecatalog/development/blob/master/oscm-installation/install/macrodefs-glassfish.xml#L300
https://github.com/servicecatalog/development/blob/master/oscm-installation/install/macrodefs-glassfish.xml#L317
https://github.com/servicecatalog/development/blob/master/oscm-installation/install/macrodefs-glassfish.xml#L528
https://github.com/servicecatalog/development/blob/master/oscm-installation/install/macrodefs-glassfish.xml#L543
https://github.com/servicecatalog/development/blob/master/oscm-installation/install/macrodefs-glassfish.xml#L543

**Comment by StavrevaS** [comment]
The conflict markers were result of an error by rebase action.

**Comment by toshihiro-shiino** [comment]
conflict often occurs on rebase, so I believe it is better to check diff after rebase.
