### ISSUE TITLE
Why GetServersNumber returns Integer

### ISSUE THREAD

**Issue by toshihiro-shiino** [servicecatalog/development#739]
GetServersNumber returns Integer instead of int.

https://github.com/servicecatalog/development/blob/fb_operator_export_data/oscm-app-extsvc-2-0/javasrc/org/oscm/app/v2_0/intf/APPlatformController.java#L450

However, I can not understand from JavaDoc why null can be returned.
Also, I do not know what will happen if I return null.

If an error occurs, I understand that I will throw an APPlatformException and not return null.

**Comment by GoebelL** [comment]
Only I can think of here is for allowing adapters to skip updates, since the subscription parameter will not be updated if null is returned.

**Comment by toshihiro-shiino** [comment]
@GoebelL 
I understand!
But I think that it's better if this is described in JavaDoc.

**Comment by toshihiro-shiino** [comment]
It’s really hard to understand.
After all, did not we return null if we wanted to skip the update?

**Comment by toshihiro-shiino** [comment]
It seems the fix applied this time is one of API Breaking Changes.
GetServersNumber is the default method of the interface and if I am not mistaken, this API Change will not issue any compile error and runtime error which results in very dangerous situation of silent corruption of GetServersNumber implementation.
I believe I am the only one in the world at present who has implemented GetServersNumber in addition to the standard controllers, so it will not cause any issue practically for now.
However, I trust that this kind of fix should not be performed so lightly without leaving any explanation and evidence.
