### ISSUE TITLE
Missing changes*.zip

### ISSUE THREAD

**Issue by toshihiro-shiino** [servicecatalog/development#740]
I download "https://github.com/servicecatalog/development/releases/download/v17.0.0/oscm-integration-app-pack.zip".
I extract it and read readme.htm.
There is written like this "Archive files, changes*.zip, where you can find detailed information on changes to the APP Web service API as compared to previous releases. Use the changes.html file in each archive for viewing the respective documentation.".
But I can't find changes*.zip and changes.html.

**Comment by GoebelL** [comment]
These files are unfortunately not available. The mentioned note in readme.htm is outdated and needs to be corrected.

**Comment by toshihiro-shiino** [comment]
ok, I understand.

**Comment by digitalfishpond** [comment]
fixed with #765

**Comment by toshihiro-shiino** [comment]
We are afraid that it seems the fix is not correctly provided.
First of the all, what we found for certain is there is no </LI>.
Then, what we deem as certain is the word "Archive files" actually indicates "changes*.zip", so leaving either one of the expressions is not suitable since their meanings are identical.
We expect the correct fix will be deleting the whole elements that contain "API changes" from the document.

**Comment by digitalfishpond** [comment]
@toshihiro-shiino PTAL

**Comment by toshihiro-shiino** [comment]
@digitalfishpond LGTM
