### ISSUE TITLE
Manage payment types. services with "native" billing only should be shown

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/development#75]
Date:2016/05/13
[Test category]: creative

[Steps to reproduce]
Login as supplier on blue Portal
goto manage payment types
[Expected result]
only Services with nativ billing are listed
[Observed result]
all Services are listed

**Comment by DawidCh** [comment]
If the page should hide not native billed services should the API behave consistent?
Method AccountServiceWS.getServicePaymentConfiguration?

**Comment by GoebelL** [comment]
It would make sense to filter the external billing services in UI as well as in API. As long as the filtering is implemented in the service and not on UI the API should behave consistent.
@mdehn 
Please comment.

**Comment by mdehn** [comment]
Please list only services with native billing when managing payment types.
UI and API behavior must be consistent.

**Comment by DawidCh** [comment]
Reopen to wait for codefreeze to be lifted..

**Comment by SylviaDehn** [comment]
[Build]2016/08/09 verfied
