### ISSUE TITLE
Support of SHA256 signature in SAML transaction

### ISSUE THREAD

**Issue by toshihiro-shiino** [servicecatalog/development#750]
In the present OSCM, the signature in SAML is hard-coded in SHA1.

https://github.com/servicecatalog/development/blob/d87f5b3defba5a7301c39f3a41d95b9b8d73fe69/oscm-saml2-api/javasrc/org/oscm/saml2/api/LogoutRequestGenerator.java#L97
> String encodedSigAlg = URLEncoder.encode("http://www.w3.org/2000/09/xmldsig#rsa-sha1", UTF_8);
>
> Signature signature = Signature.getInstance("SHA1withRSA");

We request for a support of SHA256 signature (http://www.w3.org/2001/04/xmldsig-more#rsa-sha256) as well in SAML transaction.

**Comment by GoebelL** [comment]
@grubskim 
It would be good if SHA256 could be applied to the SAML logout request. Could test if this can be safely applied without major implications?

**Comment by grubskim** [comment]
Added SHA256 as a hashing option.
New configuration setting: SSO_SIGNING_ALGORITHM:

    - if not present, default is SHA1
    - correct values are either SHA1 or SHA256

German and Japanese translations needed for:
ex.InvalidSigningAlgorithmException
in ExceptionMessages_.properties

**Comment by SylviaDehn** [comment]
[Build] 17.2+ 2017/07/25 
1. Specify ADFS Secure hash algorithm for relying party trust to SHA-256
2. Specify SHA256 for SSO_SIGNING_ALGORITHM
Login using ADFS is no longer possible.
Error shown in bes server.log: see attachment

**Comment by SylviaDehn** [comment]
[serverlog.txt](https://github.com/servicecatalog/development/files/1176988/serverlog.txt)

**Comment by GoebelL** [comment]
@grubskim 
please check. P1 for 17.3 TM.

**Comment by GoebelL** [comment]
SHA256 support targeted for 17.4.

**Comment by grubskim** [comment]
Fixed SHA256 support in retrieving the certificate.

**Comment by SylviaDehn** [comment]
@grubskim please comment on what was fixed

**Comment by grubskim** [comment]
Improved a check in SamlKeySelector. Previous version was checking first if the algorithm is DSA or RSA, then checking if RSA is SHA1. In case of SHA256, the logic was throwing an invalid key exception. Added SHA256 as a valid option during the check.
Now the login should work with SHA1 or SHA256 set on both OSCM and ADFS side.

**Comment by SylviaDehn** [comment]
[Build] 17.3+ 2017/08/01 verified

**Comment by SylviaDehn** [comment]
@gertipoppel please check in documentation for this feature if you have not already done this

**Comment by gertipoppel** [comment]
Included the description again in the Installation and Operator's Guide.
