### ISSUE TITLE
update number of VMS for openstack subscription fails 

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#755]
[Version]
17.1 2017/06/02

[How to reproduce]
1. for a new openstack service, define 
    \<ParameterDefinition configurable="false" default="0" id="VMS_NUMBER"
                         mandatory="true" valueType="LONG">
      \<LocalizedDescription locale="en"\>The number of VMs of IaaS subscriptions\</LocalizedDescription\>
    \</ParameterDefinition\>
in technical service definition.
Note: my openstack app user is technical provider as well as supplier.
2. subscribe to marketable service based on the tech service.
3. check if number of VMs are updated

[Expected result]
values are updated when subscription timer fires

[Observed result]
errors occur in app-core.log and bes server log. Possibly this indicates a problem with authorization.

[Details]
see server.log for bes and app-core.log attached

**Comment by SylviaDehn** [comment]
[app-core.log.txt](https://github.com/servicecatalog/development/files/1058337/app-core.log.txt)

**Comment by SylviaDehn** [comment]
[server.log.bss.txt](https://github.com/servicecatalog/development/files/1058338/server.log.bss.txt)

**Comment by SylviaDehn** [comment]
bssuser.parameterdefinition does have VMS_NUMBER, but the corresponding entry does not exist in bnssuser.parameter for this subscription

**Comment by GoebelL** [comment]
Maybe caused by #716.

**Comment by SylviaDehn** [comment]
Also my app db table serviceinstance has "1" for the value of my vmsnumber. Even though there is more than one vm deployed for my subscription stack.

**Comment by DawidCh** [comment]
@SylviaDehn what is the role of your app user?

**Comment by SylviaDehn** [comment]
my app user is also my supplier/tech provider admin, the same as for the controller user. So not the platform administrator. But I tried with the platform administrator and as far as I remember it also did not work. But if you say this is the problem (even though it should be possible), I could try again.

**Comment by DawidCh** [comment]
Could you please try with TECHNOLOGY_MANAGER role?

**Comment by SylviaDehn** [comment]
I do not know what you mean, I have TECHNOLOGY_MANAGER role. My user has both roles, TECHNOLOGY_MANAGER and SUPPLIER.

**Comment by SylviaDehn** [comment]
Here are all the roles of my user:
Service manager
Technology manager
Administrator
Marketplace manager

**Comment by GoebelL** [comment]
Please check #716.

**Comment by SylviaDehn** [comment]
The permission part of the bug has been fixed with #716. 
But please check why the incorrect number of VMs is gotten from openstack

**Comment by badziakp** [comment]
@SylviaDehn 
Could you tell me how do you know that the number of vms is wrong? Could you attach the print screen where you can see it? (The best for me would be openstack screen)

**Comment by elfriedegoetz** [comment]
The best is to go to "My subscription" -> VM-tab 

![vm_number](https://user-images.githubusercontent.com/15209605/27376105-72a92482-5671-11e7-9b12-52fbe8a163c2.PNG)

Parameter Table in the Database:
![capture1](https://user-images.githubusercontent.com/15209605/27376142-89e32396-5671-11e7-84da-1525fd74f214.PNG)

**Comment by DawidCh** [comment]
Can we get the screens from openstack console, please? We have to set up the same stack.

**Comment by kwodzynski** [comment]
WIndows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1773 2017/06/14 in Saml mode.
 I have noticed one more thing. My subscription is created in OSCM, but is not created in OpenStack (because I have incorrect values in my Technical Service) but anyway the subscription received vmsnumber=1 after Timer fires.

**Comment by SylviaDehn** [comment]
@kwodzynski - my guess is that this is the same problem. It is simply not updated from the server. 
@DawidCh - it is just a stack with 2 VMs, nothing special.

**Comment by SylviaDehn** [comment]
@DawidCh - this used to work fine in the first version I tested. Check for a merge error.

**Comment by badziakp** [comment]
Enterprise version was fixed.

**Comment by kwodzynski** [comment]
Windows Server 2016, jdk1.8u121, build ISSUE696-3 2017/06/27 in SAML mode.
I checked for subscriptions with 2, 1 and 0 VMs (0 for incorrect Technical Service). In each case I received correct number of VMs.
Set to verified.

**Comment by SylviaDehn** [comment]
@badziakp Could you please comment on the cause for this error

**Comment by badziakp** [comment]
The problem was that default method form the interface was not implemented in the adapter for the enterprise version.

**Comment by kwodzynski** [comment]
Windows Server 2016. jdk1.8u121, build BES_MASTER_UNIT-1775 2017/06/28 in SAML mode.
I have repeated my test for 2, 1 and 0 VMs. I got correct number of VMs in every case.

**Comment by kwodzynski** [comment]
Retested on Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1778 2017/06/29 (Official 17.2.0) in Saml mode. I received correct numbers of VMs.
