### ISSUE TITLE
VMware Controller does not get network settings from database

### ISSUE THREAD

**Issue by opetrovski** [servicecatalog/development#758]
[Version]
17.0

[How to reproduce]
Create a service that gets its network settings from database and subscribe

[Expected result]
the network settings are taken from database and the created VM is configured with these settings

[Observed result]
- provisioning is suspended
- error mail does not contain any hint
- log is saying that NIC1_GATEWAY is not set

[Details]
see attached app-vmware.log 
[app-vmware.txt](https://github.com/servicecatalog/development/files/1060902/app-vmware.txt)

**Comment by GoebelL** [comment]
The issue applies to the case when network setting from database are used. Alternative options to use DHCP or manual network configuration may serve as workaround.

**Comment by GoebelL** [comment]
Hi @opetrovski

Could you help with this issue?

**Comment by GoebelL** [comment]
https://github.com/servicecatalog/development/commit/2979fb5171b22f0abeca6a1d87ccbd696867f8eb

**Comment by opetrovski** [comment]
Issue was fixed by moving the statemachine actions reserveIPAddress and releaseIPAddress from a customer specific implementation into this controller. The statemachine definitions create_vm.xml and delete_vm.xml are affected.
