### ISSUE TITLE
update number of VMS for aws subscription fails

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/development#759]
[Version]
BES_MASTER_UNIT-17712017/06/07

[How to reproduce]
    for a new aws service, define

    <ParameterDefinition configurable="false" default="4" id="VMS_NUMBER"
    mandatory="true" valueType="LONG">
    <LocalizedDescription locale="en">The number of VMs of IaaS subscriptions
</LocalizedDescription>
    </ParameterDefinition>

    in technical service definition.
    Note: my aws app user is technical provider as well as supplier.
    subscribe to marketable service based on the tech service.
    
   in database table "parameter" the default of 4 VMS are written after a subscription is created

[Expected result]
values for VMS_Number are updated to the valid value 1 when "APP_TIMER_REFRESH_SUBSCRIPTIONS" timer fires

[Observed result]
nothing is happen. In the bes server.log:

Caused by: org.oscm.internal.types.exception.SaaSSystemException: EXCEPTIONID 1497005436036: You are not allowed to perform this opperation!
	at org.oscm.subscriptionservice.bean.SubscriptionServiceBean.notifySubscriptionAboutVmsNumber(SubscriptionServiceBean.java:5584)
	at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)

**Comment by GoebelL** [comment]
Seems to be related or may be duplicate with #755. 
@DawidCh, please check.

**Comment by DawidCh** [comment]
@elfriedegoetz is the app user in technology manager role?

**Comment by elfriedegoetz** [comment]
app user?? what do you mean.
My BSS_USER_ID_ proxy is the PLATFORM_OPERATOR

**Comment by badziakp** [comment]
@elfriedegoetz 
The error log in the description is related to the OpenStack subscriptions. Did you tested it after issue #716 was fixed?

**Comment by elfriedegoetz** [comment]
Yes the message in the error log is fixed, but the number of VMs are still not updated see scenario above.

**Comment by badziakp** [comment]
So the vms number is still 4? Are you sure that the timer was executed? What is a value of APP_TIMER_REFRESH_SUBSCRIPTIONS in the test database?

**Comment by elfriedegoetz** [comment]
sorry I had problems with my sts-domain. Now it works fine.
But I noticed, if I  directly terminate the subscription via amazon , no update of the VMs will done.
Is this behavior correct?

**Comment by GoebelL** [comment]
That's a valid question. I guess this case handling is missing. I'd expect the parameter should be set to 0 once the polling timer detects the cloud subscription is gone.

**Comment by DawidCh** [comment]
I think this is not so simple. Subscription object is referenced to cloud resource. If the resource has been removed in cloud system, setting number of vms to 0 is not solution. We would also have to terminate subscription. If this is valid requirement than it should be reported. It may be implemented in the scope of requirement #629

**Comment by kwodzynski** [comment]
I have checked what happens if someone does delete subscription from aws controller. Unfortunately, the parameters of the subscription are not deleted after the both operations (DELETE and DEPROVISION) from bssuser.parameter table, but ....

**Comment by kwodzynski** [comment]
... I also checked main scenario from this issue. Value for vms number is changed for 1 when "APP_TIMER_REFRESH_SUBSCRIPTIONS" timer fires. I've got no such errors in bes.log. My environment it: Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1773 2017/06/14 in SAML mode.

**Comment by DawidCh** [comment]
Feature request from comment https://github.com/servicecatalog/development/issues/759#issuecomment-310045608 has been reported #771
Because fix was not needed here, I'm setting the bug as invalid.

**Comment by elfriedegoetz** [comment]
The original issue works fine

**Comment by elfriedegoetz** [comment]
I'm setting the bug as invalid?? The bug is not invalid!! Now the bug is fixed .

**Comment by DawidCh** [comment]
The bug has been fixed in the scope of #716.

**Comment by kwodzynski** [comment]
Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1775 2017/06/28 in SAML mode.
I have created one subscription when I was connected to Internet with proxy, and second one with wrong names of AMI and Subnet Definition. In both cases instances have not been created in Amazon Dashboard. Unfortunately also in both cases I received value "1" in paramater table. 
For correct subscription it works properly.

**Comment by kwodzynski** [comment]
Because incorrect subscriptions have a PENDING status and Report ignores subscription with such one, we can recognize this situation as correct. I close.

**Comment by kwodzynski** [comment]
Retested on Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1778 2017/06/29 (Official 17.2.0) in Saml mode. It works as expected.
