### ISSUE TITLE
Subscription search dose not work

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#76]
Subscription list(not search anything yet)

[version]
V16.0.4

[Frequency]
Always

[How to reproduce]
1. login on marketplace
2. Go to account->subscription
3. search name, reference, parameters of type string
(ex. Example, ExampleApp_login_zyuryo, 987, foofoo)

[Expected result]
the service can be found

[Observed result]
the service cannot be found

[Note]
This subscription had Japanese character name. I removed Japanese character from name but still I could not search anything.

**Comment by StavrevaS** [comment]
[Fixed version]
16.0.5

[Detail of fix]
The SubscriptionDao class was refactored to some extent.

[Commit]
[38c7c7ee7388e43e9371ba65a58eaff877f775e8](https://github.com/servicecatalog/development/commit/38c7c7ee7388e43e9371ba65a58eaff877f775e8)

**Comment by jiangweiyi** [comment]
Verified by FNST
[verified version]V16.0 fix5
[verified details]Now the subscriptions can be searched out in "Account"--"subscription" page. So this bug can be verifed.
