### ISSUE TITLE
Check the OpenStack Integration Guide

### ISSUE THREAD

**Issue by mdehn** [servicecatalog/development#761]
The OpenStack Integration Guide states that
- Orchestration API (Heat) v1
- Compute API (Nova) v2.1
are required.
As far as I know OSCM is tested against OpenStack releases, e.g. Newton, rather than single APIs.
Please check, if documentation is up-to-date.

**Comment by StavrevaS** [comment]
The Openstack releases are based on certain API versions. It is good to state with which OpenStack releases we have tested, e.g Newton. However, the controller builds its requests to OpenStack based on some API version, not release version. So it is correct to have them in documentation in case of problems.

**Comment by GoebelL** [comment]
@mdehn 
I confirm the documentation is up-to-date. Orchestration API (Heat) v1 and Compute API (Nova) v2.1 are latest versions. New releases are being tested and expected to work anyway. I don't see need to mention this in the manuals. Such info is rather interesting for release announcement, which is published on the respective OSCM web pages.
