### ISSUE TITLE
MaxPermSize is ignored

### ISSUE THREAD

**Issue by toshihiro-shiino** [servicecatalog/development#766]
In OSCM v17 or later, Java 8 is adapted due to the usage of Glassfish 4.1.
Java 8 abolishes PermGen space and replaces it with Metaspace.
The Ant script of OSCM is still configuring -XX:MaxPermSize in v17 or later, but Java is ignoring such configuration. 
Please fix this issue so -XX:MaxMetaspaceSize will be configured instead of –XX:MaxPermSize. (Or simply eliminating both configurations can be an alternative as well).

**Comment by SylviaDehn** [comment]
@DawidCh - for update installations, MaxPermSize should be deleted, and the new option added manually, correct? Please inform Gerti if this is correct.

**Comment by SylviaDehn** [comment]
@gertipoppel - see above

**Comment by SylviaDehn** [comment]
@digitalfishpond - please you or Dawid respond to my comment above

**Comment by DawidCh** [comment]
It is more for production settings. If you do not suffer of lack of memory for glassfish assigned, you do not have to do anything.

**Comment by SylviaDehn** [comment]
What is a production setting?

**Comment by DawidCh** [comment]
Yes.

**Comment by SylviaDehn** [comment]
Build: 2017/06/28 
Verified code and update installation documentation

**Comment by toshihiro-shiino** [comment]
Unfortunately, the default domain.xml of Glassfish 4.1 is "-XX:MaxPermSize=192m".
So, I think that we shoud not replace "MaxPermSize" with "MaxMetaspaceSize" regarding "delete.jvm.options".

**Comment by SylviaDehn** [comment]
@toshihiro-shiino You are correct. 
@DawidCh Please correct the delete option to delete -XX:MaxPermSize=192

**Comment by toshihiro-shiino** [comment]
Why only app-domain?
bes-domain and master-indexer-domain are still wrong.
https://github.com/servicecatalog/development/blob/master/oscm-installation/domains/bes_domain/installer/JVM-options.properties#L2
https://github.com/servicecatalog/development/blob/master/oscm-installation/domains/indexer_domain/installer/JVM-options.properties#L2

**Comment by digitalfishpond** [comment]
seems odd, i definitely committed 3 files: [https://github.com/servicecatalog/development/pull/784/commits/a1fdb04a4b8edff0e36555d8cd6738f9c28d9296](https://github.com/servicecatalog/development/pull/784/commits/a1fdb04a4b8edff0e36555d8cd6738f9c28d9296)

 I'll create another pull request for the two that got dropped.

**Comment by SylviaDehn** [comment]
verified 17.2
