### ISSUE TITLE
Vmware adapter; Upgrade install: Target does not exist

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#768]
[Version]
 V17.0.2 

[Date]
2017/06/08

[Test category] 
Creative

[Description]
Vmware adapter upgrade install: Target does not exist
update installation; changes of target VMware system, therefore deleting of the content of the vmware database with >ant -f build-db-import.xml deleteAll -Ddb.dir=controller_db
works ok;
running the target ant -f build-db-import.xml importDomain -Ddb.dir=controller_dd
error: 
Buildfile: C:\Software\CT-MG\17.01\vmware-install\install\build-db-import.xml

BUILD FAILED
Target "importDomain" does not exist in the project "APP VMWare controller database import tasks".
[Steps to reproduce]
see above
[Expected result]
target exists
[Observed result] 
arget "importDomain" does not exist in the project "APP VMWare controller database import tasks".
[Details]
See above; 

[Messages and logs]
See documentation: 
VMware vSphere Integration (GlassFish)
B1WS-1281-01 May 2017
2.4 Update Installation 
Updating the vmware Database Step 3 to 5,

**Comment by GoebelL** [comment]
@AndreasTWolf, 
if your expectation is that a target "importDomain" exist, what is it supposed to do?

I guess it should be "importDatacenter" but not "importDomain" as described in the manual. If I am right, my expectation is that the manual states "importDatacenter". This would be a different formulation of issue https://github.com/servicecatalog/development/issues/770.

**Comment by GoebelL** [comment]
This is issue is duplicate to #770. The importAll target from mentioned build file calls following targets in given order:
1. importVCenter
2. importDatacenter
3. importCluster
4. importVLAN
5. importIPPool

Thus, this is correctly solved with respective documentation [fix](https://github.com/servicecatalog/documentation/commit/429f077928523edc2992ca96b56bd9e2ec70e745).

**Comment by kwodzynski** [comment]
Tested on Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1778 2017/06/29 (Official 17.2.0) in Saml mode.
The target "importDomain" does not exist in file build-db-import.xml, but still I can find its in doc file "VMWareIntegration.pdf" (twice, on 16. and 21. page).

**Comment by gertipoppel** [comment]
Fixed with new build of doc. 
modified sources: 
DocSources/en/Shared/Installation/c_InstControllerInExistingAPP.xml
DocSources/en/VMWareIntegrationGuide/Installation/t_InstDB.xml

**Comment by kwodzynski** [comment]
Tested on Windows Server 2016, jdk1.8.u131, build BES_MASTER_UNIT-1904 2017/07/27  (Official 17.3.0) in Saml mode.
The target "importDomain" has been removed from every place.
