### ISSUE TITLE
 Price model is shown same window when broker or reseller operate

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#77]
[version]
V16.0.4

[Frequency]
Always

[How to reproduce]
1. Login as broker or reseller
2. Select "View service" in Marketable service
3. Select service using external billing
4. Click Display in Price model for your service section

[Expected result]
- Show the price model in a separate window

[Observed result]
- Show the price model in a same window

**Comment by DawidCh** [comment]
@servicecatalog/oscmdev2

**Comment by GoebelL** [comment]
The issue has been reproduced.

The respective function in service/serviceData.xhtml should be fixed.
The button implementation is different from subscription/view.xhtml. It's implemented with a h:commandButton, which means a HTTP POST to the same view. It should be done with a GET and directed with target for opening in a new window. Use **<h:commandLink .... target="_blank"/>**.

Why is the include "/priceModel/externalServicePriceModel.xhtml" not reused here? Please check.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/09 verified
