### ISSUE TITLE
Vmware adapter upgrade install: undocumented target necessary to upgrade install successfully 

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#770]
[Version]
V17.0.2

[Date]
2017/06/08

[Test category]
Creative

[Description]
Vmware adapter upgrade install: undocumented target necessary to upgrade install successfully 

When calling the (not described) target 
>ant -f build-db-import.xml importDatacenter -Ddb.dir=controller_db 
and then 
>ant -f build-db-import.xml importCluster -Ddb.dir=controller_db 
it works
[Steps to reproduce]
see above
[Expected result]
all necessary targets are described 
[Observed result]
Target  importDatacenter is not descibed in the documentation
[Details]
See above;

[Messages and logs]
See documentation:
VMware vSphere Integration (GlassFish)
B1WS-1281-01 May 2017
2.4 Update Installation
Updating the vmware Database Step 3 to 5,

**Comment by GoebelL** [comment]
Similar to #769.

**Comment by gertipoppel** [comment]
Fixed in the VMware vSphere Integration Guide. Will be available with V17.2
