### ISSUE TITLE
vmware adapter on vSphere 6.5: Accessinfo IP address not returned

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#774]
[Version]
V17.0.2

[Date]
2017/06/08

[Test category]
Creative

[Description]
When deploying an instance on vSphere server 6.5 the access info for the IP address is not returned from vSphere: 
![image](https://user-images.githubusercontent.com/19411047/27470205-0c0e17b8-57f3-11e7-9a1e-d94d716637da.png)
 
[Details]
See above;
settings in subscription:
![image](https://user-images.githubusercontent.com/19411047/27470237-32ce23c0-57f3-11e7-82fe-076f14baa563.png)

[Messages and logs]

app-vmware.log entry:
[2017-06-22 17:32:26] [__ejb-thread-pool14] DEBUG vcenter: estvcsadev.intern.est.fujitsu.com
[2017-06-22 17:32:26] [__ejb-thread-pool14] DEBUG locale: en
[2017-06-22 17:32:26] [__ejb-thread-pool14] DEBUG Generated access information for service instance 'Blubber3':
Blubber3, 
[2017-06-22 17:32:26] [__ejb-thread-pool14] DEBUG Transition from current state 'END' with event 'success' into state 'SUCCESS'

**Comment by StavrevaS** [comment]
Test with 1 network adapter with DHCP option. The adapter name is mandatory in this case ("VM Network").
The IP address is then available.
![untitled](https://user-images.githubusercontent.com/14818282/27590136-f67641b0-5b4d-11e7-9eb0-5dc01b2375f2.jpg)

**Comment by StavrevaS** [comment]
Test with 1 network adapter with Database option. The adapter name and all necessary settings are read from database (data service of VMWare controller is corrected).
![untitled1](https://user-images.githubusercontent.com/14818282/27590874-55cfdc46-5b50-11e7-9c7c-416c491cc812.jpg)
