### ISSUE TITLE
parameter configuration tool sample does not calculate the correct total price

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#779]
[Version]
17.1+ 2017/06/14

[How to reproduce]

1.    deploy parameter configuration tool from integration-pack sample to application server
2.    specify parameter configuration tool for marketable service
3.    set price model for service specifying per subscription prices for parameters with values less than 
       one, e.g. 0.0003 cents etc
4.    as customer subscribe to marketable service and use "configure" for parameters

[Expected result]
look at parameter costs total

[Observed result]
the total is not correctly calculated

[Details]
see attached screenshot

**Comment by SylviaDehn** [comment]
![parameterconfig](https://user-images.githubusercontent.com/15086024/27592468-d4f6c904-5b54-11e7-83cb-b6830586c869.jpg)

**Comment by digitalfishpond** [comment]
What is the minimum amount here? How many decimal points? In javascript, floats have a very low precision.
This can be mitigated by multiplying the operands and dividing the results, 
`result = ( x * 1000 + y * 1000 ) / 1000`
but if the multiplicator is too low in relation to the number of decimals, then it has no effect. Do we expect to ever go lower than a millionth of a cent?

**Comment by SylviaDehn** [comment]
possibly use the same methods as ctmg billing? Please as dev for advice

**Comment by SylviaDehn** [comment]
[Build] 17.3+
[Date] 2017/08/30
verified
