### ISSUE TITLE
Unnecessary update procedures (postgresql-9.4-1206-jdbc42.jar)

### ISSUE THREAD

**Issue by toshihiro-shiino** [servicecatalog/development#782]
I have downloaded "https://github.com/servicecatalog/development/releases/download/v17.1.0/oscm-install-pack.zip", and read install/doc/en/Installation.pdf after extracting the file.

There is below description in “4.1 Updating From CT-MG V17.0 or Later”:

> 1. Check whether the file
> postgresql-9.4-1206-jdbc42.jar is contained in the following directories of the application server:
> * lib directory of the bes-domain domain
> * <GLASSFISH_HOME>/mq/lib/ext
> If this is not the case, copy the file from the <install_pack_dir>/install/lib directory to the location where it is missing.

It naturally indicates only v17.0 since the released version is v17.1, however, the driver version of Postgres JDBC included in v17.0 is 9.4-1206, so it seems the above description is not necessary.

**Comment by GoebelL** [comment]
@gertipoppel, please remove it.

**Comment by gertipoppel** [comment]
Removed it from update procedure description. 
Modified source file: 
DocSources/en/InstallationGuide/Update/c_Update_17_0.xml

**Comment by kwodzynski** [comment]
It has been removed from the chapter "4.1 Updating From CT-MG V17.0 or Later" but I still can find this description in the chapter "Updating from a CT-MG Release Prior to V17.0" in topic "Updating the Database" on 34. page.

@gertipoppel , @GoebelL Shouldn't it be removed also there?

If it is ok, please close an issue.

**Comment by toshihiro-shiino** [comment]
CTMG v16.0 & v16.1 includes postgresql-9.1-903-jdbc4.jar.
So, in case of version upgrade before v17.0, we may need to upgrade the JDBC driver.

**Comment by toshihiro-shiino** [comment]
I confirmed that v16.1 Fix7 includes postgresql-9.1-903-jdbc4.jar, so we **must** update the JDBC driver if we upgrade from before v17.0.

**Comment by kwodzynski** [comment]
ok, so I close.

**Comment by toshihiro-shiino** [comment]
fix verified with ESCM v17.3.
