### ISSUE TITLE
EJB Container initialization error

### ISSUE THREAD

**Issue by telmer6** [servicecatalog/development#787]
While trying to install OSCM, I receive the following error:
```
deployApplication:
     [echo] asadmin --user admin --passwordfile C:\Users\ELMERT~1\AppData\Local\Temp\BES\script1909800810.txt --port 8448 deploy
     [exec] Command deploy failed.
     [exec] remote failure: Error occurred during deployment: Exception while loading the app : EJB Container initialization error. Please see server.log for more details.
```

Using 
- Ant 1.10.1
- Java EE 7u3
- PostgreSQL 9.6.3-2
- Windows Server 2016 Standard

[server.txt](https://github.com/servicecatalog/development/files/1112957/server.txt)

**Comment by toshihiro-shiino** [comment]
I guess the root cause is a connection error to the DB on line 469 of server.txt.
Why do not you check the connection setting to DB?

**Comment by telmer6** [comment]
Setting the localhost entries of postgres in pg_hba.conf to "trust" fixed the issue, but this seems like a security hole.

**Comment by toshihiro-shiino** [comment]
I'm just a user, not a developer...
Honestly, I think it's not such a big issue because we can fetch plain password from domain.xml.
So, Even without it, we lose when AP server has been invaded by attackers.

**Comment by telmer6** [comment]
I forgot about that. Makes sense.

**Comment by DawidCh** [comment]
> Setting the localhost entries of postgres in pg_hba.conf to "trust" fixed the issue, but this seems like a security hole.
You doesn't have to open postgres to whole world to get it work. Basically you can allow that from the subnetwork x.x.x.x all the connections have to be password protected with md5 encryption. Setting it to trust shouldn't be used on production or even devs environments.
I can advise you to take a look at the possible settings of pg_hba.conf file: https://www.postgresql.org/docs/9.5/static/auth-pg-hba-conf.html under the "auth-method" bullet.
