### ISSUE TITLE
Wrong path in Operation.pdf file

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#804]
[Version]
BES_MASTER_UNIT-1897 2017/07/26 in SAML mode

[How to reproduce]

Open \oscm-install-pack\doc\en\Operation.pdf
Go to 33. page
Find the sentence (In Backup chapter): By default, this file is named _key_ and located in the following directory:

[Expected result]
The path is correct:
<GLASSFISH_HOME>/glassfish/domains/bes-domain/config/

[Observed result]
The path is incorrect:
<GLASSFISH_HOME>/glassfish/domains/bes-domain/config/key

[Details]
In another places in the file, the path is correct, for example on page 34. in 4. point of Chapter "Recovery"

**Comment by gertipoppel** [comment]
Fixed in the operators guide

**Comment by kwodzynski** [comment]
Windows Server 2016, jdk1.8u131, build BES_MASTER_UNIT-1904 2017/07/27 (official 17.3.0) in SAML mode. 
The path is correct.
