### ISSUE TITLE
Browser got stuck when I click subscription with External Parameter Configuration

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#816]
[Version]
BES_MASTER_UNIT-1904 2017/07/27 (official 17.3.0) in SAML mode

[How to reproduce]
Subscribe the marketable service which has External Parameter Configurator
Assigne any user for the subscription
Login as the user and go to My subscriptions page
Click on the subscription

[Expected result]
Page with Details is displayed

[Observed result]
The browser got stuck and nothing happens, moreover in server.log from BES domain I received message as in attached file
[bes-server-log.txt](https://github.com/servicecatalog/development/files/1214342/bes-server-log.txt)

[Details]
The browser crashed and it has to be closed. I have noticed the problem on IE11, Firefox and Chrome

**Comment by SylviaDehn** [comment]
@kwodzynski please check, I cannot reproduce this issue with 17.4

**Comment by kwodzynski** [comment]
Tested on openSUSE Leap 42.3 64-bit, openjdk 1.8.0_144, build 17.4.0 in SAML mode. I have not noticed the problem with the 17.4.0 version. Closing
