### ISSUE TITLE
Technical service creation : Operation field

### ISSUE THREAD

**Issue by mfqih** [servicecatalog/development#822]
[Version]
OSCM 17.3.0
[How to reproduce]
1.	Login as Technical
2.	Create a Technical service
3.	Fill in the Access information, Description, License agreement
4.	Fill in the Tags field
5.	Click on Save

[Expected result]
“Technical Service created” message

[Observed result]
“Error : The Operation failed” message

[Details]
When I re-do the same operations without filling the tags field, it works. Technical service created

**Comment by StavrevaS** [comment]
The issue is connected to #823. @mfqih please check your installation as written in issue #823
