### ISSUE TITLE
Version dialog box has warning

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#83]
Version: 16.0.3+
Date: 2016/05/09
[Test category] creative

[Steps to reproduce]
0. as platform operator (administrator), set set HIDE_PAYMENT_INFORMATION=true
1. log in as supplier
2. go to Customer/Manage payment types (see warning that "Payment types are not used on this platform" .... OK)
3. press "Fujitsu" log at top to see version

[Expected result]
the usual version dialog box

[Observed result]
the dialog box has a warning line at top  (probably from 'Customer/Manage payment types')

**Comment by kowalczyka** [comment]
[Details of fix]
Error panel  has been removed from version dialog box.

**Comment by kowalczyka** [comment]
[Details of cause]
Error panel placed in dialog box (version popoup is also dialog box). Never encountered before as warning message on "manage payment" page (or any other error meesage on other page) was not added to the initial page loading. 

Version box should not display any error messages and this was not handled in the UI but never encountered.

Omit payment feature and configuration setting value was not a direct reason of this issue.

**Comment by SylviaDehn** [comment]
[Build]2016/08/03 verified
This error message did exist, but now is now longer possible since the menu item is missing when you turn HIDE_PAYMENT_INFORMATION on.
I checked with another error message and the version dialog box is ok.
