### ISSUE TITLE
step missing in vmware controller installation doc

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#830]
[Build] 17.4 2017/09/08

[Details]
Installing the VMware Service Controller in an Existing APP Environment, does not explain update of app database.
Please replace section 12.
with the following info for updating the app database:
(I copied this from another section)
Update the following configuration files so that the settings match your current installation:
• db.properties
• configsettings.properties
• configsettings_controller.properties
Particularly take care of settings which have been introduced or changed with the new release
to which you are upgrading.
4. Update the schema and configuration settings of the bssapp database by executing the
build-db.xml file in <install_pack_dir>/install as follows:
<ANT_HOME>/bin/ant -f build-db.xml updateDatabase

**Comment by gertipoppel** [comment]
Modified the description in all controller manuals. 
Modified source file: 
DocSources/en/Shared/Installation/c_InstControllerInExistingApp.xml
