### ISSUE TITLE
Subscription and chargeback of OpenStack projects

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/development#832]
**OSCM Use Case**

I'm running an OpenStack environment as internal IT service provider. My customers are departments of my company or partner companies. OSCM shall be the portal to deliver OpenStack services to these customers. The main use cases are to let customers subscribe to OpenStack services and to let me show-back costs to these customers dependent on their resource consumption. OpenStack services are VMs, network and storage.

**Desired Functionality**

In OSCM the customer shall be able to create one or more OpenStack projects (tenants). On subscription he shall define

- define one or more OpenStack horizon users with rights to manage resources in the new created project
- quotas of the project

In OSCM the customer shall be able to increase the quota of his subscribed OpenStack projects (tenants). 

The price of the subscribed projects shall be calculated on the real usage of the project:  VCPU-Hours, GB-Hours, RAM-Hours.

The usage data shall be updated on daily basis.

**Potential solution**

Codebase could be the existing OSCM-APP controller. Add new service type "OpenStack tenant". Subscription parameters would be
- Domain name
- project name
- openstack user1
- openstack user2
- openstack user3
- openstack user4
- number of 

1. Metadata Items
2. VCPUs
3. Instances
4. Injected Files
5. Injected File Content (Bytes)
6. Volumes
7. Volume Snapshots
8. Total Size of Volumes and Snapshots (GiB)
9. RAM (MB)
10. Security Groups
11. Security Group Rules
12. Floating IPs
13. Networks
14. Ports
15. Routers
16. Subnets

 

Events types could be VCPU-Hours, GB-Hours, RAM-Hours

The connector would use the existing OpenStack APIs to create / update the OpenStack project. A collector could run daily to retrieve the Ceilometer data for the OpenStack and to create the corresponding OSCM events.

**Comment by GoebelL** [comment]
This issue was moved to servicecatalog/oscm#93
