### ISSUE TITLE
New Development Repository

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#833]

**Comment by GoebelL** [comment]
New repository name "oscm".
Following tasks come into my mind. Please add if you have more.

Todo:
1. tag development master and TomEE branches
2. mirror copy develepment->oscm
3. Put TomEE branch on master and delete all unneeded branches
4. Shift Jenkins jobs, ee jobs checkout scripts
5. travis CI
6. reviewable
7. codecov 
8. zenhub 
9. other webhooks
10. docker build
11. users and teams
12. copy/move open tomee issues? Howto? 
13. oscm webpage links (later)

**Comment by grubskim** [comment]
> 1. tag development master and TomEE branches

Done - created tag v17.5.0-RC1 in development, oscm, oscm-dockerbuild and ops repositories.

> 2. mirror copy develepment->oscm

Done - new repository: https://github.com/servicecatalog/oscm.git

> 3. Put TomEE branch on master and delete all unneeded branches

Done - the tomee code has been merged to the respective master branches of oscm (mirrored development), oscm-dockerbuild, and ops repositories. Tomee branches deleted.

**Comment by grubskim** [comment]
> 11. users and teams

Done, copied from development repository.

**Comment by DawidCh** [comment]
This issue was moved to servicecatalog/oscm#4
