### ISSUE TITLE
Integrated installer for the SUSE OpenStack Cloud

### ISSUE THREAD

**Issue by mdehn** [servicecatalog/development#837]
Currently OSCM comes with an installer procedure based on ANT scripts.
To integrate smoothly with the SUSE OpenStack Cloud, provide Barclamp scripts to install OSCM through the SUSE Crowbar Web interface.
Barclamps are a set of recipes, templates, and installation instructions, and are used to install automatically OpenStack services.

**Comment by StavrevaS** [comment]
The installer is developed in another [repository](https://github.com/servicecatalog/crowbar-openstack).
