### ISSUE TITLE
Add note to README

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#84]
I setup OSCM development environment. At that time, I had to add some steps to setup so I want to add these note to README:
  - Download documentation to "document" directory.
  - Add "-Xmx" parameter to ANT JRE configuration if Contributor got OutOfMemory error in building OSCM or could not finish build OSCM.
  - Add "proxyuser" and "proxypassword" properties to setproxy tag in build-dev-PackageDeploy.xml if Contributor use proxy with authentication.

**Comment by SylviaDehn** [comment]
[Build]2016/08/01 verified
