### ISSUE TITLE
Cannot create new marketplace in Docker image with TomEE if Marketplace ID is empty

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#841]
[Version]
OSCM 17.4.0 
Docker image with TomEE

[How to reproduce]
Login as Platform Operator
Go to Create marketplace
Fill up Name and Organization ID
Click Save button

[Expected result]
New marketplace is created

[Observed result]
Red message "Value is required"
The marketplace is not created

[Details]
- It is working with ESCM (as described above) and
- in OSCM if I filled "Marketplace ID" field - but the field should not be required

**Comment by toshihiro-shiino** [comment]
It does not reproduce in our environment.
Version: CE UNIT FOR GITHUB RELEASE-125-20170908121207

**Comment by SylviaDehn** [comment]
@kwodzynski - I cannot reproduce this error either 
Are you sure that you did not find the error that I already reported with tenant ID?

**Comment by kwodzynski** [comment]
I forgot to write, it does occur on Docker image with TomEE. I have corrected the description of this bug and I will check it with environment with Glassfish 4.

**Comment by kwodzynski** [comment]
Ok, I checked it with environment with Glassfish 4 in Internal and Saml mode. In both cases the functionality is working correctly, so it is probably problem with Docker image with TomEE.
@SylviaDehn I do not think that it is related with #831 because the Docker image is in Internal mode.

**Comment by SylviaDehn** [comment]
I also have this issue with TomEE

**Comment by GoebelL** [comment]
This bug is evident. Marketplace ID has to be an optional field. The save button is correctly enabled as soon as the user fills the required organization. However the form validation refuses leaving the ID field blank. Please fix this logic.

**Comment by grubskim** [comment]
Added missing empty string check in \org\oscm\marketplace\bean\MarketplaceServiceBean.java.

**Comment by kwodzynski** [comment]
Tested with Docker image 17.5 2017/11/02. It works correctly
