### ISSUE TITLE
Cannot create new organization in Docker image with TomEE

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#842]
[Version]
OSCM 17.4.0
Docker image with TomEE

[How to reproduce]
Login as Platform Operator
Go to Create organization
Fill up all of neccesary fields
Click Save button

[Expected result]
New organization is created

[Observed result]
Red message "The operation failed."
The organization is not created

[Details]

I have tried a few different configuration of "Organization role". In each cases I have received the red communicat.
I have not noticed any error messages in the log files.

**Comment by DawidCh** [comment]
The problem is caused by not possibility to send an emails. After proper configuration of email server it should be fixed.
@kwodzynski test it again please.

**Comment by kwodzynski** [comment]
Tested on Docker image PRIVATE-BUILD-ON-DEC4B557CD2B2017/09/28 (OSCM 17.4.0).
If the email server is properly configured, the problem does not occur. Closing.
