### ISSUE TITLE
Procedure of adding the templates  for Openstack

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#844]
Procedure of adding the templates  for Openstack should be documented for Apache TomEE

**Comment by GoebelL** [comment]
Hi @kwodzynski

find my answer in https://github.com/servicecatalog/development/issues/845
 Just refer to the [OpenStack Integration Guide](https://github.com/servicecatalog/documentation/blob/master/Development/oscm-app-openstack/doc/en/OSIntegration.pdf).
The documentation for TomEE is in progress.  However, the respective UI feature is quite application server agnostic.

Check-out chapter 5.6 "Providing Templates for the Provisioning of Resources". There is extensive description how to proceed, same valid for TomEE.
