### ISSUE TITLE
Possibility of adding the Openstack's templates from GUI - docker

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#845]
If user of docker image wants to add Openstack's templates, he has to login to Docker machine and copy the files via terminal.
It would be a great feature if the user could add the templates using GUI of CTMG.

**Comment by GoebelL** [comment]
Hi @kwodzynski 

if I get you right, you are addressing something which we already have in OSCM. Note that you can import HEAT templates to the OpenStack adapter via UI. The user doesn't have to login to the Docker host and most likely even won't be able to. This was exactly the motivation for adding such feature.
See https://github.com/servicecatalog/development/issues/618.

Isn't this what you mean?

**Comment by kwodzynski** [comment]
@GoebelL 
Yes, that is it what I mean. Closing
