### ISSUE TITLE
On Chrome cursor keeps spinning after save is pressed

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#846]
[Version] OSCM 17.4.0 2017/10/09
Docker image with TomEE 
Chrome

[How to reproduce]
1. create marketable service, press save

[Expected result]
cursor stops spinning when operation is finished

[Observed result]
cursor does not stop spinning 

[Details]
This occurs with lots of dialog boxes, possibly all of them
Workaround: move cursor

**Comment by GoebelL** [comment]
This may be related with https://github.com/servicecatalog/development/issues/803

**Comment by GoebelL** [comment]
To be fixed with #803.
