### ISSUE TITLE
Initial log-in to controller UI only possible with PLATFORM_OPERATOR administrator

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#849]
[Version] OSCM 17.4.0 2017/10/09
Docker image with TomEE
Chrome

[How to reproduce]
1. default for logging into a controller after docker containers are started, is user "administrator" of PLATFORM_OPERATOR organization
2. In a productive environment, once this is done, the user and organization can be changed to the
controller managing organization. 

[Expected result]
Log-in to controller is possible

[Observed result]
The following prerequisites are necessary to be able to log-in to controller:
Organization must be supplier + tech. provider
Organization admin must have supplier and + tech provider roles

[Details]
In order for the default installation to work, one has to manually change the PLATFORM_OPERATOR organization and its administrator as described above.
These changes to organization and user cannot be reverted. This is not good. 
Another option should be discussed.

**Comment by shimizuf** [comment]
The initdb containers must set values for controller authentication during database initialization, ie before the first application startup. The behavior described is the default which is set in the initdb image. This can be overridden by using the following Docker environment variables, granted that the login details are already known:
CONTROLLER_ORG_ID
CONTROLLER_USER_KEY
CONTROLLER_USER_NAME
CONTROLLER_USER_PASS

However the caveat is that the CONTROLLER_USER_KEY is generated by the application/database when the user is created and cannot be reliably anticipated by the operator when the database is first initialized. To solve this I propose that we change controller authentication to not require the numeric user key set in the database. @GoebelL, @StavrevaS: Any thoughts on this?

**Comment by GoebelL** [comment]
>To solve this I propose that we change controller authentication to not require the numeric user key set >in the database.
User keys are difficult to replace here. I fear there are no alternative unique identifiers. With multi-tenancy each tenant has it's own user name space.

**Comment by DawidCh** [comment]
We can provide yet another user "supplier" with the rights supplier + tech. provider in the PLATFORM_OPERATOR organization. Will it solve the problem?

**Comment by SylviaDehn** [comment]
If the supplier/tech. provider is in the PLATFORM_OPERATOR organization it would be a problem since the rights are different.

**Comment by DawidCh** [comment]
Ok, yet another user "supplier" in different organization "supplier"?

**Comment by GoebelL** [comment]
Initial supplier will be provided with the sample data. See issue #856.  
For time being no action is needed. The workaround is to manually setup such supplier. If needed re-import it with database dump, i.e. for feature testing.

**Comment by DawidCh** [comment]
The temporary workaround: you can set data of technical provider and supplier in APP database directly and restart app server. Fix in progress.

**Comment by DawidCh** [comment]
Ok. Modification of user assigned for controllers has to be done as follows:
1. Login to oscm-app:8880/oscm-app as platform_operator
2. Login to oscm-app:8880/oscm-app-openstack/ as platform_operatro
3. Change user_id, user_password, user_key and save the data on oscm-app:8880/oscm-app-openstack/ page. You will get warning about user in wrong organization.
4. Change organization id for the controller on oscm-app:8880/oscm-app page and save.
From now your new user should be able to log in to controller.

**Comment by SylviaDehn** [comment]
This should not be closed, this is a merely a workaround! Because the initial problem that the administrator has to have additional rights added (which cannot be subsequently removed)  still exists.

**Comment by SylviaDehn** [comment]
This issue was moved to https://github.com/servicecatalog/oscm/issues/23
