### ISSUE TITLE
Non valid security certificate on learning center website

### ISSUE THREAD

**Issue by mfqih** [servicecatalog/development#850]
Hello,

https://ctmg02.openservicecatalogmanager.org/oscm-portal/marketplace?mId=MyCompany&locale=en

ctmg02.openservicecatalogmanager.org is using a non valid security certificate. It expired on tuesday 3rd October 2017 07:39. 
Error Code : SEC_ERROR_EXPIRED_CERTIFICATE

Rgds,

**Comment by GoebelL** [comment]
Hi,

this issue affects the test environment for the OSCM learning center. 

@mfalkenhahn 
Please take over here. Ensure the cron job for renewing the certificate is running and doesn't error.

**Comment by mfalkenhahn** [comment]
ctmg02.openservicecatalogmanager.org is using a valid security certificate.

**Comment by GoebelL** [comment]
Thanks.
