### ISSUE TITLE
Cannot change organization for controller management

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#851]
[Version] OSCM 17.4.0 2017/10/09
Docker image with TomEE

[How to reproduce]
new installation; with new Supplier/Tech Provider Organization created. 
org: SuppTechOrg orgid: abcdef, user: SuppTechAdmin1
1. as 'administrator' change PLATFORM_OPERATOR Organization to tech. provider
2. change 'administrator' to have technical provider manager role
3. as  'administrator', login with default settings to app
http://estst1.intern.est.fujitsu.com:8881/oscm-app  ... works ok
4. as  'administrator', login to openstack controller settings dialog
http://estst1.intern.est.fujitsu.com:8881/oscm-app-openstack  .... ok
5. change openstack controller settings:
User ID SuppTechAdmin1
User Key 10000
Password secret
Enter controller specific settings
Save configuration settings
6. (still logged into app in another tab)
change Organization ID of ess.openstack to abcdef
Close browser, delete cookies
7. login to app with 'administrator' (ok after restart of app container, but not sure if that was necessary)
8. login to http://estst1.intern.est.fujitsu.com:8881/oscm-app-openstack/ fails with error 401 (unauthorized)

[Expected result]
login should be possible

[Observed result]
error 401 

[Details]
error 401 was found in app catalina logfile

**Comment by SylviaDehn** [comment]
This is a test blocker, because I can only work with administrator which is not realistic.

**Comment by shimizuf** [comment]
@SylviaDehn: As far as I'm aware the restart of the app container should not be necessary after changing the settings.
At the time of the 401 error in the APP log, is there anything logged in the CORE log?

**Comment by SylviaDehn** [comment]
All log file entries that seem relevant are listed below

core container, catalina.2017-10-11.log:
=========================
 INFO [http-nio-8081-exec-2] org.oscm.security.ADMRealmImpl.handleLoginAttempt User '1000' successfully logged in.
(this is strange, because the user 10000 has been specified for openstack ....)

core container, localhost_access_log.2017-10-11.txt
================================
172.18.0.5 - - [11/Oct/2017:10:55:30 +0000] "GET /oscm-webservices/IdentityService/BASIC?wsdl HTTP/1.1" 200 79889
172.18.0.5 - - [11/Oct/2017:10:55:30 +0000] "POST /oscm-webservices/IdentityService/BASIC HTTP/1.1" 200 804
172.18.0.5 - - [11/Oct/2017:10:55:30 +0000] "POST /oscm-webservices/IdentityService/BASIC HTTP/1.1" 200 1062
10.140.18.97 - 10000 [11/Oct/2017:10:56:22 +0000] "POST /oscm-portal/user/list.jsf HTTP/1.1" 200 8455
10.140.18.49 - - [11/Oct/2017:10:59:45 +0000] "POST /oscm-portal/operator/manageConfiguration.jsf HTTP/1.1" 200 220

app container, catalina ......log:
==================
11-Oct-2017 10:55:30.481 INFO [http-nio-8881-exec-7] org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromWSDL Creating Service {http://oscm.org/xsd}IdentityService from WSDL: http://oscm-core:8081/oscm-webservices/IdentityService/BASIC?wsdl
11-Oct-2017 10:55:30.517 INFO [http-nio-8881-exec-7] org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromWSDL Creating Service {http://oscm.org/xsd}IdentityService from WSDL: http://oscm-core:8081/oscm-webservices/IdentityService/BASIC?wsdl
11-Oct-2017 10:55:30.562 INFO [http-nio-8881-exec-7] org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromWSDL Creating Service {http://oscm.org/xsd}IdentityService from WSDL: http://oscm-core:8081/oscm-webservices/IdentityService/BASIC?wsdl
11-Oct-2017 10:55:30.570 INFO [http-nio-8881-exec-7] org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromWSDL Creating Service {http://oscm.org/xsd}IdentityService from WSDL: http://oscm-core:8081/oscm-webservices/IdentityService/BASIC?wsdl

app, localhost_access_log:
================
10.140.18.97 - - [11/Oct/2017:10:55:17 +0000] "GET /oscm-app-openstack/ HTTP/1.1" 401 -
10.140.18.97 - - [11/Oct/2017:10:55:30 +0000] "GET /oscm-app-openstack/ HTTP/1.1" 401 -

**Comment by SylviaDehn** [comment]
[Build] 2017/10/16 tomee 
verified
