### ISSUE TITLE
Wrong default value in app db for APP_SUSPEND

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#853]
[Version] OSCM 17.4.0 2017/10/10
Docker image with TomEE

check app db for APP_SUSPEND

[Expected result]
APP_SUSPEND=false

[Observed result]
APP_SUSPEND=changeIt

[Details]
The default for APP_SUSPEND should be set correctly for app db.
See https://github.com/servicecatalog/development/issues/595

**Comment by shimizuf** [comment]
@SylviaDehn Can you please re-build and test with the oscm-dockerbuild branch add_property_app_suspend?

**Comment by SylviaDehn** [comment]
@shimizuf checked in branch add_property_app_suspend, is ok

**Comment by shimizuf** [comment]
@SylviaDehn Thanks, merged to fb_tomee_sles_based. Closing.

**Comment by SylviaDehn** [comment]
[Build] 2017/11/02 verified
