### ISSUE TITLE
Manage VAT rates reports country code missing

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#854]
[Version] OSCM 17.4.0 2017/10/12
Docker image with TomEE

[How to reproduce]
new installation; with new Supplier/Tech Provider Organization created.
1. log in as supp/tech provider
2. select menu 'Manage VAT rates'
3. click 'VAT support is enabled'
4. enter default VAT rate
5. press save 

[Expected result]
default VAT rate is saved

[Observed result]
error 'The country with the code is not supported for your organization.'

[Details]

**Comment by grubskim** [comment]
Introduced additional check for empty string in case of "country" and "customer" VATs. 

The reason for this issue was that when leaving country or customer VAT as empty, the application was trying to save it anyway, but couldn't find a country or customer code for verification.

**Comment by SylviaDehn** [comment]
[Build] 2017/11/02 verified
