### ISSUE TITLE
Authority check for user account management in OSCM Marketplace 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#858]
[Build] 
OSCM TomEE, 2017-10-16 

[How to reproduce]

 * Create an user A1 in organization PLATFORM_OPERATOR with only one initial user role as marketplace manager
 * Create a marketplace M1 for PLATFORM_OPERATOR
 * Open marketplace portal for M1 and log-in as A1
 * Open Users tab in Account > Users & Units 

[Expected behavior]
Users tab opens showing existing organization users.

[Observed behavior]
Error message "insufficient authorities" appears.

**Comment by SylviaDehn** [comment]
duplicate #848

**Comment by GoebelL** [comment]
I agree.
