### ISSUE TITLE
Service instance operation page for openstack is not available

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#859]
[Version] OSCM 17.4.0 2017/10/16
Docker image with TomEE

[How to reproduce]
Enter URL: http://estst1.intern.est.fujitsu.com:8880/oscm-app/controller/?cid=ess.openstack

[Expected result]
Log-in, and then Service instance operation page available

[Observed result]
Error 404 No webpage was found for the web address: http://estst1.intern.est.fujitsu.com:8880/oscm-app/controller/?cid=ess.openstack

**Comment by GoebelL** [comment]
Parameter cid is changed to controllerId. This is relevant for documentation.
@DawidCh please communicate this.

@SylviaDehn 
http://estst1.intern.est.fujitsu.com:8880/oscm-app/controller/?controllerId=ess.openstack should work.

**Comment by gertipoppel** [comment]
Is it controllerId or controllerid (in the code it looks like the latter - lowercase i)?

**Comment by gertipoppel** [comment]
@DawidCh Is it controllerId or controllerid (in the code it looks like the latter - lowercase i)?

**Comment by DawidCh** [comment]
controllerid

**Comment by gertipoppel** [comment]
Modified the doc for container-based OSCM accordingly.

**Comment by SylviaDehn** [comment]
verified
