### ISSUE TITLE
Controller provisioning url and action urls have changed to point to container

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#861]
[Version] OSCM 17.4.0 2017/10/16
Docker image with TomEE

[Details]
For technical services the provisioning and action urls have changed to point to containers.
This has to be reflected in the sample technical services and in the user doc.

e.g. 
provisioning url:
http://oscm-app:8880/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousOperationProxy?wsdl

action url:
http://oscm-app:8880/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousOperationProxy?wsdl

**Comment by SylviaDehn** [comment]
@gertipoppel please note this is also a doc issue

**Comment by SylviaDehn** [comment]
@DawidCh  I looked at your commit. Why do you leave port and server empty. As far as I believe they HAVE to point to the container addy and port, and this is fixed:
http://oscm-app:8880

**Comment by DawidCh** [comment]
@SylviaDehn as you wish. Fix on the way.

**Comment by SylviaDehn** [comment]
@DawidCh But only if my wish is correct ....

**Comment by DawidCh** [comment]
@SylviaDehn yes it is correct, so closing.

**Comment by SylviaDehn** [comment]
[Build] 2017/11/02 verified
