### ISSUE TITLE
Custom tab server info url not working

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#862]
[Version] OSCM 17.4.0 2017/10/16
Docker image with TomEE

[How to reproduce]
Enter custom tab url for openstack 

[Expected]
http://estst1:8880/oscm-app-openstack/serverInformation.jsf works

[Details]
Probably this path has changed, but to what?

**Comment by SylviaDehn** [comment]
@DawidCh please let me know what the path is, so I can test and Gerti can document it

**Comment by DawidCh** [comment]
@SylviaDehn the address is correct, but tomee in containers is still misconfigured. I'm working (in the meantime) to get it work. The problem is with the verification of signature at app side.

**Comment by DawidCh** [comment]
@grubskim take a look (debug) at https://github.com/servicecatalog/development/blob/b76365fb313578ae46b1aa44d0e76a96ca880335/oscm-app/javasrc/org/oscm/app/v2_0/service/APPlatformServiceBean.java#L294

**Comment by DawidCh** [comment]
After proper configuration APP_TRUSTSTORE, APP_TRUSTSTORE_BSS_ALIAS in oscm-app container the custom tab is available under address: http://<oscm-core-external-address>:8880/oscm-app-openstack/serverInformation.jsf
