### ISSUE TITLE
Chrome: Service Instance Details of controller instance looks weird

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#863]
[Version] OSCM 17.4.0 2017/10/16
Docker image with TomEE
Chrome ONLY

[How to reproduce]
1. go to controller service instances url
e.g. 
http://estst1.intern.est.fujitsu.com:8880/oscm-app/controller/?controllerid=ess.openstack
2. double click on an instance and page down in dialog box

[Expected result]
dialog box looks normal

[Observed result]
you can read the dialog box but there is a funny moving pixel background s. attachment 

[Details]
see attached file

**Comment by SylviaDehn** [comment]
![serviceinstancedetails](https://user-images.githubusercontent.com/15086024/31662914-8b14dc1a-b340-11e7-8ddf-3518d4f0fcb9.png)

**Comment by DawidCh** [comment]
This issue was moved to servicecatalog/oscm#6
