### ISSUE TITLE
Wrong default value in database BSSAPP - configurationsetting

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#864]
[Version] OSCM 17.4.0 2017/10/13
Docker image with TomEE

[How to reproduce]
In the default database "bssapp" created for Docker image I can find incorrect value in table "configurationsetting"

[Expected result]
APP_MAIL_RESOURCE is set to "APPMail"

[Observed result]
APP_MAIL_RESOURCE is set to "java:openejb/Resource/APPMail"

[Details]
It caused problems with mails and subscriptions.

**Comment by DawidCh** [comment]
The bug is fixed in newest build. @kwodzynski please verify.

**Comment by kwodzynski** [comment]
Verified with Open Service Catalog Manager 17.4.0 (2017/10/17)
