### ISSUE TITLE
Web Services End Points in Mock Product does not match with the ones in TomEE

### ISSUE THREAD

**Issue by victorhrsilva** [servicecatalog/development#865]
[Version] OSCM 17.4.0 2017/10/13 
Docker image with TomEE

[How to reproduce]
Try to use mockproduct app to Trigger Service Approve Action

[Expected result]
Mockproduct manage to approve the process trigged via WS

[Observed result]
Any operation of mock product receives connection time-out

[Details]
Current WebService endpoint of docker images e.g.: http://host:port/oscm-webservices/TriggerService/BASIC

Current implementation of Mock Product:
https://github.com/servicecatalog/development/blob/564e66593c9d272b8e04804410b633bc089aa203/oscm-integrationtests-mockproduct/javasrc/org/oscm/integrationtests/mockproduct/PortFactory.java#L39
https://github.com/servicecatalog/development/blob/564e66593c9d272b8e04804410b633bc089aa203/oscm-integrationtests-mockproduct/javasrc/org/oscm/integrationtests/mockproduct/PortFactory.java#L40

**Comment by StavrevaS** [comment]
Try to use the mock product from the repository https://github.com/servicecatalog/oscm-soap-mock
It is available as docker image in dockerhub

**Comment by victorhrsilva** [comment]
I have pull and started the docker with `docker run -d --name oscm-soap-mock -p 9680:8080 servicecatalog/oscm-soap-mock`

Target URL on process trigger: http://hostname:9680/oscm-soap-mock/NotificationService?wsdl
Base URL on Mock: http://hostname:8080/

Results:
Status | Reason
-- | --
 The external system did not accept the action | java.net.ConnectException: Connection timed out (Connection timed out)

**Comment by StavrevaS** [comment]
The docker build file should be extended to expose the necessary ports.

**Comment by DawidCh** [comment]
This issue was moved to servicecatalog/oscm#7
