### ISSUE TITLE
aws default entries missing for app db

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#866]
[Version] OSCM 17.4.0 2017/10/18
Docker image with TomEE

[How to reproduce]

1. manually enter aws def values in db 
2. restart container

[Expected result]
login to aws container works

[Observed result]
login to aws container does not work

[Details]
Please provide default values in app db for aws.  This is blocking testing. Even manually entering values does not work.

**Comment by kwodzynski** [comment]
Tested on Docker image created from hotfix/issue866 branch. It works as expected

**Comment by badziakp** [comment]
CONTROLLER_ID was hardcoded with value ess.openstack. I added the similar configuration for aws.

**Comment by SylviaDehn** [comment]
[Build] 2017/11/02 verified
