### ISSUE TITLE
Wrong links in mail "Account created"

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#871]
[Version] OSCM 17.5.0 2017/10/18
Docker image with TomEE

[How to reproduce]
Create new organization, customer or user

[Expected result]
The links in mail are correct:
- URL:  http
- Secure URL: https

[Observed result]
The link "URL" is incorrect.
- URL: https://estessbesci6.intern.est.fujitsu.com:8081/oscm-portal
- Secure URL: https://estessbesci6.intern.est.fujitsu.com:8081/oscm-portal

[Details]
Both links are the same (https)

**Comment by SylviaDehn** [comment]
This is ok if you specify the BASE_URL in the config settings as http with the correct port,
try it. Works for me ....

**Comment by kwodzynski** [comment]
@SylviaDehn You are right. I set the values and I received correct mail. Closing.
