### ISSUE TITLE
controller id missing for ess.openstack and ess.aws

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#872]
[Version] OSCM 17.5.0 2017/10/18
Docker image with TomEE

[How to reproduce]
1. login app:
http://estst1.intern.est.fujitsu.com:8880/oscm-app/

[Expected result]
controller id is shown for openstack and/or aws (or possibly nothing?)

[Observed result]
controller id field shows  ${CONTROLLER_ID}

[Details]
If the user is supposed to enter controller-id manually, then no controller Id should be shown. Or
is this just an error?

**Comment by badziakp** [comment]
This issue was caused by partially solution to #866. Now issue #866 is fixed so this problem shouldn't occur any more.

**Comment by SylviaDehn** [comment]
[Build] 2017/11/02 verified
