### ISSUE TITLE
version info not found for app

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#873]
[Version] OSCM 17.4.0 2017/10/19
Docker image with TomEE

[How to reproduce]
1. check version of app software
http://estst1.intern.est.fujitsu.com:8880/oscm-app/

[Expected result]
clicking on OSCM on the left gives me version info

[Observed result]
I do not know where to click, cursor does not change shape

**Comment by kwodzynski** [comment]
You need to click on the right of "USER ID: name_of_logged_user" (right top corner). The place to show version info should be standardized and always be displayed after click on OSCM logo.
The problem occurs on each controller.

**Comment by DawidCh** [comment]
This issue was moved to servicecatalog/oscm#10
