### ISSUE TITLE
online help not available

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#874]
[Version] OSCM 17.5.0 2017/10/19
Docker image with TomEE

[How to reproduce]
1. in portal, press help icon

[Expected result]
help is shown for dialog box

[Observed result]
nothing happens

**Comment by GoebelL** [comment]
It seems that portal help application is not deployed in core container.

**Comment by GoebelL** [comment]
Now online-help is correctly deployed and shown in the portal. Checked docker build from yesterday ~1 pm.

**Comment by SylviaDehn** [comment]
verified
