### ISSUE TITLE
audit log not available

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#875]
[Version] OSCM 17.5.0 2017/10/19
Docker image with TomEE

[How to reproduce]
1. turn on audit log in configuration settings
2. carry out operations that are normally logged in audit log
3. as platform operator export audit log

[Expected result]
audit log is exported

[Observed result]
error shown: No audit log data available for export.

**Comment by DawidCh** [comment]
This issue was moved to servicecatalog/oscm#11
