### ISSUE TITLE
Learning Center : The technical service (Web Calendar) is not available

### ISSUE THREAD

**Issue by mfqih** [servicecatalog/development#877]
Hello,

I got this error when trying to subscribe the web calendar free edition.
The requested action cannot be executed due to a connection error. The technical service for the subscription Web Calendar Free Edition  is currently not available.

https://openservicecatalogmanager.org/ui/product-oscm/learning-center-oscm-1/tutorial-oscm-saas.html

Regards,

**Comment by GoebelL** [comment]
@mfalkenhahn 
Please take over.
