### ISSUE TITLE
Very slow UI after "Get it Now"

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/development#882]
OSCM 17.4.
Provisioning Service based on APP (Powershell)

When using user "cmgt-business" and subcribing to a service (HyperV), the UI change from "Get it Now" to the configuration dialog takes 2 seconds which is very good.
When using the user "cmgt-it"  (who is in the supplier organization) and subcribing to the same service (HyperV) the change from "Get it Now" to the configuration dialog takes about 180 seconds which is too long. 
Please investigate

**Comment by shimizuf** [comment]
Hi @uhu133 , this repository has been deprecated and the new active repository is servicecatalog/oscm. Could you please move this issue to the new repository?

**Comment by uhu133** [comment]
duplicated into servicecatalog/oscm
