### ISSUE TITLE
Report "payment preview" error when using "PWD" in technical service as parameter

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/development#886]
[system.log](https://github.com/servicecatalog/development/files/1559726/system.log)
When using the type PWD in a parameter of a technical service the following two issues occurs:

1. you can set a price on PWD when "define price for service". This does not make sense, because PWD is like a STRING

2. After booking a service with a PWD parameter, the report "payment preview" does not show any results. Log file system.log shows an enum error (see log file attached).

OSCM 17.4.

**Comment by GoebelL** [comment]
Fixed in OSCM 17.8.
