### ISSUE TITLE
APP: UDA values are not propagated to service parameter in method createInstance

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/development#888]
When using an UDA for a APP provisioned service parameter, the UDA value is not propagated to service parameter when the Java method createInstance is called. This happens later when the APP state machine triggers later activities. 

As a result "createInstance" gets the wrong service parameters value.

OSCM 17.4

**Comment by kowalczyka** [comment]
Could you please give more details? 

I have just investigate propagation of UDAs when creating new subscription both sync and async one and when createInstance (or asyncCreateInstance) is called the uda is there on InstanceRequest -> attributeValue list.

Are you using synchronous or asynchronous provisioning?
Could you share your technicalservice xml which is used?
Which Java method (which class) you meant ("the Java method createInstance")?

**Comment by uhu133** [comment]
We are using asynchronous provisioning. I'll attach the source and the technical service.
[PowerShell.zip](https://github.com/servicecatalog/development/files/1685768/PowerShell.zip)



public class PowershellController implements APPlatformController {
    @Override
    public InstanceDescription createInstance(ProvisioningSettings settings) throws APPlatformException {
              }
}

**Comment by GoebelL** [comment]
@uhu133 
Attributes are not copied to InstanceDescription in your PowershellController. Add setChangedAttributes  around line 117.
[...]
 InstanceDescription id = new InstanceDescription();
 id.setInstanceId(UUID.randomUUID().toString());
 id.setChangedParameters(settings.getParameters());
 **id.setChangedAttributes(settings.getAttributes());**
