### ISSUE TITLE
Repeated subscription modification error 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#893]
[Environment] 17.4 Glassfish, custom controller  

[How to reproduce]
1. Async subscription modification with custom controller is attempted with invalid parameter.  
(e.g. value of disk size paramater exceeding capacity that can be provided by the cloud side)
2. As subscription is back to ACTIVE state, user repeats modification with corrected the parameter
3. Error from Exception is shown in subscription UI

[Detail]
Error occurs in APP attempting to persist parameters with null values. See attached log

**Comment by GoebelL** [comment]
[app_server_log_from_repeated_modify_after_aborted_subscription.txt](https://github.com/servicecatalog/development/files/1649799/app_server_log_from_repeated_modify_after_aborted_subscription.txt)

**Comment by GoebelL** [comment]
See around line 108.

**Comment by GoebelL** [comment]
[additional info]
The issue should be reproduce-able with OSCM sample controller, when throwing an APPlatformException in  dispatch() (Dispatcher.java) at point when handling case MODIFICATION_REQUESTED.

**Comment by StavrevaS** [comment]
The parameters coming from OSCM to APP can be null, but APP converts the null values to empty strings.
The same should be assured about changed parameters coming from the controller side (with InstanceStatus.setChangedParameters). Please check this issue.

**Comment by GoebelL** [comment]
@kowalczyka 
Please take over at your site

**Comment by badziakp** [comment]
I checked method InstanceStatus.setChangedParameters using Sample controller. When this method gets a map with any parameter which value is null then the exception "org.postgresql.util.PSQLException: ERROR: null value in column "parametervalue" violates not-null constraint" is thrown and error log can be found in server.log of app domain.

**Comment by StavrevaS** [comment]
@badziakp it is exactly as I expected. Please solve with converting the null values to empty strings.

**Comment by grubskim** [comment]
Fixed with https://github.com/servicecatalog/development/pull/895

**Comment by GoebelL** [comment]
@SylviaDehn 
Please verify with last unit build

**Comment by SylviaDehn** [comment]
[Build] 17.3.1 verified with sample controller
