### ISSUE TITLE
Wrong context for birt is used in HTTPS URL

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#9]
Wrong context for BIRT is used in HTTPS URL value of org/oscm/internal/types/enumtypes/ConfigurationKey.java 

 @Example("http://<your server>:<your port>/birt/frameset?__report=${reportname}.rptdesign&SessionId=${sessionid}&__locale=${locale}&WSDLURL=${wsdlurl}&SOAPEndPoint=${soapendpoint}&wsname=Report&wsport=ReportPort or https://<your server>:<your port>/**eclipse-birt-runtime**/frameset?__report=${reportname}.rptdesign&SessionId=${sessionid}&__locale=${locale}&WSDLURL=${wsdlurl}&SOAPEndPoint=${soapendpoint}&wsname=ReportSecure&wsport=ReportSecurePort")

The context should be "birt" not "eclipse-birt-runtime" also for the HTTPS URL.

**Comment by DawidCh** [comment]
Issue under the tests.

**Comment by DawidCh** [comment]
Bug fixed and merged to master.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/10 verified
