### ISSUE TITLE
 Filtering at Service field no longer works in lists

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#91]
[Steps to reproduce]

1. Supplier defines marketable service and localization for english and japanese (not german).
2. User (any) has localization set to german and logs in to marketplace.
3. In the subscirption list user sees english localized values for service name (as there is not german localization available).
4. User tries to filter subscription by service id column.

[Expected result]
The expected subscriptions are found

**Comment by jiangweiyi** [comment]
Verified by FNST
[Verified Build]16.0 fix5
[Detail]Filtering at Service field can work now. This issue has already been verified in bugzilla.
