### ISSUE TITLE
Wrong access info in OpenStack Sample Service

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/development#917]
when creating an instance with the OSCM OpenStack Sample Service the access info at "My Subscriptions" shows the dns name of the server where OSCM is running and NOT the IP address or dns name of the OpenStack server which was created by subscription.
![capture](https://user-images.githubusercontent.com/32158057/41145714-4e9460ac-6b01-11e8-98ce-7789a0aecb7f.JPG)

**Comment by uhu133** [comment]
![capture2](https://user-images.githubusercontent.com/32158057/41145800-864afa9c-6b01-11e8-9e6a-6037ce822301.JPG)
The corresponding OpenStack instances.

**Comment by GoebelL** [comment]
This issue was moved to servicecatalog/oscm#98
