### ISSUE TITLE
Logs generated for external price models

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#92]
[Version]
16.0.3+

[How to reproduce]
0. Switch on audit logging
1. Define price model with external billing
2. Go to Operation > Export audit log
3. Select user role All
4. Check "Edit price model type to free of charge for service"
5. Export audit log

[expected  result]
No record of the this service

[observed  result]
Service was listed

[details]
The help states "A service manager defined or changed a free-of-charge service price model so that no costs are charged for using the service.", but I didn't select free-of-charge.

**Comment by GoebelL** [comment]
Please check for similar cases. E.g. other logs recorded with external billing services.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/03
