### ISSUE TITLE
Question on vmware-connector: Import of VMs  

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/development#921]
what is the basic functionality of this feature?

Can VMs be imported as subscriptions?
Are the VMs mapped to existing Marketable Service types?
Can imported VMs be changed once provided as a subscription (e.g. with new parameters)?

**Comment by GoebelL** [comment]
Hi @uhu133 
The VMWare connector provides for importing VCenter configurations with network, loadbalancer, storage etc. via CSV. Importing of VMs is not in the scope. Where did you pick up this? 
Never heard of such but clearly it's possible. Basically, I could think of a script based solution to back import VMs as subscription. This could be implemented on base of OSCM WS API and VSphere SDK. 
Let me know if such is in your mind.

**Comment by GoebelL** [comment]
This is handled in https://github.com/servicecatalog/oscm/issues/148
