### ISSUE TITLE
build failed error

### ISSUE THREAD

**Issue by bharath7394** [servicecatalog/development#931]
Dear sir,
we are trying to build ,The build.lib is working fine then after if we try to build build.BES the following error occurs please suggest the solution for this

BUILD FAILED
C:\Users\bharathmc\srikanth\oscm\oscm-build\build.xml:273: The following error occurred while executing this line:
C:\Users\bharathmc\srikanth\oscm\oscm-build\build.xml:146: The following error occurred while executing this line:
C:\Users\bharathmc\srikanth\oscm\oscm-build\defaultprojectbuild.xml:141: Error starting wsgen: null

Total time: 31 seconds

we went to the built.xml and it is showing it is showing "Resolves dependencies, compiles and packages" but what dependency required we not understand as we have run the build.lib for dependencies(successfully build the build.lib) 

please let us know which dependency we missed

**Comment by GoebelL** [comment]
@bharath7394 
See https://github.com/servicecatalog/oscm/issues/395
