### ISSUE TITLE
build failed error

### ISSUE THREAD

**Issue by bharath7394** [servicecatalog/development#932]
Hi,
Sir,
  Am getting the following build error while building the "ALL.BUILD" and also the OSCM jar's(OSCM-api-client-handler, OSCM-extsvc-platform.jar, junit-4.5.jar, OSCM-api-client-handler.jar, WSDL) and some other jar's(postgresql-9.4.1206.jar, hibernate-commons-annotations-4.0.1.jar, hibernate-core-4.1.8.final.jar, hibernate-entitymanager-4.1.8.final.jar, hibernate-jpa-2.0-api-1.0.1.final.jar, javaee.jar, javassist-3.15.0-GA.jar, jboss-logging-3.1.0.GA.jar, jboss-transaction-app-1.1-spec-1.0.0.final.jar) are missing where to get those jar's please help to overcome this.

_dependencies:
_copyDocument:
package:
_init:
     [echo] ====================================================================================
     [echo] Building Project example-service (PRIVATE-BUILD-ON-bharath-20190816044552)
     [echo] ====================================================================================
     [echo] Project Source: C:\Users\bharathmc\srikanth_development\development\example-service
     [echo] Working Dir:    C:\Users\bharathmc\srikanth_development\development\oscm-build\result\work\example-service
     [echo] Packaging Dir:  C:\Users\bharathmc\srikanth_development\development\oscm-build\result\package\example-service
_copyjavares:
_checkjre:
compile:
    [javac] Compiling 84 source files to C:\Users\bharathmc\srikanth_development\development\oscm-build\result\work\example-service\classes

BUILD FAILED
C:\Users\bharathmc\srikanth_development\development\oscm-devruntime\javares\devscripts\build-dev-PackageDeploy.xml:170: The following error occurred while executing this line:
C:\Users\bharathmc\srikanth_development\development\oscm-build\build.xml:332: The following error occurred while executing this line:
C:\Users\bharathmc\srikanth_development\development\oscm-build\build.xml:208: The following error occurred while executing this line:
C:\Users\bharathmc\srikanth_development\development\oscm-build\defaultprojectbuild.xml:103: C:\Users\bharathmc\srikanth_development\development\example-service\{java.home.dir}\jre\lib does not exist.

Total time: 16 seconds

**Comment by GoebelL** [comment]
Hi @bharath7394 

two things. First, please check out the [oscm repo in GitHub](https://github.com/servicecatalog/oscm) for the latest version of OSCM. If you have any issues on OSCM please post there.
Second, please use `BUILD.LIB` and `BUILD.BES` from `oscm-devruntime\javares\build-oscmaas.xml` for buliding OSCM as described in the readme.
