### ISSUE TITLE
Users of reseller or broker organizations cannot write reviews

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#94]
Users of reseller or broker organizations cannot write reviews to partner services they have subscribed, in case they are not administrators.

[How to reproduce]
1. As plattform administrator create a supplier s1, a reseller r1 and make r1 owner of a marketplace 
    mr1 
2. As service manager of s1 create a market service m1 and grant resale permissions to reseller r1
3. As admin of reseller r1 create a user c1 and publish m1 on mr1
4. Login to mr1 as admin of reseller r1, subscribe to m1 and assign c1
5. Login to mr1 as c1

[expected result]
c1 can create review

[observed result]
Create review is disabled

**Comment by kowalczyka** [comment]
Just to have the common understanding (I am trying to reproduce it):
1) What do you mean by "Create review is disabled" - button is disabled or button does not appear at all? In my environement user c1 can't see the button at all
2) Can admin of reseller r1 write the reviews? In my environement admin reseller r1 can't also see the button at all and he can't write the review

**Comment by GoebelL** [comment]
The issue was originally reported from FJ. I know for sure that I reproduce it, but I don't remember all details.
>1) What do you mean by "Create review is disabled" - button is disabled or button does not appear at >all? In my environement user c1 can't see the button at all 
Not sure. However both is wrong anyway. See [excepted result]
>2) Can admin of reseller r1 write the reviews?
I think yes, but the general answer is that it has to be consistent. Please check the documentation and marketplace FAQ. It has to behave the same for subscriptions of reseller services as for supplier service subscriptions. If administrators who have created subscriptions of supplier services can review them even without being assigned it has to be same for reseller services.

**Comment by kowalczyka** [comment]
I have been trying to reproduce the problem again but I can't do this on the latest version 16.0.6.

Everything is working here as expected.

**Comment by SylviaDehn** [comment]
[Build]2016/08/02 verified
