### ISSUE TITLE
Displaying external subscription price models for suppliers should available by default

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#96]
[Version]
16.0.3+

[How to reproduce]
1. Customer subscribes a service with external billing
2. Service manager checks the subscription in view subscription page

[Observed behavior]
Display price model is not available from beginning. First after importing the subscription price model, it's available the display button becomes active.

[Expected behavior]
Display price model is available from beginning and initially shows the default service price model.

**Comment by badziakp** [comment]
[Fix details]
Displaying external price model on Customer -> View subscriptions  is always available.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/03 verified
