### ISSUE TITLE
Disable removal of native billing adpapter

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#97]
[Version]
16.0.4

[How to reproduce]
1. Login as administrator
2. Select "Manage billing systems"
3. Add external billing
4. Set external billing as default
5. Delete Native Billing

[Expected result]
- Delete button isn't active in Native Billing, or
- Native Billing cannot be deleted

[Observed result]
- Delete button is active in Native Billing, and
- Native Billing can be deleted

**Comment by GoebelL** [comment]
The definition needs to be clarified. Currently, if native billing is set as 'not default' it can be deleted. This is also in accordance with the documentation.

**Comment by mdehn** [comment]
Native billing must not be deleted.

**Comment by GoebelL** [comment]
Removing native billing is not a problem, since it can be restored. This is in accordance with the documentation.

**Comment by misako0927** [comment]
Please write how to restore native billing in help page if this function will be decided.

**Comment by SuessI** [comment]
I added a corresponding note to the online help (operator_manageBillingAdapters.xml). Will be available on 2016-06-02.
