### ISSUE TITLE
"New Billing system" view is closed when the duplicate error in the view is happened.

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/development#99]
[Version]
16.0.4

[How to reproduce]
1) Open Manage billing system
2) Click "Add" button and Show "billing system" view
3) Input the existing Billing system ID
4) Click "Save" button

[Expected result]
 Continue to edit in New billig system even if the error is happened.

[Observed result]
 New billig system view is closed when the error is happeded,.

**Comment by kowalczyka** [comment]
[Details of fix]
Validation of billing adapter id added to be invoked before saving the billing adapter.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/02 verified
